import type { Metadata } from "next";
import { TrustMark } from "@/components/trust-mark";
import { loadPublicIndustry } from "@/lib/industry-public";
import { publicationTypeLabel } from "@/lib/industry-hub";
import { publicPageMetadata } from "@/lib/seo";
import { brand } from "@/lib/brand";
import { AdvocacyPolicyWatch } from "@/components/advocacy-policy-watch";
import "./industry.css";

export const dynamic="force-dynamic";
export const metadata:Metadata=publicPageMetadata("Industry Hub",`Official manufacturer profiles, announcements, product launches, packaging changes, and alerts—clearly sourced and reviewed by ${brand.name}.`,"/industry");

export default async function IndustryHubPage(){
  const{profiles,publications,registryRecords}=await loadPublicIndustry();
  const hasOfficialContent=profiles.length>0||publications.length>0;
  return <main className="shell wideShell industryPage"><section className="industryHero"><div><div className="eyebrow">{brand.name} Industry Hub</div><h1>The industry, in its own words.</h1><p className="lede">Official profiles, releases, factory news, education, packaging changes, and counterfeit alerts—published with visible sources and permanent corrections.</p><div className="ctaRow"><a className="button" href="/industry/registry">Explore product & release registry</a></div></div><aside><TrustMark kind="Official"/><strong>Official source</strong><p>Published directly by the manufacturer or organization. This identifies who made the statement; it does not mean {brand.name} independently verified or endorsed every claim.</p></aside></section>
    <section className="industryPrinciples"><article><span>01</span><strong>Authorized source</strong><p>Official records come from a verified organization workspace.</p></article><article><span>02</span><strong>Founder publication gate</strong><p>Submission, approval, and publication are separate decisions.</p></article><article><span>03</span><strong>Permanent history</strong><p>Updates and corrections never erase the record that came before.</p></article></section>
    <section className="industryPrinciples registryPreview"><article><span>{registryRecords.filter(item=>item.recordType==="product").length}</span><strong>Official products</strong><p>Current, limited, discontinued, and historical product records.</p></article><article><span>{registryRecords.filter(item=>item.recordType==="release").length}</span><strong>Dated releases</strong><p>Launches and availability states preserved beyond the announcement.</p></article><article><span>{registryRecords.filter(item=>item.recordType==="packaging").length}</span><strong>Artifact revisions</strong><p>Bands, boxes, seals, codes, and authentication guidance.</p></article></section>
    <section className="industryProfiles"><div className="sectionHead"><div><div className="eyebrow">Verified organizations</div><h2>Official digital homes</h2></div><span>{profiles.length} published</span></div><div>{profiles.map(profile=><a href={`/industry/${profile.slug}`} key={profile.id}><TrustMark kind="Official" compact/><h3>{profile.payload.displayName}</h3><p>{profile.payload.summary}</p><small>{profile.partnerType} · Published {new Date(profile.publishedAt).toLocaleDateString()}</small><strong>Open official profile →</strong></a>)}</div>{!hasOfficialContent&&<div className="industryPublicationStandard"><div><div className="eyebrow">Publication standard</div><h3>Trust comes before volume.</h3><p>No organization profile or statement has completed every verification, approval, and publication gate yet. Hojavía will leave this space intentionally quiet until the first qualified record is ready.</p></div><div><TrustMark kind="Official" compact/><p>Drafts, submissions, incomplete research, and paid placement never appear as verified industry content.</p><a className="textLink" href="/trust">Understand Hojavía trust labels →</a></div></div>}</section>
    {publications.length>0&&<section className="industryNewsroom"><div className="sectionHead"><div><div className="eyebrow">Official newsroom</div><h2>Direct from verified organizations</h2></div><a className="textLink" href="/trust">Understand trust labels →</a></div><div>{publications.map(item=><article key={item.id}>{item.payload.heroImageUrl&&<img src={item.payload.heroImageUrl} alt=""/>}<div><TrustMark kind="Official" compact/><small>{publicationTypeLabel(item.type)} · {item.organizationName}</small><h3>{item.payload.title}</h3><p>{item.payload.summary}</p><footer><time>{new Date(item.publishedAt).toLocaleDateString()}</time><a href={`/industry/${item.slug}#publication-${item.id}`}>Read official statement →</a></footer></div></article>)}</div></section>}
    <section className="industryCulture"><div className="sectionHead"><div><div className="eyebrow">The living record</div><h2>Study the craft. Preserve the history.</h2><p>Explore Hojavía’s sourced educational and historical work while the official organization registry grows deliberately.</p></div></div><div className="industryCultureGrid"><a href="/learn/seed-to-smoke"><span>01 · Craft</span><h3>Seed to smoke</h3><p>Follow tobacco from seed selection and cultivation through curing, fermentation, blending, rolling, and rest.</p><strong>Explore the complete journey →</strong></a><a href="/learn/blending"><span>02 · People</span><h3>The blender’s architecture</h3><p>Understand the distinct roles of wrapper, binder, filler, origin, processing, and the people shaping the final cigar.</p><strong>Study blending →</strong></a><a href="/learn/release-chronology"><span>03 · History</span><h3>Release chronology</h3><p>Separate launch year, production period, collection year, and the age of the cigars inside a presentation.</p><strong>Read the chronology guide →</strong></a><a href="/learn/habanos-authenticity"><span>04 · Protection</span><h3>Authentication and evidence</h3><p>Learn how packaging, provenance, codes, documented changes, and uncertainty should be evaluated without shortcuts.</p><strong>Review authentication guidance →</strong></a></div></section>
    <AdvocacyPolicyWatch/>
    <section className="industryClosing"><div><div className="eyebrow">For collectors</div><h2>Explore only what the evidence supports.</h2><p>Use the public registry for qualified official records and evidence-aware cigar identities. Unfinished research remains visibly unfinished.</p><a className="button" href="/industry/registry">Open the living registry</a></div><div><div className="eyebrow">For the trade</div><h2>Help preserve your own record.</h2><p>Growers, blenders, factories, manufacturers, retailers, lounges, writers, and educators can prepare sourced information for independent review.</p><a className="button secondary" href="/partner-workspace">Represent an organization</a></div></section>
  </main>;
}
