import { z } from "zod";
import type { InventoryItem, ProfessionalRating } from "./types";
import { responseOutputText } from "./cigar-vision";
import { cigarProductKey } from "./cigar-identity";

export const ProfessionalRatingSchema = z.object({ ratingId:z.string().trim().min(1), inventoryId:z.string().trim().min(1), publication:z.string().trim().min(1), score:z.coerce.number().min(50).max(100), reviewDate:z.string().trim().optional(), reviewer:z.string().trim().optional(), sourceUrl:z.string().url(), matchConfidence:z.enum(["High","Medium","Low"]), matchedVintage:z.union([z.string(),z.number()]).optional(), summary:z.string().trim().max(1000).optional(), createdAt:z.string().datetime() });
export const ProfessionalRatingCreateSchema=ProfessionalRatingSchema.omit({ratingId:true}).extend({submissionId:z.string().uuid().optional()}).strict();
const RatingCandidateSchema=z.object({ publication:z.string(), score:z.number().min(50).max(100), reviewDate:z.string(), reviewer:z.string(), sourceUrl:z.string().url(), matchConfidence:z.enum(["High","Medium","Low"]), matchedVintage:z.union([z.string(),z.number()]).nullable(), summary:z.string() });
export const RatingResearchSchema = z.object({ ratings:z.array(RatingCandidateSchema).max(8), notes:z.string() });
export type RatingResearch = z.infer<typeof RatingResearchSchema>;
const SourcedRatingResearchSchema=z.object({ratings:z.array(RatingCandidateSchema.extend({matchedBrand:z.string(),matchedLine:z.string(),matchedVitola:z.string()})).max(8),notes:z.string()});
const researchSchema={type:"object",additionalProperties:false,properties:{ratings:{type:"array",maxItems:8,items:{type:"object",additionalProperties:false,properties:{publication:{type:"string"},score:{type:"number",minimum:50,maximum:100},reviewDate:{type:"string"},reviewer:{type:"string"},sourceUrl:{type:"string"},matchConfidence:{type:"string",enum:["High","Medium","Low"]},matchedVintage:{type:["string","number","null"]},matchedBrand:{type:"string"},matchedLine:{type:"string"},matchedVitola:{type:"string"},summary:{type:"string"}},required:["publication","score","reviewDate","reviewer","sourceUrl","matchConfidence","matchedVintage","matchedBrand","matchedLine","matchedVitola","summary"]}},notes:{type:"string"}},required:["ratings","notes"]} as const;
export function ratingsForInventory(ratings:ProfessionalRating[],inventoryId:string){return ratings.filter(rating=>rating.inventoryId===inventoryId).sort((a,b)=>b.score-a.score)}
export function ratingSummary(ratings:ProfessionalRating[],inventoryId:string){const matches=ratingsForInventory(ratings,inventoryId);return{count:matches.length,highest:matches[0]?.score,average:matches.length?Math.round(matches.reduce((sum,rating)=>sum+rating.score,0)/matches.length*10)/10:undefined,publications:new Set(matches.map(rating=>rating.publication)).size}}
export function exactRatingResearch(item:InventoryItem,input:z.infer<typeof SourcedRatingResearchSchema>):RatingResearch{const target=cigarProductKey(item);const accepted=input.ratings.filter(rating=>cigarProductKey({brand:rating.matchedBrand,line:rating.matchedLine,vitola:rating.matchedVitola})===target);return{ratings:accepted.map(({matchedBrand:_,matchedLine:__,matchedVitola:___,...rating})=>rating),notes:accepted.length===input.ratings.length?input.notes:`${input.notes}${input.notes?" ":""}${input.ratings.length-accepted.length} nearby-product result${input.ratings.length-accepted.length===1?" was":"s were"} excluded because brand, line, and vitola did not exactly match.`}}
export function ratingResearchHref(inventoryId:string){return `/ratings?inventoryId=${encodeURIComponent(inventoryId)}#rating-${encodeURIComponent(inventoryId)}`}
export function prioritizeRatingInventory(items:InventoryItem[],inventoryId?:string){if(!inventoryId)return items;const selected=items.find(item=>item.inventoryId===inventoryId);return selected?[selected,...items.filter(item=>item.inventoryId!==inventoryId)]:items}
export async function researchCigarRatings(item:InventoryItem){const apiKey=process.env.OPENAI_API_KEY?.trim();if(!apiKey)throw new Error("Professional rating research is not configured");const prompt=`Find published professional review scores for this exact premium cigar: brand ${item.brand}; line ${item.line}; vitola ${item.vitola}; release or vintage ${item.vintage??"unknown"}. Search rating publishers and established cigar publications such as Cigar Aficionado, Cigar Journal, halfwheel, Blind Man's Puff, and comparable editorial sources. Include a result only when the source page directly supports a numeric score and the exact brand, line, and marketed vitola match. Echo the identity stated by the source into matchedBrand, matchedLine, and matchedVitola. A nearby Arturo Fuente family, OpusX release, Forbidden X cigar, ToyMaker cigar, different size, or differently named presentation is not the requested product. Mark High confidence only when all identity fields and any stated vintage match; Medium when the exact cigar matches but vintage is unspecified. Do not return Low-confidence nearby products. Do not treat retailer customer ratings, star ratings, forum posts, search snippets without a source page, or collection-level ratings as professional scores. Summarize each review in original words without copying review text. Use the canonical direct source URL. Return an empty ratings array when no defensible exact rating is found.`;const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_VISION_MODEL?.trim()||"gpt-5.6-terra",reasoning:{effort:"medium"},store:false,max_output_tokens:3200,tools:[{type:"web_search"}],include:["web_search_call.action.sources"],input:prompt,text:{format:{type:"json_schema",name:"professional_rating_research",strict:true,schema:researchSchema}}}),signal:AbortSignal.timeout(100_000)});const payload=await response.json();if(!response.ok)throw new Error((payload as {error?:{message?:string}}).error?.message||`OpenAI request failed (${response.status})`);const text=responseOutputText(payload);if(!text)throw new Error("Research returned no rating results");return exactRatingResearch(item,SourcedRatingResearchSchema.parse(JSON.parse(text)))}
