import { canonicalBrand, cigarBrands } from "./brand-directory";
import { canonicalCigarIdentity } from "./cigar-identity";
import type { CatalogCigar } from "./types";

export type CigarTradition="Habanos"|"New World"|"Unresolved";
export type LineageNode={catalogId:string;identityId:string;brand:string;line:string;vitola:string;releaseYear?:string|number;edition?:string;tradition:CigarTradition;relationship:"Same line"|"Same maker"|"Edition family";label:string};
export function cigarTradition(brand:string):CigarTradition{const found=cigarBrands.find(value=>value.name===canonicalBrand(brand));return found?.segment==="Habanos"?"Habanos":found?"New World":"Unresolved"}
function editionFamily(value:CatalogCigar){const text=`${value.line} ${value.edition||""} ${value.packaging||""}`.toLowerCase();if(/regional|regionales|regional edition/.test(text))return"Regional Edition";if(/edici[oó]n limitada|limited edition/.test(text))return"Limited Edition";if(/gran reserva/.test(text))return"Gran Reserva";if(/\breserva\b/.test(text))return"Reserva";if(/la casa del habano|\blcdh\b/.test(text))return"La Casa del Habano";if(/habanos specialist/.test(text))return"Habanos Specialist";if(/anniversary|aniversario/.test(text))return"Anniversary";if(/batch|small batch/.test(text))return"Batch release";return value.discontinued?"Discontinued":"Regular production"}
export function buildCigarLineage(selected:CatalogCigar,catalog:CatalogCigar[]):{tradition:CigarTradition;family:string;identityRule:string;nodes:LineageNode[]}{
  const brand=canonicalBrand(selected.brand),tradition=cigarTradition(brand),family=editionFamily(selected);
  const nodes=catalog.filter(value=>value.catalogId!==selected.catalogId&&canonicalBrand(value.brand)===brand).map(value=>{const candidateFamily=editionFamily(value);const relationship=value.line.trim().toLowerCase()===selected.line.trim().toLowerCase()?"Same line":candidateFamily===family&&family!=="Regular production"?"Edition family":"Same maker";return{catalogId:value.catalogId,identityId:canonicalCigarIdentity({...value,vintage:value.releaseYear}).identityId,brand:value.brand,line:value.line,vitola:value.vitola,releaseYear:value.releaseYear,edition:value.edition,tradition:cigarTradition(value.brand),relationship,label:candidateFamily} satisfies LineageNode}).sort((a,b)=>a.relationship.localeCompare(b.relationship)||String(b.releaseYear||"").localeCompare(String(a.releaseYear||""))||a.line.localeCompare(b.line)).slice(0,12);
  return{tradition,family,identityRule:tradition==="Habanos"?"Marca, vitola, edition program, territory, release year, packaging, and box or cosecha context stay distinct.":tradition==="New World"?"Maker, line, blend generation, vitola, factory, production type, and release or batch stay distinct.":"Tradition remains unresolved until attributable maker evidence is attached.",nodes};
}
