import ExcelJS from "exceljs";
import { InventoryInputSchema, normalizeInventory } from "./inventory-model";
import type { InventoryItem } from "./types";

export const MAX_IMPORT_BYTES=5*1024*1024,MAX_IMPORT_ROWS=5000;
const aliases:Record<string,keyof InventoryItem>={"inventory id":"inventoryId",id:"inventoryId",manufacturer:"brand",maker:"brand",brand:"brand",family:"line",collection:"line",series:"line",line:"line",blend:"line",vitola:"vitola",size:"vitola","release year":"vintage","production year":"vintage",vintage:"vintage",quantity:"currentQty",qty:"currentQty","current quantity":"currentQty",boxes:"fullBoxQty","box quantity":"fullBoxQty","sticks per box":"sticksPerBox",singles:"looseStickQty","loose sticks":"looseStickQty",packaging:"packaging","box code":"boxCode","retail value":"retailValue","value per cigar":"retailValue","unit value":"retailValue",cost:"actualCost","actual cost":"actualCost",storage:"storageLocationId",humidor:"storageLocationId",notes:"notes"};
const numeric=new Set<keyof InventoryItem>(["currentQty","fullBoxQty","sticksPerBox","looseStickQty","retailValue","actualCost"]);
export type ImportPreviewRow={row:number;item?:InventoryItem;errors:string[];warnings:string[];duplicate:boolean};
export type ImportPreview={fileName:string;rows:ImportPreviewRow[];valid:number;invalid:number;duplicates:number;columns:string[]};
function cleanHeader(value:unknown){return String(value??"").trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ")}
function safeCell(value:unknown):string|number|undefined{if(value===null||value===undefined||value==="")return undefined;if(typeof value==="object")throw new Error("Formulas, hyperlinks, rich text, and embedded spreadsheet objects are not accepted");if(typeof value==="string"&&/^[=+@-]/.test(value.trim()))throw new Error("Formula-like cell values are not accepted");return typeof value==="number"?value:String(value).trim()}
function csvRows(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===","&&!quoted){row.push(cell);cell=""}else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&text[i+1]==="\n")i++;row.push(cell);rows.push(row);row=[];cell=""}else cell+=char}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function identity(item:Pick<InventoryItem,"brand"|"line"|"vitola"|"vintage">){return[item.brand,item.line,item.vitola,item.vintage??""].map(value=>String(value).trim().toLowerCase().replace(/\s+/g," ")).join("|")}
function makeId(row:number){return`IMPORT-${Date.now()}-${row}-${crypto.randomUUID().slice(0,8)}`}
export async function parseInventoryFile(fileName:string,bytes:Buffer,existing:InventoryItem[]):Promise<ImportPreview>{
 if(bytes.length>MAX_IMPORT_BYTES)throw new Error("File exceeds the 5 MB upload limit");const extension=fileName.toLowerCase().split(".").pop();if(!["csv","xlsx"].includes(extension||""))throw new Error("Only .csv and .xlsx files are accepted");if(extension==="xlsx"){if(bytes[0]!==0x50||bytes[1]!==0x4b)throw new Error("The file is not a valid .xlsx workbook");const forbidden=["vbaProject.bin","xl/embeddings/","xl/externalLinks/","customUI/"].find(marker=>bytes.includes(Buffer.from(marker)));if(forbidden)throw new Error("Workbooks containing macros, embedded objects, external links, or custom executable UI are not accepted")}else if(bytes.includes(0))throw new Error("CSV files must contain plain UTF-8 text");let raw:unknown[][];
 if(extension==="csv")raw=csvRows(bytes.toString("utf8"));else{const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(bytes as never);if(workbook.worksheets.length!==1)throw new Error("Use a workbook with one inventory worksheet");raw=[];workbook.worksheets[0].eachRow({includeEmpty:false},row=>raw.push((row.values as unknown[]).slice(1)))}
 if(raw.length<2)throw new Error("The file needs a header row and at least one inventory row");if(raw.length-1>MAX_IMPORT_ROWS)throw new Error(`Import is limited to ${MAX_IMPORT_ROWS} rows`);const headers=raw[0].map(value=>String(value??"").trim()),mapped=headers.map(value=>aliases[cleanHeader(value)]);if(!mapped.includes("brand")||!mapped.includes("vitola"))throw new Error("Use columns named Brand/Manufacturer and Vitola/Size before importing");const existingKeys=new Set(existing.map(identity)),seen=new Set<string>();
 const rows=raw.slice(1).map((values,index):ImportPreviewRow=>{const errors:string[]=[],warnings:string[]=[],data:Record<string,unknown>={};try{values.forEach((value,column)=>{const field=mapped[column];if(!field)return;const safe=safeCell(value);if(safe===undefined)return;data[field]=numeric.has(field)?Number(safe):safe});if(!data.inventoryId)data.inventoryId=makeId(index+2);if(data.currentQty!==undefined&&!Number.isInteger(data.currentQty))errors.push("Quantity must be a whole number");const parsed=InventoryInputSchema.safeParse(data);if(!parsed.success){errors.push(...parsed.error.issues.map(issue=>`${issue.path.join(".")||"row"}: ${issue.message}`));return{row:index+2,errors,warnings,duplicate:false}}if(errors.length)return{row:index+2,errors,warnings,duplicate:false};const item=normalizeInventory(parsed.data),key=identity(item),duplicate=existingKeys.has(key)||seen.has(key);seen.add(key);if(duplicate)warnings.push("Possible duplicate already exists in this vault or file");if(item.currentQty===undefined)warnings.push("No quantity supplied; this lot will have an unknown quantity");return{row:index+2,item,errors,warnings,duplicate}}catch(error){errors.push(error instanceof Error?error.message:"Unsafe cell value");return{row:index+2,errors,warnings,duplicate:false}}});return{fileName,rows,valid:rows.filter(row=>row.item&&!row.errors.length).length,invalid:rows.filter(row=>row.errors.length).length,duplicates:rows.filter(row=>row.duplicate).length,columns:headers};
}
