import { canonicalCigarIdentity } from "./cigar-identity";
import { cigarTradition } from "./cigar-lineage";
import { exactMarketMovement } from "./market-movement";
import type { CigarCollection, InventoryItem, SmokingLog, Valuation } from "./types";

export type LeafFeedItem={id:string;kind:"Journal"|"Market"|"Cellar"|"Culture"|"Collection";priority:number;title:string;detail:string;href:string;label:string};
export function buildLeafFeed(input:{inventory:InventoryItem[];smokes:SmokingLog[];valuations:Valuation[];collections:CigarCollection[];communityPosts?:{id:string;title:string;category:string}[]}):LeafFeedItem[]{
  const items:LeafFeedItem[]=[];
  for(const smoke of [...input.smokes].sort((a,b)=>b.dateSmoked.localeCompare(a.dateSmoked)).slice(0,3)){const lot=input.inventory.find(value=>value.inventoryId===smoke.inventoryId);const title=lot?`${lot.brand} ${lot.line}`:smoke.cigarName||"Recorded cigar";items.push({id:`smoke-${smoke.smokeId}`,kind:"Journal",priority:82,title:`Revisit ${title}`,detail:`Your ${smoke.dateSmoked} experience can guide what to smoke, pair, or document next.`,href:lot?`/cigars/${canonicalCigarIdentity(lot).identityId}`:"/smoke-journal",label:"Open experience"})}
  const byIdentity=new Map<string,{lot:InventoryItem;valuations:Valuation[]}>();for(const lot of input.inventory){const key=canonicalCigarIdentity(lot).identityId;byIdentity.set(key,{lot,valuations:input.valuations.filter(value=>value.inventoryId===lot.inventoryId)})}
  for(const[key,value]of byIdentity){const movement=exactMarketMovement(value.valuations);if(movement.changePercent===undefined)continue;items.push({id:`market-${key}`,kind:"Market",priority:78,title:`${value.lot.brand} ${value.lot.line} market movement`,detail:`${movement.summary} ${movement.sourceCount} linked source${movement.sourceCount===1?"":"s"}; asking prices and completed sales remain separate.`,href:`/cigars/${key}`,label:"Inspect evidence"})}
  for(const collection of input.collections.filter(value=>value.status!=="Complete").slice(0,3))items.push({id:`collection-${collection.collectionId}`,kind:"Collection",priority:74,title:`Continue ${collection.name}`,detail:"Review exact components and evidence gaps without treating the unowned remainder as owned.",href:`/collections/${encodeURIComponent(collection.collectionId)}`,label:"Open collection"});
  for(const post of(input.communityPosts||[]).slice(0,3))items.push({id:`community-${post.id}`,kind:"Culture",priority:58,title:post.title,detail:`${post.category} · Collector experience, not official product fact.`,href:"/community?tab=board#recent-discussions",label:"Join the discussion"});
  const traditions=new Set(input.inventory.map(value=>cigarTradition(value.brand)));if(traditions.has("Habanos"))items.push({id:"learn-habanos",kind:"Culture",priority:52,title:"Protect the Habanos story",detail:"Review authenticity, edition chronology, packaging, and box-code evidence without overstating certainty.",href:"/learn/habanos-authenticity",label:"Open Habanos guide"});if(traditions.has("New World"))items.push({id:"learn-new-world",kind:"Culture",priority:51,title:"Follow the people behind New World cigars",detail:"Connect maker, blender, factory, blend generation, vitola, and release evidence.",href:"/learn/manufacturing-truth",label:"Open manufacturing truth"});
  return items.sort((a,b)=>b.priority-a.priority||a.title.localeCompare(b.title)).slice(0,18);
}
