export type ManufacturingRelationship =
  | "Vertically integrated"
  | "Company-owned factory"
  | "Partner-owned factory"
  | "Directed contract production"
  | "Mixed production";

export type ManufacturingTrustLevel = "Official" | "Verified Historical";
export type ManufacturingConfidence = "High" | "Medium";

export type ManufacturingTruthRecord = {
  id: string;
  brand: string;
  owner: string;
  blender: string;
  relationship: ManufacturingRelationship;
  factories: string[];
  factoryCountries: string[];
  tobaccoRegions: string[];
  examples: string[];
  truth: string;
  releaseRule: string;
  history: string;
  trustLevel: ManufacturingTrustLevel;
  confidence: ManufacturingConfidence;
  sourceName: string;
  sourceUrl: string;
  checkedAt: string;
};

export const manufacturingTruthRecords: ManufacturingTruthRecord[] = [
  {
    id: "my-father",
    brand: "My Father Cigars",
    owner: "García family",
    blender: "José “Pepín” García, Jaime García, and the García family blending team",
    relationship: "Vertically integrated",
    factories: ["My Father Cigars S.A.", "El Rey de los Habanos"],
    factoryCountries: ["Nicaragua", "United States"],
    tobaccoRegions: ["Estelí", "Jalapa", "Namanji"],
    examples: ["My Father", "Don Pepin García", "selected Miami production"],
    truth: "The García family owns its principal Nicaraguan production and its Miami factory. Farming, tobacco preparation, blending, and manufacturing are connected within the family organization.",
    releaseRule: "Confirm whether an individual cigar was made in Estelí or Miami; the family name alone does not identify the precise factory.",
    history: "The family opened El Rey de los Habanos in Miami in 2003 and later expanded into farming and large-scale production in Nicaragua.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "My Father official history",
    sourceUrl: "https://myfathercigars.com/about/",
    checkedAt: "2026-07-23",
  },
  {
    id: "arturo-fuente",
    brand: "Arturo Fuente",
    owner: "Fuente family",
    blender: "Carlos “Carlito” Fuente Jr. and the Fuente family tobacco team",
    relationship: "Vertically integrated",
    factories: ["Tabacalera A. Fuente y Cia."],
    factoryCountries: ["Dominican Republic"],
    tobaccoRegions: ["El Cibao", "Chateau de la Fuente"],
    examples: ["Don Carlos", "Hemingway", "Fuente Fuente OpusX"],
    truth: "Fuente cigars are produced by the family organization in the Dominican Republic. OpusX also documents the family’s long project to grow wrapper tobacco on its Dominican estate.",
    releaseRule: "Record the exact line and stated origin; family production does not mean every cigar uses the same farm, blend, or production specification.",
    history: "The company’s manufacturing story moved from Tampa to the Dominican Republic and developed into a multigenerational family system.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Arturo Fuente family history",
    sourceUrl: "https://arturofuente.com/history/family-history/",
    checkedAt: "2026-07-23",
  },
  {
    id: "perdomo",
    brand: "Perdomo Cigars",
    owner: "Perdomo family",
    blender: "Nick Perdomo Jr. and the Perdomo tobacco team",
    relationship: "Vertically integrated",
    factories: ["Tabacalera Perdomo"],
    factoryCountries: ["Nicaragua"],
    tobaccoRegions: ["Estelí", "Condega", "Jalapa"],
    examples: ["10th Anniversary", "20th Anniversary", "Lot 23"],
    truth: "Perdomo controls farming, curing, fermentation, aging, rolling, box production, and packaging through its Nicaraguan operation.",
    releaseRule: "The three growing regions and multiple wrapper treatments remain release facts; “made by Perdomo” is not a complete blend description.",
    history: "Nick Perdomo Jr. founded the company with his father and developed a vertically connected operation after opening the family’s Nicaraguan factory.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "The Perdomo Way",
    sourceUrl: "https://www.perdomocigars.com/the-perdomo-way",
    checkedAt: "2026-07-23",
  },
  {
    id: "espinosa",
    brand: "Espinosa Premium Cigars",
    owner: "Espinosa family",
    blender: "Erik Espinosa with Hector Alfonso Sr. and collaborating factory teams",
    relationship: "Mixed production",
    factories: ["La Zona", "Tabacalera A.J. Fernandez"],
    factoryCountries: ["Nicaragua"],
    tobaccoRegions: ["Estelí", "Jalapa", "Brazilian Mata Fina where disclosed"],
    examples: ["Espinosa Habano", "Laranja Reserva", "601", "Murcielago", "Knuckle Sandwich"],
    truth: "Espinosa owns La Zona, but not every Espinosa-owned brand is made there. The company also directs projects manufactured by A.J. Fernandez.",
    releaseRule: "Verify the factory by line and release. A La Zona association must never be applied automatically to the entire portfolio.",
    history: "Production relationships have moved over time; Cedriva preserves the maker attached to the relevant release period.",
    trustLevel: "Verified Historical",
    confidence: "High",
    sourceName: "Direct Erik Espinosa interview",
    sourceUrl: "https://www.cigaraficionado.com/article/a-conversation-with-erik-espinosa",
    checkedAt: "2026-07-23",
  },
  {
    id: "casa-carrillo",
    brand: "Casa Carrillo",
    owner: "Perez-Carrillo family",
    blender: "Ernesto Perez-Carrillo and the Casa Carrillo blending team",
    relationship: "Company-owned factory",
    factories: ["Casa Carrillo factory (formerly Tabacalera La Alianza)"],
    factoryCountries: ["Dominican Republic"],
    tobaccoRegions: ["Cibao Valley", "tobacco origins vary by release"],
    examples: ["La Historia", "Encore", "Pledge", "Essence"],
    truth: "Most Casa Carrillo cigars are made at the family factory in Santiago. Selected collaborations can use outside factories and must be credited separately.",
    releaseRule: "Treat the exact manufacturer and blend as release-level fields, especially for collaborations.",
    history: "Ernesto Perez-Carrillo’s manufacturing path connects El Crédito in Miami with the family’s later Dominican factory.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Casa Carrillo official company record",
    sourceUrl: "https://casacarrillocigars.com/wearecasacarrillo/",
    checkedAt: "2026-07-23",
  },
  {
    id: "la-flor-dominicana",
    brand: "La Flor Dominicana",
    owner: "Gomez family",
    blender: "Litto Gomez and the Gomez family tobacco team",
    relationship: "Vertically integrated",
    factories: ["La Flor Dominicana factory"],
    factoryCountries: ["Dominican Republic"],
    tobaccoRegions: ["La Canela", "Cibao Valley"],
    examples: ["LG", "Double Ligero", "Andalusian Bull", "Small Batch"],
    truth: "La Flor Dominicana produces its cigars in its own Dominican factory and grows important tobaccos on its La Canela farm.",
    releaseRule: "Estate involvement varies by cigar; identify which components are documented as farm-grown rather than implying every leaf is estate tobacco.",
    history: "Litto and Ines Gomez founded the company in 1994 and progressively expanded control over tobacco, production, and packaging.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "La Flor Dominicana factory",
    sourceUrl: "https://www.laflordominicana.com/our-factory",
    checkedAt: "2026-07-23",
  },
  {
    id: "aj-fernandez",
    brand: "A.J. Fernandez Cigars",
    owner: "Fernandez family",
    blender: "A.J. Fernandez and the Tabacalera A.J. Fernandez blending team",
    relationship: "Vertically integrated",
    factories: ["Tabacalera A.J. Fernandez"],
    factoryCountries: ["Nicaragua"],
    tobaccoRegions: ["Estelí", "Jalapa", "Condega"],
    examples: ["New World", "San Lotano", "Bellas Artes", "Enclave"],
    truth: "A.J. Fernandez’s own portfolio is produced within his Nicaraguan organization, which also manufactures many cigars owned by outside companies.",
    releaseRule: "When the factory makes a contract cigar, keep the outside brand owner and the actual manufacturer as separate credits.",
    history: "The organization has grown into a major tobacco and manufacturing partner; its factory role can be larger than the A.J. Fernandez name visible on shelves.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "A.J. Fernandez official record",
    sourceUrl: "https://www.ajfernandezcigars.com/",
    checkedAt: "2026-07-23",
  },
  {
    id: "drew-estate",
    brand: "Drew Estate",
    owner: "Swisher",
    blender: "Willy Herrera and Drew Estate’s blending and production teams",
    relationship: "Company-owned factory",
    factories: ["La Gran Fabrica Drew Estate"],
    factoryCountries: ["Nicaragua"],
    tobaccoRegions: ["Estelí", "Jalapa", "tobacco origins vary by line"],
    examples: ["Herrera Estelí", "Liga Privada", "Undercrown", "ACID"],
    truth: "Drew Estate’s core handmade portfolio is produced at La Gran Fabrica in Estelí. Brand ownership, creative authorship, and factory manufacture are related but distinct facts.",
    releaseRule: "Future production locations must be attached to the relevant cigar and date rather than retroactively applied to older releases.",
    history: "Drew Estate grew from a small New York venture into a large Nicaraguan factory and later became part of Swisher.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Drew Estate official story",
    sourceUrl: "https://drewestate.com/our-story/",
    checkedAt: "2026-07-23",
  },
  {
    id: "la-galera",
    brand: "La Galera",
    owner: "Blanco family",
    blender: "José “Jochy” Blanco and José Manuel Blanco",
    relationship: "Vertically integrated",
    factories: ["Tabacalera Palma"],
    factoryCountries: ["Dominican Republic"],
    tobaccoRegions: ["Cibao Valley", "Jacagua", "La Canela"],
    examples: ["La Galera Habano", "Connecticut", "Maduro", "Imperial Jade"],
    truth: "La Galera is made at the Blanco family’s Tabacalera Palma, an agricultural and manufacturing organization that also produces cigars for other clients.",
    releaseRule: "Do not transfer the La Galera brand credit to contract brands; name each outside brand owner and Tabacalera Palma separately.",
    history: "The family record spans multiple generations of Dominican growing, processing, manufacturing, and blending.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "La Galera official family history",
    sourceUrl: "https://www.lagaleracigars.com/about-us",
    checkedAt: "2026-07-23",
  },
  {
    id: "cle",
    brand: "C.L.E. Cigar Company",
    owner: "Christian Eiroa and partners",
    blender: "Christian Eiroa and collaborating C.L.E. tobacco teams",
    relationship: "Company-owned factory",
    factories: ["C.L.E. Cigar Factory", "Las Lomas"],
    factoryCountries: ["Honduras"],
    tobaccoRegions: ["Jamastrán Valley"],
    examples: ["C.L.E. Corojo", "Eiroa", "Asylum", "Aladino-related family work"],
    truth: "C.L.E. controls Honduran manufacturing, but the precise named facility can vary by line. Related Eiroa family brands should not be collapsed into one ownership record.",
    releaseRule: "Record the facility and owner disclosed for the specific cigar; shared family history does not make every Eiroa-associated brand the same company.",
    history: "Christian Eiroa’s work connects family farming and Camacho history with the company he formed in 2012.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "C.L.E. official tradition",
    sourceUrl: "https://clecigars.com/our-tradition/",
    checkedAt: "2026-07-23",
  },
  {
    id: "dunbarton",
    brand: "Dunbarton Tobacco & Trust",
    owner: "Steve and Cindy Saka",
    blender: "Steve Saka with dedicated partner-factory teams",
    relationship: "Directed contract production",
    factories: ["Joya de Nicaragua S.A.", "Nicaragua American Cigar S.A. (NACSA)"],
    factoryCountries: ["Nicaragua"],
    tobaccoRegions: ["Estelí", "Jalapa", "multiple disclosed and undisclosed leaf sources"],
    examples: ["Sobremesa", "Mi Querida", "Sin Compromiso", "StillWell Star"],
    truth: "Dunbarton owns and directs its brands but does not represent its partner factories as company-owned. Different marcas use different dedicated factory teams.",
    releaseRule: "Attach the actual partner factory to each marca and preserve collaborative tobacco contributions where they are documented.",
    history: "The company was founded in 2015 around direct blend control and long-term partner-factory relationships.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Dunbarton official manufacturing disclosure",
    sourceUrl: "https://www.dunbartoncigars.com/about/",
    checkedAt: "2026-07-23",
  },
  {
    id: "warped",
    brand: "Warped Cigars",
    owner: "Kyle Gellis",
    blender: "Kyle Gellis with partner-factory tobacco teams",
    relationship: "Directed contract production",
    factories: ["El Titan de Bronze", "TABSA / Aganorsa Leaf"],
    factoryCountries: ["United States", "Nicaragua"],
    tobaccoRegions: ["Estelí", "Jalapa", "Condega"],
    examples: ["La Colmena", "Don Reynaldo", "Maestro del Tiempo", "The Devil’s Hands"],
    truth: "Warped is a brand and blending direction expressed through multiple disclosed manufacturing partners, including a small Miami factory and Aganorsa’s Nicaraguan production.",
    releaseRule: "Factory credit belongs to the line. Never describe the whole portfolio as Miami-made or Aganorsa-made.",
    history: "The portfolio’s manufacturing relationships are part of its creative record, not background logistics.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Warped official portfolio",
    sourceUrl: "https://www.warpedcigars.com/story",
    checkedAt: "2026-07-23",
  },
  {
    id: "roma-craft",
    brand: "RoMa Craft Tobac",
    owner: "RoMa Craft partners",
    blender: "Skip Martin and Esteban Disla",
    relationship: "Partner-owned factory",
    factories: ["Fábrica de Tabacos Nica Sueño"],
    factoryCountries: ["Nicaragua"],
    tobaccoRegions: ["Estelí", "tobacco origins vary by blend"],
    examples: ["CroMagnon", "Neanderthal", "Intemperance"],
    truth: "RoMa Craft’s brands are produced at Nica Sueño, the Estelí factory co-owned by company partner Skip Martin and master cigar maker Esteban Disla.",
    releaseRule: "Credit both product direction and factory authorship; small scale does not make production a single-person act.",
    history: "The company developed around intentionally limited, hands-on production and direct factory participation.",
    trustLevel: "Verified Historical",
    confidence: "High",
    sourceName: "Nica Sueño factory record",
    sourceUrl: "https://cigarwars.net/factories/fabrica-de-tabacos-nica-sueno-sa",
    checkedAt: "2026-07-23",
  },
  {
    id: "ferio-tego",
    brand: "Ferio Tego",
    owner: "Michael Herklots and Brendon Scott",
    blender: "Michael Herklots with collaborating partner-factory teams",
    relationship: "Directed contract production",
    factories: ["Plasencia", "Quesada Cigars", "Agroindustrias Diadema"],
    factoryCountries: ["Nicaragua", "Dominican Republic", "Honduras"],
    tobaccoRegions: ["Origins vary by collection"],
    examples: ["Elegancia", "Generoso", "Metropolitan", "Timeless"],
    truth: "Ferio Tego directs a portfolio made through disclosed manufacturing partners in three countries and also stewards blends preserved from the Nat Sherman era.",
    releaseRule: "Every collection requires its own factory and blend record; “Ferio Tego” identifies the owner, not one manufacturing site.",
    history: "The company formed after Nat Sherman’s closure and preserved selected existing blends while developing new projects.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Ferio Tego official team and partner record",
    sourceUrl: "https://www.feriotego.com/our-team",
    checkedAt: "2026-07-23",
  },
  {
    id: "manufactura-rivas",
    brand: "Manufactura Rivas and contract projects",
    owner: "Francisco “Chico” Rivas",
    blender: "Francisco “Chico” Rivas with client brand and factory teams",
    relationship: "Company-owned factory",
    factories: ["Manufactura Rivas / “Top Secret Nest”"],
    factoryCountries: ["Dominican Republic"],
    tobaccoRegions: ["Dominican Republic", "origins vary by project"],
    examples: ["Caminos", "Dos Jotas", "SP1014", "selected Caldwell and Lost & Found projects"],
    truth: "Rivas is both a blender and independent manufacturer whose factory produces proprietary and outside-brand projects. The better-known name on a band may not be the factory that made it.",
    releaseRule: "Verify every client project individually. Published records use more than one factory name, and a relationship documented for one project must not be generalized.",
    history: "Rivas’s career includes prior work at Quesada and decades of Dominican blending and manufacturing.",
    trustLevel: "Verified Historical",
    confidence: "Medium",
    sourceName: "Caminos manufacturer and Rivas biography",
    sourceUrl: "https://www.neptunecigar.com/caminos-cigar",
    checkedAt: "2026-07-23",
  },
  {
    id: "plasencia",
    brand: "Plasencia Cigars",
    owner: "Plasencia family",
    blender: "Néstor Andrés Plasencia and the Plasencia family tobacco team",
    relationship: "Vertically integrated",
    factories: ["Plasencia Cigars S.A.", "Plasencia factories in Nicaragua and Honduras"],
    factoryCountries: ["Nicaragua", "Honduras"],
    tobaccoRegions: ["Estelí", "Jalapa", "Condega", "Olancho", "Jamastrán"],
    examples: ["Alma series", "Reserva Original", "Cosecha series", "outside contract brands"],
    truth: "The Plasencia family grows, processes, and manufactures tobacco at substantial scale for its own portfolio and for outside brand owners.",
    releaseRule: "Identify the exact factory and country for each cigar. A Plasencia manufacturing credit does not prove a cigar is a Plasencia-owned brand or a Nicaraguan puro.",
    history: "The family record spans five generations, migration from Cuba, agricultural operations in Nicaragua and Honduras, and a namesake portfolio launched after decades of contract production.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Plasencia official heritage",
    sourceUrl: "https://www.plasenciacigars.com/heritage/",
    checkedAt: "2026-07-23",
  },
  {
    id: "foundation",
    brand: "Foundation Cigar Company",
    owner: "Nicholas Melillo",
    blender: "Nicholas Melillo with collaborating growers and factory teams",
    relationship: "Directed contract production",
    factories: ["Tabacalera A.J. Fernandez", "My Father Cigars S.A."],
    factoryCountries: ["Nicaragua"],
    tobaccoRegions: ["Estelí", "Jalapa", "Condega", "Connecticut River Valley where disclosed"],
    examples: ["El Güegüense", "The Tabernacle", "Olmec", "The Wise Man Corojo and Maduro"],
    truth: "Foundation owns and directs its brands through partner factories. Manufacturing is disclosed by line and can change when a project is redesigned.",
    releaseRule: "Confirm the manufacturer for the specific release. Current Wise Man production must not be retroactively assigned to earlier versions or the entire Foundation portfolio.",
    history: "Melillo founded Foundation in 2015 after years working in tobacco and Nicaraguan production; the company’s record combines Connecticut heritage, Nicaraguan leaf, and partner-factory manufacture.",
    trustLevel: "Verified Historical",
    confidence: "High",
    sourceName: "Foundation official biography and documented factory record",
    sourceUrl: "https://foundationcigarcompany.com/about-foundation/",
    checkedAt: "2026-07-23",
  },
  {
    id: "tatuaje",
    brand: "Tatuaje",
    owner: "Pete Johnson",
    blender: "Pete Johnson with José “Pepín” García and García-family tobacco teams",
    relationship: "Directed contract production",
    factories: ["My Father Cigars S.A.", "El Rey de los Habanos"],
    factoryCountries: ["Nicaragua", "United States"],
    tobaccoRegions: ["Estelí", "Jalapa", "tobacco origins vary by line"],
    examples: ["Tatuaje Brown Label", "Cabaiguan", "Monster Series"],
    truth: "Tatuaje’s authorship is a long-running partnership between Johnson’s product direction and the García family’s blending, tobacco, and manufacturing system.",
    releaseRule: "Check the exact line, vitola, and period before assigning Estelí or Miami production.",
    history: "The brand began through Johnson’s early collaboration with Pepín García and has preserved factory differences across its portfolio.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Tatuaje official manufacturer disclosure",
    sourceUrl: "https://tatuajecigars.com/cabaiguan.html",
    checkedAt: "2026-07-23",
  },
  {
    id: "illusione",
    brand: "Illusione",
    owner: "Dion Giolito",
    blender: "Dion Giolito with partner-factory tobacco teams",
    relationship: "Mixed production",
    factories: ["TABSA / Aganorsa Leaf", "Raíces Cubanas", "selected A.J. Fernandez production"],
    factoryCountries: ["Nicaragua", "Honduras"],
    tobaccoRegions: ["Estelí", "Jalapa", "Condega", "origins vary by line"],
    examples: ["Original Documents", "Epernay", "Singulare", "Allegria"],
    truth: "Illusione owns and directs its portfolio through several manufacturing relationships. The factory and sometimes the country vary by line and production era.",
    releaseRule: "Treat every factory assignment as line- and date-specific; do not infer the manufacturer from Illusione’s Nicaraguan identity alone.",
    history: "The portfolio has long associations with Aganorsa/TABSA and Raíces Cubanas, with later projects adding other production relationships.",
    trustLevel: "Verified Historical",
    confidence: "Medium",
    sourceName: "Documented Illusione factory relationships",
    sourceUrl: "https://www.cigaraficionado.com/article/master-of-illusione-18865",
    checkedAt: "2026-07-23",
  },
  {
    id: "ovejanegracigars",
    brand: "Black Label Trading Co. and Black Works Studio",
    owner: "James and Angela Brown",
    blender: "James Brown with the Fábrica Oveja Negra tobacco and production team",
    relationship: "Company-owned factory",
    factories: ["Fábrica Oveja Negra"],
    factoryCountries: ["Nicaragua"],
    tobaccoRegions: ["Estelí", "tobacco origins vary by project"],
    examples: ["Black Label Trading Co.", "Black Works Studio", "Killer Bee"],
    truth: "The Browns operate the Estelí factory that produces their brands, connecting product direction and small-batch manufacturing within one organization.",
    releaseRule: "Outside projects made by Oveja Negra still require separate brand-owner credit; a shared factory does not make them Black Label products.",
    history: "The factory was opened to give the founders direct control over experimentation, tobacco preparation, construction, and release scale.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Fábrica Oveja Negra official record",
    sourceUrl: "https://ovejanegracigars.com/pages/factory",
    checkedAt: "2026-07-23",
  },
  {
    id: "crowned-heads",
    brand: "Crowned Heads",
    owner: "Crowned Heads",
    blender: "Jon Huber and Crowned Heads with collaborating factory blenders and tobacco teams",
    relationship: "Mixed production",
    factories: ["Casa Carrillo", "My Father Cigars S.A.", "Tabacalera Pichardo", "La Gran Fabrica Drew Estate", "NACSA"],
    factoryCountries: ["Dominican Republic", "Nicaragua"],
    tobaccoRegions: ["Origins vary by project"],
    examples: ["Four Kicks", "J.D. Howard Reserve", "Mil Días", "Juárez"],
    truth: "Crowned Heads develops concepts and blend direction through multiple manufacturing partners. The factory relationship is central to each project’s authorship.",
    releaseRule: "Record the partner factory for every line and release; “Crowned Heads” identifies the brand owner, not a single production site.",
    history: "Four Kicks established the company’s collaborative model with Ernesto Perez-Carrillo and the factory then known as Tabacalera La Alianza.",
    trustLevel: "Official",
    confidence: "High",
    sourceName: "Crowned Heads official Four Kicks record",
    sourceUrl: "https://www.crownedheads.com/the-story-behind-four-kicks/",
    checkedAt: "2026-07-23",
  },
];

export const manufacturingFactories = [
  { name: "My Father Cigars S.A.", country: "Nicaragua", brands: ["My Father", "Tatuaje", "selected Foundation work"], record: "my-father" },
  { name: "Tabacalera A. Fuente y Cia.", country: "Dominican Republic", brands: ["Arturo Fuente"], record: "arturo-fuente" },
  { name: "Tabacalera Perdomo", country: "Nicaragua", brands: ["Perdomo"], record: "perdomo" },
  { name: "La Zona", country: "Nicaragua", brands: ["Espinosa core lines", "outside projects"], record: "espinosa" },
  { name: "Tabacalera A.J. Fernandez", country: "Nicaragua", brands: ["A.J. Fernandez", "Espinosa projects", "outside contract brands"], record: "aj-fernandez" },
  { name: "Casa Carrillo", country: "Dominican Republic", brands: ["Casa Carrillo", "Crowned Heads projects"], record: "casa-carrillo" },
  { name: "La Gran Fabrica Drew Estate", country: "Nicaragua", brands: ["Drew Estate", "outside collaborations"], record: "drew-estate" },
  { name: "Tabacalera Palma", country: "Dominican Republic", brands: ["La Galera", "outside contract brands"], record: "la-galera" },
  { name: "Joya de Nicaragua S.A.", country: "Nicaragua", brands: ["Joya de Nicaragua", "Dunbarton projects"], record: "dunbarton" },
  { name: "El Titan de Bronze", country: "United States", brands: ["Warped lines", "selected boutique projects"], record: "warped" },
  { name: "Fábrica de Tabacos Nica Sueño", country: "Nicaragua", brands: ["RoMa Craft Tobac"], record: "roma-craft" },
  { name: "Manufactura Rivas", country: "Dominican Republic", brands: ["Caminos", "Dos Jotas", "outside contract projects"], record: "manufactura-rivas" },
  { name: "Plasencia factories", country: "Nicaragua and Honduras", brands: ["Plasencia", "outside contract brands"], record: "plasencia" },
  { name: "Fábrica Oveja Negra", country: "Nicaragua", brands: ["Black Label Trading Co.", "Black Works Studio", "outside projects"], record: "ovejanegracigars" },
  { name: "TABSA / Aganorsa Leaf", country: "Nicaragua", brands: ["Aganorsa portfolio", "Warped lines", "Illusione lines", "outside contract brands"], record: "illusione" },
] as const;

export const manufacturingRegions = [
  ["Estelí, Nicaragua", "A major center for factories, tobacco processing, and dark, structured Nicaraguan tobacco. A city or region is context—not a flavor guarantee."],
  ["Jalapa, Nicaragua", "A northern valley associated with aromatic, often sweeter tobacco and valued wrapper. Farm, seed, priming, and crop still control the actual character."],
  ["Condega, Nicaragua", "A cooler Nicaraguan growing region often associated with thinner, aromatic leaf and useful combustion. General tendencies never replace a lot record."],
  ["Cibao Valley, Dominican Republic", "A broad agricultural region containing distinct farms and microclimates. Dominican origin alone cannot identify seed, processing, or sensory character."],
  ["Jamastrán Valley, Honduras", "An important Honduran tobacco region closely associated with the Eiroa family and Corojo history. Modern seed and hybrid details require release evidence."],
  ["Connecticut River Valley, United States", "Historic home of Connecticut Shade and Broadleaf traditions. Cultivation method, seed, priming, and fermentation create very different tobaccos within the same valley."],
] as const;

const houseRecordMap: [string, string][] = [
  ["My Father", "my-father"],
  ["Arturo Fuente", "arturo-fuente"],
  ["Perdomo", "perdomo"],
  ["Espinosa", "espinosa"],
  ["Casa Carrillo", "casa-carrillo"],
  ["La Flor Dominicana", "la-flor-dominicana"],
  ["A.J. Fernandez", "aj-fernandez"],
  ["Drew Estate", "drew-estate"],
  ["La Galera", "la-galera"],
  ["C.L.E.", "cle"],
  ["Dunbarton", "dunbarton"],
  ["Warped", "warped"],
  ["RoMa Craft", "roma-craft"],
  ["Ferio Tego", "ferio-tego"],
  ["Manufactura Rivas", "manufactura-rivas"],
  ["Plasencia", "plasencia"],
  ["Foundation", "foundation"],
  ["Tatuaje", "tatuaje"],
  ["Illusione", "illusione"],
  ["Black Label", "ovejanegracigars"],
  ["Black Works", "ovejanegracigars"],
  ["Crowned Heads", "crowned-heads"],
];

export function manufacturingTruthHrefForHouse(house: string) {
  const match = houseRecordMap.find(([name]) => house.includes(name));
  return match ? `/learn/manufacturing-truth#${match[1]}` : "/learn/manufacturing-truth";
}
