export type InventoryItem = {
  inventoryId: string;
  catalogId?: string;
  brand: string;
  line: string;
  vitola: string;
  vintage?: string | number;
  originalQty?: number;
  smokedQty?: number;
  currentQty?: number;
  fullBoxQty?: number;
  sticksPerBox?: number;
  looseStickQty?: number;
  knownBoxSizes?: string;
  boxFormatSourceUrl?: string;
  retailValue?: number;
  actualCost?: number;
  collectionId?: string;
  packaging?: string;
  boxCode?: string;
  habanosSealPhotoLink?: string;
  habanosVerified?: boolean;
  storageLocationId?: string;
  status?: string;
  priority?: string;
  score?: number;
  action?: string;
  photoLink?: string;
  boxPhotoLink?: string;
  boxCodePhotoLink?: string;
  provenanceDocumentLink?: string;
  provenanceNotes?: string;
  notes?: string;
};

export type InventoryInput = Omit<InventoryItem, "currentQty"> & { currentQty?: number };

export type SmokingLog = { smokeId: string; inventoryId: string; cigarName?: string; dateSmoked: string; vintage?: string | number; overall?: number; flavor?: string; strength?: string; sweetness?: string; construction?: string; tastingNotes?: string; buyAgain?: boolean };
export type Valuation = { valuationId: string; inventoryId: string; valuationDate: string; replacementValue?: number; marketValue?: number; lastSaleValue?: number; lastSaleDate?: string; lastSaleVenue?: string; lastSaleSourceUrl?: string; source?: string; sourceUrl?: string; confidence?: string; notes?: string };
export type ProfessionalRating = { ratingId:string; inventoryId:string; publication:string; score:number; reviewDate?:string; reviewer?:string; sourceUrl:string; matchConfidence:"High"|"Medium"|"Low"; matchedVintage?:string|number; summary?:string; createdAt:string };
export type ActivityType = "Purchase" | "Add sticks" | "Add box" | "Open box" | "Smoke" | "Gift" | "Sale" | "Damaged / discarded" | "Correction" | "Storage move";
export type InventoryActivity = { activityId: string; inventoryId: string; eventDate: string; eventType: ActivityType; quantityChange?: number; boxesChange?: number; looseSticksChange?: number; totalAmount?: number; fromStorage?: string; toStorage?: string; resultingQuantity?: number; resultingFullBoxes?: number; resultingLooseSticks?: number; notes?: string; createdAt?: string };
export type CigarCollection = { collectionId:string; name:string; maker?:string; releaseYear?:string|number; edition?:string; expectedComponents?:number; expectedCigars?:number; wholeMarketValue?:number; acquisitionCost?:number; valuationDate?:string; valuationSource?:string; valuationSourceUrl?:string; status?:"Complete"|"Incomplete"|"Opened"; photoLink?:string; notes?:string };
export type Humidor={humidorId:string;name:string;type?:string;capacity?:number;location?:string;targetTempF:number;minTempF:number;maxTempF:number;targetHumidity:number;minHumidity:number;maxHumidity:number;humidificationDevice?:string;sensorName?:string;photoLink?:string;notes?:string};
export type HumidorReading={readingId:string;humidorId:string;sensorId?:string;provider?:string;externalReadingId?:string;recordedAt:string;temperatureF:number;humidity:number;batteryPercent?:number;source?:string;notes?:string;importedAt?:string};
export type EnvironmentalSensor={sensorId:string;humidorId:string;provider:string;model?:string;name:string;externalDeviceId?:string;syncMethod:"CSV import"|"Cloud API"|"Webhook"|"Mobile bridge"|"Manual";connectionStatus:"Ready"|"Connected"|"Needs setup"|"Stale"|"Error";lastSyncAt?:string;batteryPercent?:number;firmware?:string;notes?:string};
export type AlertDelivery={alertId:string;humidorId:string;sensorId?:string;severity:"Attention"|"Critical"|"Offline";alertType:string;message:string;readingId?:string;detectedAt:string;emailSentAt?:string;smsSentAt?:string;status:"Sent"|"Partial"|"Pending"|"Failed";notes?:string};
export type CatalogCigar = { catalogId: string; brand: string; line: string; vitola: string; country?: string; sourceUrl?: string; researchStatus?: string };
export type AvailabilityListing={seller:string;sellerType:"Authorized retailer"|"Specialty dealer"|"Auction"|"Manufacturer"|"Other";title:string;url:string;availability:"In stock"|"Auction open"|"Waitlist"|"Unknown";askingPrice?:number;quantity?:number;unitPrice?:number;listingDate?:string;condition?:string;notes:string};
export type PriceMatch={url:string;seller:string;price:number;targetPrice:number;basis:"Per cigar";availability:"In stock"|"Auction open"};
export type WishlistItem = { wishlistId:string; brand:string; line:string; vitola:string; collectionId?:string; collectionName?:string; priority:"High"|"Medium"|"Standard"; targetPrice?:number; sourceUrl?:string; status:"Watching"|"Purchased"|"Added to vault"|"Passed"; notes?:string; createdAt:string; purchasedAt?:string; inventoryId?:string; availabilityLastCheckedAt?:string; availabilityListings?:AvailabilityListing[]; priceMatches?:PriceMatch[]; priceAlertedUrls?:string[]; acknowledgedNotificationIds?:string[] };
