import type { Metadata } from "next";
import { publicPageMetadata } from "@/lib/seo";
import "../evidence-guides.css";

export const metadata:Metadata=publicPageMetadata("Cigar Authentication & Evidence","Evaluate cigar identity, packaging, provenance, codes, condition, and uncertainty without relying on one shortcut.","/learn/habanos-authenticity");
const HABANOS_CHECKER="https://www.habanos.com/en/authenticity-check/?lang=en";
const evidence=[
  ["Exact cigar identity","Confirm brand, line, named vitola, physical dimensions, edition, and market. Family-name similarity is not an exact match."],
  ["Packaging","Compare the box style, count, bands, seals, inserts, hardware, printing, and known changes for the claimed release period."],
  ["Codes and official tools","Use an official checker when one exists. A valid code is useful evidence, but it should be considered with the complete item."],
  ["Provenance","Preserve seller, receipt, auction record, photographs, ownership history, and any expert inspection. A story without documentation remains a claim."],
  ["Condition and consistency","Look for details that agree with one another. A single unusual feature may reflect a documented revision; several conflicts require caution."],
] as const;
export default function AuthenticityGuidePage(){return <main className="shell evidenceGuide"><section className="evidenceGuideHero"><div><div className="eyebrow">Hojavía Learn · Protection</div><h1>Authentication is a body of evidence—not one photograph or code.</h1><p className="lede">Strong authentication connects the exact cigar, its packaging, its documented history, and the evidence available for the claimed time and market.</p></div><aside><strong>Be transparent</strong><p>“Not yet verified” protects trust. It is not the same as “counterfeit.”</p></aside></section><section className="evidenceGuideCards">{evidence.map(([title,body],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h2>{title}</h2><p>{body}</p></article>)}</section><section className="evidenceGuideDecision"><div><div className="eyebrow">A careful review</div><h2>Ask what each item proves—and what it cannot prove.</h2></div><ol><li>Begin with the exact claimed cigar and release.</li><li>Photograph the complete box, codes, seals, bands, contents, and any receipt.</li><li>Check official tools and dated reference material.</li><li>Keep conflicting details visible instead of forcing a conclusion.</li><li>Use an experienced specialist for high-value or disputed items.</li></ol><p className="evidenceGuideNote">Hojavía does not authenticate a cigar merely because a user entered a code or uploaded a photograph. Official tools, collector records, and expert conclusions remain clearly identified.</p><div className="ctaRow"><a className="button" href={HABANOS_CHECKER} target="_blank" rel="noreferrer">Open the official Habanos checker ↗</a><a className="button secondary" href="/trust">Understand evidence labels</a></div></section></main>}
