import { loadValuations } from "@/lib/data";
import { loadInventory } from "@/lib/inventory";
import { buildPortfolioHistory } from "@/lib/portfolio-history";
import "./value-history.css";

export const dynamic = "force-dynamic";
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const unitMoney = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 });

export default async function ValueHistoryPage() {
  const [inventory, valuations] = await Promise.all([loadInventory(), loadValuations()]);
  const history = buildPortfolioHistory(inventory, valuations);
  const max = Math.max(...history.snapshots.map(point => point.value), 1);
  const changePercent = history.totals.acquisitionCost ? history.totals.unrealizedChange / history.totals.acquisitionCost * 100 : undefined;
  return <main className="shell wideShell historyPage">
    <section className="historyHero"><div><div className="eyebrow">Portfolio intelligence</div><h1>See how the vault is growing.</h1><p className="lede">Track documented collection value, compare it with acquisition cost, and focus new research on the lots that materially move the portfolio.</p></div><div className="historyValue"><span>Current tracked value</span><strong>{money.format(history.totals.currentValue)}</strong><small>{history.totals.coverage}% of inventory lots have valuation records</small></div></section>
    <section className="historyMetrics"><article><span>Acquisition cost</span><strong>{money.format(history.totals.acquisitionCost)}</strong><small>Recorded purchase cost</small></article><article className={history.totals.unrealizedChange >= 0 ? "positive" : "negative"}><span>Value over cost</span><strong>{history.totals.unrealizedChange >= 0 ? "+" : ""}{money.format(history.totals.unrealizedChange)}</strong><small>{changePercent === undefined ? "Add purchase costs for a return estimate" : `${changePercent >= 0 ? "+" : ""}${changePercent.toFixed(1)}% estimated`}</small></article><article><span>Valuation dates</span><strong>{history.snapshots.length}</strong><small>Historical evidence points</small></article><article><span>Measured movers</span><strong>{history.movers.length}</strong><small>Lots with two or more valuations</small></article></section>
    <section className="historyGrid"><article className="card historyChart"><div className="sectionHead"><div><div className="eyebrow">Value timeline</div><h2>Documented portfolio history</h2></div><a className="textLink" href="/records">Add evidence →</a></div>{history.snapshots.length ? <div className="chartArea">{history.snapshots.map(point => <div className="chartPoint" key={point.date}><span style={{ height: `${Math.max(4, point.value / max * 100)}%` }} title={`${point.date}: ${money.format(point.value)}`}/><small>{point.date}</small><b>{money.format(point.value)}</b></div>)}</div> : <div className="emptyState">Add valuation records to begin the portfolio timeline.</div>}<p className="historyCaution">Historical totals use today’s owned quantities with the valuation evidence available on each date. Quantity-history reconstruction is the next accounting layer.</p></article><aside className="card allocationCard"><div className="eyebrow">Concentration</div><h2>Value by brand</h2><div className="allocationList">{history.brandAllocation.slice(0,8).map(row => <div key={row.brand}><span><strong>{row.brand}</strong><small>{money.format(row.value)}</small></span><i><b style={{width:`${row.percent}%`}}/></i><em>{row.percent}%</em></div>)}</div></aside></section>
    <section className="section"><div className="sectionHead"><div><div className="eyebrow">Market movement</div><h2>Biggest documented movers</h2></div><a className="textLink" href="/valuations">Valuation workspace →</a></div><div className="moverList">{history.movers.slice(0,12).map(row => <a href={`/inventory/${row.item.inventoryId}`} key={row.item.inventoryId}><div><strong>{row.item.brand} {row.item.line}</strong><small>{row.item.vitola} · {row.item.currentQty ?? 0} cigars</small></div><span><small>{unitMoney.format(row.previousValue)} → {unitMoney.format(row.latestValue)}</small><strong className={row.change >= 0 ? "gain" : "loss"}>{row.change >= 0 ? "+" : ""}{row.changePercent}%</strong></span><b className={row.lotChange >= 0 ? "gain" : "loss"}>{row.lotChange >= 0 ? "+" : ""}{money.format(row.lotChange)}</b></a>)}{!history.movers.length && <div className="emptyState">Two valuation records for the same inventory lot are required to calculate movement.</div>}</div></section>
  </main>;
}
