import assert from "node:assert/strict";
import test from "node:test";
import { buildCigarTimeline,buildCollectionIntelligence,buildCollectorDNA,estimateAging } from "../lib/collection-intelligence";
import type { InventoryItem,ProfessionalRating,SmokingLog,Valuation } from "../lib/types";

const item:InventoryItem={inventoryId:"I1",brand:"Arturo Fuente",line:"OpusX",vitola:"Petite Lancero",vintage:2016,currentQty:10,retailValue:75,storageLocationId:"H1",priority:"High",photoLink:"https://example.com/photo.jpg",provenanceNotes:"Original box"};
test("aging intelligence exposes its general heuristic",()=>{const result=estimateAging(item,new Date("2026-07-22"));assert.equal(result.age,10);assert.equal(result.phase,"Mature");assert.equal(result.peakWindow,"2024–2031");assert.match(result.basis,/heuristic/)});
test("undated cigars do not receive invented maturity",()=>{const result=estimateAging({...item,vintage:undefined});assert.equal(result.maturityPercent,undefined);assert.equal(result.phase,"Undated")});
test("Collector DNA learns only from tasting evidence",()=>{const smokes:SmokingLog[]=[{smokeId:"S1",inventoryId:"I1",dateSmoked:"2026-01-01",overall:95,buyAgain:true,strength:"Medium-full",tastingNotes:"Cream, leather and cedar"}];const dna=buildCollectorDNA([item],smokes,new Date("2026-07-22"));assert.deepEqual(dna.topBrands,["Arturo Fuente"]);assert.equal(dna.preferredStrength,"Medium-full");assert.deepEqual(dna.flavorSignals,["leather","cream","cedar"])});
test("collection score combines eight transparent dimensions",()=>{const valuation:Valuation={valuationId:"V1",inventoryId:"I1",valuationDate:"2026-01-01",marketValue:80};const result=buildCollectionIntelligence({inventory:[item],valuations:[valuation],humidors:[],readings:[],smokes:[]},new Date("2026-07-22"));assert.equal(result.components.length,8);assert.ok(result.score>=0&&result.score<=100);assert.equal(result.advisor.smokeNow[0].inventoryId,"I1")});
test("cigar timeline combines activity, tasting, value, and published scores",()=>{const rating:ProfessionalRating={ratingId:"R1",inventoryId:"I1",publication:"Cigar Journal",score:94,sourceUrl:"https://example.com/review",matchConfidence:"High",createdAt:"2026-02-01T00:00:00Z"};const timeline=buildCigarTimeline(item,[{activityId:"A1",inventoryId:"I1",eventDate:"2025-01-01",eventType:"Purchase",resultingQuantity:10}],[{smokeId:"S1",inventoryId:"I1",dateSmoked:"2026-03-01",overall:95}],[{valuationId:"V1",inventoryId:"I1",valuationDate:"2026-02-15",marketValue:80}],[rating]);assert.equal(timeline.length,4);assert.equal(timeline[0].type,"Smoked / rated");assert.equal(timeline.at(-1)?.type,"Acquired / adjusted")});
