import assert from "node:assert/strict";
import test from "node:test";
import { inValuationBatches,reusableValuation,valuationBatchSize,valuationBudgetStatus,valuationMonitorPriority,valuationNeedsMonitoring,valuationRefreshDays } from "../lib/valuation-monitor";
import type { InventoryItem,Valuation } from "../lib/types";

const item:InventoryItem={inventoryId:"I1",brand:"Cohiba",line:"Siglo IV",vitola:"Marevas",currentQty:20,retailValue:50,priority:"High"};
const valuation=(date:string,overrides:Partial<Valuation>={}):Valuation=>({valuationId:`V-${date}`,inventoryId:"I1",valuationDate:date,marketValue:60,source:"Retailer",sourceUrl:"https://example.com/cigar",confidence:"High",...overrides});

test("rare and Cuban cigars refresh at 60 days",()=>{assert.equal(valuationRefreshDays(item),60);assert.equal(valuationNeedsMonitoring(item,[valuation("2026-05-22")],new Date("2026-07-21")),true);assert.equal(valuationNeedsMonitoring(item,[valuation("2026-05-23")],new Date("2026-07-21")),false)});
test("regular production cigars refresh at 120 days",()=>{const regular={...item,brand:"Foundation",line:"Olmec",priority:"Normal" as const};assert.equal(valuationRefreshDays(regular),120);assert.equal(valuationNeedsMonitoring(regular,[valuation("2026-03-23")],new Date("2026-07-21")),true);assert.equal(valuationNeedsMonitoring(regular,[valuation("2026-03-24")],new Date("2026-07-21")),false)});
test("unsupported research waits 180 days",()=>{const unsupported=valuation("2026-01-22",{marketValue:undefined,replacementValue:undefined,notes:"Insufficient evidence"});assert.equal(valuationRefreshDays(item,unsupported),180);assert.equal(valuationNeedsMonitoring(item,[unsupported],new Date("2026-07-21")),true)});
test("empty or incomplete lots are skipped",()=>{assert.equal(valuationNeedsMonitoring({...item,currentQty:0},[]),false);assert.equal(valuationNeedsMonitoring({...item,vitola:"Unknown"},[]),false)});
test("current source-linked retail evidence is reusable for every exact matching user",()=>{const other={...item,inventoryId:"I1",packaging:"Box of 20"};const reused=reusableValuation({...item,packaging:"Single"},[{item:other,valuation:valuation("2026-07-01",{replacementValue:50})}],new Date("2026-07-21"));assert.equal(reused?.replacementValue,50);assert.equal(reusableValuation(item,[{item:other,valuation:valuation("2026-07-01",{replacementValue:50,sourceUrl:undefined,confidence:"Low"})}],new Date("2026-07-21")),undefined);assert.equal(reusableValuation(item,[{item:{...other,vitola:"Robusto"},valuation:valuation("2026-07-01",{replacementValue:50})}],new Date("2026-07-21")),undefined);assert.equal(reusableValuation(item,[{item:{...other,vintage:2024},valuation:valuation("2026-07-01",{replacementValue:50})}],new Date("2026-07-21")),undefined)});
test("high-value priority includes lot value and collector priority",()=>assert.equal(valuationMonitorPriority(item),11000));
test("valuation batches default to three and stay within safe limits",()=>{assert.equal(valuationBatchSize(),3);assert.equal(valuationBatchSize("50"),6);assert.equal(valuationBatchSize("0"),1);assert.equal(valuationBatchSize("invalid"),3)});
test("monthly estimated budget pauses before exceeding 80 percent",()=>{const events=[{created_at:"2026-07-01T00:00:00.000Z",properties:{estimatedCostUsd:6}},{created_at:"2026-06-01T00:00:00.000Z",properties:{estimatedCostUsd:99}},{created_at:"2026-07-02T00:00:00.000Z",properties:{estimatedCostUsd:4,cached:true}}];const status=valuationBudgetStatus(events,new Date("2026-07-21"),10,2.01);assert.equal(status.estimatedSpend,6);assert.equal(status.pauseAt,8);assert.equal(status.paused,true);assert.equal(status.remainingBeforePause,2)});
test("valuation work runs in bounded batches without losing order",async()=>{let active=0,peak=0;const results=await inValuationBatches([1,2,3,4,5],async value=>{active++;peak=Math.max(peak,active);await Promise.resolve();active--;return value*2},2);assert.deepEqual(results,[2,4,6,8,10]);assert.equal(peak,2)});
