import type { Metadata } from "next";
import { loadPublicIndustry } from "@/lib/industry-public";
import { loadInventory } from "@/lib/inventory";
import { loadCatalog } from "@/lib/catalog";
import { buildCanonicalCigarRecord, canonicalCatalogHref } from "@/lib/canonical-cigar-record";
import type { IndustryPackagingPayload, IndustryProductPayload, IndustryReleasePayload } from "@/lib/industry-registry";
import { TrustMark } from "@/components/trust-mark";
import { publicPageMetadata } from "@/lib/seo";
import { brand } from "@/lib/brand";
import "./registry.css";

export const dynamic="force-dynamic";
export const metadata:Metadata=publicPageMetadata("Official Product & Release Registry","Official products, releases, packaging revisions, and evidence-aware canonical cigar records.","/industry/registry");

export default async function IndustryRegistryPage(){
  const[inventory,industry]=await Promise.all([loadInventory(),loadPublicIndustry()]);
  const catalog=await loadCatalog(inventory);
  const products=industry.registryRecords.filter(item=>item.recordType==="product");
  const releases=industry.registryRecords.filter(item=>item.recordType==="release");
  const packaging=industry.registryRecords.filter(item=>item.recordType==="packaging");
  const canonical=catalog.map(item=>buildCanonicalCigarRecord(item,inventory)).filter(item=>item.status==="Verified foundation").sort((a,b)=>a.brand.localeCompare(b.brand)||a.line.localeCompare(b.line));
  return <main className="shell wideShell registryPage">
    <section className="registryHero"><div><div className="eyebrow">Industry Hub · Living record</div><h1>Products, releases, and artifacts—preserved as history.</h1><p className="lede">Official organization records and the platform’s evidence-aware cigar identities remain visibly distinct. Unknown facts stay unknown until a source supports them.</p></div><aside><TrustMark kind="Official"/><strong>Official identifies the source.</strong><p>Manufacturer publication does not replace independent verification, collector experience, or independent editorial judgment.</p></aside></section>
    <section className="registryMetrics"><article><strong>{products.length}</strong><span>official products</span></article><article><strong>{releases.length}</strong><span>official releases</span></article><article><strong>{packaging.length}</strong><span>artifact revisions</span></article><article><strong>{canonical.length}</strong><span>canonical identities</span></article></section>
    <nav className="registryJump" aria-label="Registry sections"><a href="#products">Products</a><a href="#releases">Release timeline</a><a href="#packaging">Packaging & authentication</a><a href="#canonical">Canonical records</a></nav>
    <section className="registrySection" id="products"><div className="sectionHead"><div><div className="eyebrow">Official product catalog</div><h2>What organizations currently make—and what they preserve.</h2></div></div><div className="registryCards">{products.map(item=>{const product=item.payload as IndustryProductPayload;return <article key={item.id}><TrustMark kind="Official" compact/><small>{item.organizationName} · Published {new Date(item.publishedAt).toLocaleDateString()}</small><h3>{product.brand} {product.line}</h3><p>{product.description}</p><dl><div><dt>Status</dt><dd>{product.productionStatus.replaceAll("_"," ")}</dd></div><div><dt>Factory</dt><dd>{product.factory||"Not officially stated"}</dd></div><div><dt>Blender</dt><dd>{product.blender||"Not officially stated"}</dd></div><div><dt>Blend</dt><dd>{[product.wrapper,product.binder,product.filler].filter(Boolean).join(" · ")||"Not officially disclosed"}</dd></div></dl>{product.officialProductUrl&&<a href={product.officialProductUrl} target="_blank" rel="noreferrer">Open official source ↗</a>}</article>})}{!products.length&&<div className="registryEmpty">No organization-submitted product has completed {brand.name}’s separate verification and publication gates yet.</div>}</div></section>
    <section className="registrySection" id="releases"><div className="sectionHead"><div><div className="eyebrow">Official release registry</div><h2>A dated timeline, not a disappearing announcement.</h2></div></div><div className="releaseTimeline">{releases.map(item=>{const release=item.payload as IndustryReleasePayload;return <article key={item.id}><time>{release.releaseDate}</time><div><TrustMark kind="Official" compact/><small>{item.organizationName} · {release.availabilityStatus.replaceAll("_"," ")}</small><h3>{release.releaseName}</h3><strong>{release.productName}</strong><p>{release.vitolas}</p><dl><div><dt>Release type</dt><dd>{release.releaseType.replaceAll("_"," ")}</dd></div><div><dt>MSRP</dt><dd>{release.msrp||"Not officially stated"}</dd></div><div><dt>Production</dt><dd>{release.productionQuantity||"Not officially stated"}</dd></div></dl>{release.officialReleaseUrl&&<a href={release.officialReleaseUrl} target="_blank" rel="noreferrer">Inspect official release source ↗</a>}</div></article>})}{!releases.length&&<div className="registryEmpty">The release ledger is ready. No official release has completed publication yet.</div>}</div></section>
    <section className="registrySection" id="packaging"><div className="sectionHead"><div><div className="eyebrow">Packaging & authentication registry</div><h2>Every meaningful artifact change retains its date.</h2></div></div><div className="artifactGrid">{packaging.map(item=>{const artifact=item.payload as IndustryPackagingPayload;return <article key={item.id}>{artifact.imageUrl&&<img src={artifact.imageUrl} alt=""/>}<div><TrustMark kind="Official" compact/><small>{item.organizationName} · {artifact.artifactType}</small><h3>{artifact.revisionName}</h3><strong>{artifact.productName}</strong><p>{artifact.description}</p><dl><div><dt>Effective</dt><dd>{artifact.effectiveFrom}{artifact.effectiveTo?`–${artifact.effectiveTo}`:"–present"}</dd></div><div><dt>Box code</dt><dd>{artifact.boxCodeGuidance||"No official guidance supplied"}</dd></div></dl>{artifact.authenticationGuidance&&<p className="artifactGuidance"><b>Authentication guidance</b>{artifact.authenticationGuidance}</p>}{artifact.counterfeitWarning&&<p className="artifactWarning"><b>Counterfeit alert</b>{artifact.counterfeitWarning}</p>}{artifact.officialSourceUrl&&<a href={artifact.officialSourceUrl} target="_blank" rel="noreferrer">Open official artifact source ↗</a>}</div></article>})}{!packaging.length&&<div className="registryEmpty">No band, box, seal, or packaging revision has completed publication yet.</div>}</div></section>
    <section className="registrySection" id="canonical"><div className="sectionHead"><div><div className="eyebrow">Canonical records</div><h2>The evidence-aware identity layer.</h2><p className="small">Public records have a documented product-level source, exact factory evidence, and at least 75% field coverage. Developing and research-required records remain in the private research workflow until they qualify.</p></div><a className="button secondary" href="/provenance-graph">Understand the provenance graph</a></div><div className="canonicalRegistry">{canonical.map(record=><a href={canonicalCatalogHref(record.catalogId)} key={record.catalogId}><span>{record.status}</span><h3>{record.brand}</h3><p>{record.line} · {record.vitola}</p><i><b style={{width:`${record.completion}%`}}/></i><small>{record.completion}% complete · {record.researchGaps.length} evidence gaps</small></a>)}{!canonical.length&&<div className="registryEmpty">No canonical cigar identity has met the public evidence threshold yet. Incomplete research is preserved privately and will appear here only after it qualifies.</div>}</div></section>
  </main>;
}
