import { NextResponse } from "next/server";
import { createClient as createAdmin } from "@supabase/supabase-js";
import { CommunityPostInput,CommunityRatingInput,communityCigarKey,communityTop25,type CommunityPost,type CommunityRating } from "@/lib/community";
import { moderateCommunityContent } from "@/lib/community-moderation";
import { createClient,supabaseConfigured } from "@/lib/supabase/server";

function admin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim(),key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)throw new Error("Community database is not configured");return createAdmin(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
const postShape=(row:Record<string,unknown>):CommunityPost=>({id:String(row.id),displayName:String(row.display_name),category:row.category as CommunityPost["category"],title:String(row.title),body:String(row.body),status:row.status as CommunityPost["status"],moderationReason:row.moderation_reason?String(row.moderation_reason):undefined,createdAt:String(row.created_at)});
const ratingShape=(row:Record<string,unknown>):CommunityRating=>({id:String(row.id),userId:String(row.user_id),displayName:String(row.display_name),cigarKey:String(row.cigar_key),brand:String(row.brand),line:String(row.line),vitola:String(row.vitola),vintage:row.vintage?String(row.vintage):undefined,score:Number(row.score),review:row.review?String(row.review):undefined,status:row.status as CommunityRating["status"],createdAt:String(row.created_at)});

export async function GET(){try{const client=admin();const[posts,ratings]=await Promise.all([client.from("community_posts").select("*").eq("status","active").order("created_at",{ascending:false}).limit(50),client.from("community_ratings").select("*").eq("status","active").limit(10000)]);if(posts.error||ratings.error)throw posts.error||ratings.error;const shapedRatings=(ratings.data||[]).map(row=>ratingShape(row));return NextResponse.json({data:{posts:(posts.data||[]).map(row=>postShape(row)),top25:communityTop25(shapedRatings),ratingCount:shapedRatings.length}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Community unavailable"},{status:502})}}

export async function POST(request:Request){if(!supabaseConfigured())return NextResponse.json({error:"Sign in before contributing"},{status:401});const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Sign in before contributing"},{status:401});try{const payload=await request.json() as{type?:string;data?:unknown};const client=admin();if(payload.type==="post"){const input=CommunityPostInput.parse(payload.data);const recentSince=new Date(Date.now()-120_000).toISOString();const{data:existing,error:lookupError}=await client.from("community_posts").select("*").eq("user_id",user.id).eq("title",input.title).eq("body",input.body).gte("created_at",recentSince).order("created_at",{ascending:false}).limit(1).maybeSingle();if(lookupError)throw lookupError;if(existing)return NextResponse.json({data:postShape(existing),message:existing.status==="active"?"This discussion is already posted.":"This discussion is already awaiting administrator review."});const moderation=await moderateCommunityContent(`${input.title}\n${input.body}`);if(moderation.decision==="block")return NextResponse.json({error:moderation.reason},{status:422});const{data,error}=await client.from("community_posts").insert({user_id:user.id,display_name:input.displayName,category:input.category,title:input.title,body:input.body,status:moderation.decision==="allow"?"active":"review",moderation_reason:moderation.reason}).select().single();if(error)throw error;return NextResponse.json({data:postShape(data),message:moderation.decision==="allow"?"Posted to the community.":"Submitted for administrator review."},{status:201})}if(payload.type==="rating"){const input=CommunityRatingInput.parse(payload.data);const moderation=await moderateCommunityContent(input.review||`${input.brand} ${input.line} ${input.vitola}`);if(moderation.decision==="block")return NextResponse.json({error:moderation.reason},{status:422});const cigarKey=communityCigarKey(input);const{data,error}=await client.from("community_ratings").upsert({user_id:user.id,display_name:input.displayName,cigar_key:cigarKey,brand:input.brand,line:input.line,vitola:input.vitola,vintage:input.vintage===undefined?null:String(input.vintage),score:input.score,review:input.review||null,status:moderation.decision==="allow"?"active":"review",moderation_reason:moderation.reason,updated_at:new Date().toISOString()},{onConflict:"user_id,cigar_key"}).select().single();if(error)throw error;return NextResponse.json({data:ratingShape(data),message:moderation.decision==="allow"?"Rating added to the Top 25 calculation.":"Rating submitted for administrator review."},{status:201})}return NextResponse.json({error:"Unknown community contribution"},{status:400})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Invalid contribution"},{status:422})}}
