import type { MetadataRoute } from "next";
import { absoluteSiteUrl, siteUrl } from "@/lib/seo";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: ["/manifesto", "/constitution", "/data-model", "/industry", "/learn", "/og.png", "/cedriva-mark.svg"],
      disallow: [
        "/api/",
        "/account",
        "/acquisitions",
        "/activity",
        "/ai-administrator",
        "/alerts",
        "/auction-market",
        "/briefing",
        "/catalog-discovery",
        "/cigar-somm",
        "/cigars/",
        "/collection-",
        "/collections",
        "/community",
        "/decision-center",
        "/founder-",
        "/humidors",
        "/intelligence",
        "/inventory",
        "/legacy",
        "/login",
        "/notifications",
        "/partner-",
        "/partners/",
        "/pricing",
        "/provenance-graph",
        "/ratings",
        "/records",
        "/recover",
        "/reports",
        "/reset-password",
        "/sensors",
        "/storage",
        "/system-health",
        "/trust-scorecard",
        "/valuations",
        "/value-history",
        "/verification",
        "/wishlist",
      ],
    },
    sitemap: absoluteSiteUrl("/sitemap.xml"),
    host: siteUrl(),
  };
}
