"use client";
import { FormEvent, useMemo, useRef, useState } from "react";
import type { DataMode } from "@/lib/config";
import { activityTypes } from "@/lib/activity-model";
import type { InventoryActivity, InventoryItem } from "@/lib/types";const today=()=>new Date().toISOString().slice(0,10);const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
import { createClientUuid } from "@/lib/client-uuid";
import { readSaveResponse, saveRecoveryMessage } from "@/lib/save-recovery";
import { useDeviceFormDraft } from "@/components/use-device-form-draft";
import { useUnsavedChanges } from "@/components/use-unsaved-changes";

export function ActivityManager({inventory,initialActivities,mode,selectedId}:{inventory:InventoryItem[];initialActivities:InventoryActivity[];mode:DataMode;selectedId?:string}){
  const[activities,setActivities]=useState(initialActivities);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[filter,setFilter]=useState(selectedId||"");const[submissionId,setSubmissionId]=useState(createClientUuid);
  const[lastSaved,setLastSaved]=useState<InventoryActivity>();const saveInFlight=useRef(false);const activityDraft=useDeviceFormDraft("hojavia:form-draft:activity:v1");const activitySafety=useUnsavedChanges();
  const visible=useMemo(()=>filter?activities.filter(a=>a.inventoryId===filter):activities,[activities,filter]);
  function captureActivity(event:FormEvent<HTMLFormElement>){activitySafety.markDirty();activityDraft.capture(event);setLastSaved(undefined)}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(saveInFlight.current)return;saveInFlight.current=true;setBusy(true);setMessage("");const form=event.currentTarget;const values=new FormData(form);const writeKey=String(values.get("writeKey")||"");const payload={...Object.fromEntries([...values.entries()].flatMap(([key,value])=>key==="writeKey"||value===""?[]:[[key,["quantity","boxes","totalAmount"].includes(key)?Number(value):value]])),submissionId};try{const response=await fetch("/api/activities",{method:"POST",headers:{"Content-Type":"application/json","x-founder-key":writeKey},body:JSON.stringify(payload)});const result=await readSaveResponse(response);if(!response.ok)throw new Error(result.error||"Save failed");setActivities(list=>list.some(value=>value.activityId===result.data.activityId)?list:[result.data,...list]);setSubmissionId(createClientUuid());setFilter(result.data.inventoryId);setLastSaved(result.data);const balance=result.inventory?.currentQty??result.data.resultingQuantity;setMessage(mode==="supabase"?`Activity saved with the inventory update.${balance===undefined?"":` Vault balance is now ${balance}.`} The change will appear across your signed-in devices.`:"Activity and inventory balance saved to the Smartsheet master.");form.reset();activityDraft.clear();activitySafety.markSaved()}catch(error){setMessage(saveRecoveryMessage(error,"this collection activity"))}finally{saveInFlight.current=false;setBusy(false)}}
  return <><section className="activityMetrics"><article><span>Ledger events</span><strong>{activities.length}</strong><small>Permanent history</small></article><article><span>Net stick change</span><strong>{activities.reduce((n,a)=>n+(a.quantityChange||0),0)}</strong><small>Across recorded events</small></article><article><span>Recorded value</span><strong>{money(activities.reduce((n,a)=>n+(a.totalAmount||0),0))}</strong><small>Purchases and sales</small></article></section>
  <div className="activityLayout"><section className="card"><div className="eyebrow">New ledger event</div><h2>Update the collection</h2>{activityDraft.restoredFields&&<p className="deviceDraftNotice" role="status">Your unfinished activity was restored from this browser profile. Review it before saving.</p>}<form ref={activityDraft.formRef} className="recordForm" onSubmit={save} onChange={captureActivity} aria-busy={busy}><label><span>Inventory lot</span><select name="inventoryId" required defaultValue={selectedId||""}><option value="">Select a cigar</option>{inventory.map(i=><option key={i.inventoryId} value={i.inventoryId}>{i.brand} · {i.line} · {i.inventoryId}</option>)}</select></label><label><span>Activity</span><select name="eventType">{activityTypes.map(type=><option key={type}>{type}</option>)}</select></label><p className="small">For a Correction, enter the corrected total number of sticks—not the amount to add or remove.</p><label><span>Date</span><input name="eventDate" type="date" required defaultValue={today()}/></label><div className="activityPair"><label><span>Sticks / corrected total</span><input name="quantity" type="number" min="0" defaultValue="0"/></label><label><span>Boxes</span><input name="boxes" type="number" min="0" defaultValue="0"/></label></div><label><span>Purchase / sale total</span><input name="totalAmount" type="number" min="0" step=".01" placeholder="$0.00"/></label><label><span>Destination storage</span><input name="toStorage" placeholder="Humidor / drawer / shelf"/></label><label><span>Notes</span><textarea name="notes" rows={3}/></label>{mode==="smartsheet"&&<label><span>Founder write key</span><input name="writeKey" type="password" required/></label>}<button className="button" disabled={busy||mode==="mock"}>{busy?"Saving…":"Save activity"}</button>{message&&<output aria-live="polite">{message}</output>}</form>{lastSaved&&<div className="mutationCompletion" aria-live="polite"><strong>Collection history updated.</strong><div><button type="button" className="button secondary" onClick={()=>{setLastSaved(undefined);setMessage("");activityDraft.formRef.current?.querySelector<HTMLSelectElement>('select[name="inventoryId"]')?.focus()}}>Record another activity</button><a className="button secondary" href={`/inventory/${encodeURIComponent(lastSaved.inventoryId)}`}>Open cigar record</a><a className="textLink" href="/inventory">Return to Vault</a></div></div>}</section>
  <section><div className="activityToolbar"><div><div className="eyebrow">Collection history</div><h2>{visible.length} events</h2></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All cigars</option>{inventory.map(i=><option key={i.inventoryId} value={i.inventoryId}>{i.brand} · {i.line}</option>)}</select></div><div className="activityFeed">{visible.map(a=>{const item=inventory.find(i=>i.inventoryId===a.inventoryId);return <article key={a.activityId} className="activityEvent"><div className="activityMark">{(a.quantityChange||0)>0?"+":(a.quantityChange||0)<0?"−":"↔"}</div><div><div className="activityTitle"><strong>{a.eventType}</strong><span>{a.eventDate}</span></div><a href={`/inventory/${a.inventoryId}`}>{item?`${item.brand} ${item.line}`:a.inventoryId}</a><p>{a.notes||`${a.quantityChange||0} sticks · resulting balance ${a.resultingQuantity??"—"}`}</p></div><div className="activityBalance"><strong>{a.resultingQuantity??"—"}</strong><span>remaining</span>{a.totalAmount!==undefined&&<small>{money(a.totalAmount)}</small>}</div></article>})}{!visible.length&&<div className="emptyState">No activity has been recorded yet. Your first event will appear here.</div>}</div></section></div></>;
}
