"use client";
import{useState,type FormEvent}from"react";
import{certificationLevels,placeCapabilities,placeVibes,type GooglePlaceResult,type PlaceCertification}from"@/lib/places";
type Result=GooglePlaceResult&{cedrivaScore?:number;cedrivaReviewCount:number;cedrivaScoreStatus:"Established"|"Developing";vibes:Array<{vibe:string;count:number}>;certification?:PlaceCertification};
export function PlaceDirectory(){
 const[zip,setZip]=useState(""),[results,setResults]=useState<Result[]>([]),[selected,setSelected]=useState<Result>(),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[meta,setMeta]=useState<{retrievedAt:string;methodology:string}>();
 async function search(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const response=await fetch(`/api/places/search?zip=${encodeURIComponent(zip)}`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Search failed");setResults(body.data);setMeta(body.meta);if(!body.data.length)setMessage("No verified matches found. Try a nearby ZIP code.")}catch(error){setMessage(error instanceof Error?error.message:"Search failed")}finally{setBusy(false)}}
 async function review(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);const body={googlePlaceId:selected.googlePlaceId,displayName:String(form.get("displayName")),score:Number(form.get("score")),visitDate:String(form.get("visitDate")),vibes:form.getAll("vibes"),capabilities:form.getAll("capabilities"),review:String(form.get("review")),conflictDisclosure:String(form.get("conflictDisclosure")||"")||undefined};setBusy(true);try{const response=await fetch("/api/places/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.error);setMessage(result.message);setSelected(undefined)}catch(error){setMessage(error instanceof Error?error.message:"Review failed")}finally{setBusy(false)}}
 async function certify(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);const body={googlePlaceId:selected.googlePlaceId,level:String(form.get("level")),score:Number(form.get("score")),visitMonth:String(form.get("visitMonth")),summary:String(form.get("summary")),strengths:String(form.get("strengths")),opportunities:String(form.get("opportunities")||"")||undefined,complimentaryDisclosure:String(form.get("complimentaryDisclosure")||"")||undefined,nextReviewDate:String(form.get("nextReviewDate"))};setBusy(true);try{const response=await fetch("/api/places/certifications",{method:"POST",headers:{"content-type":"application/json","x-founder-key":String(form.get("writeKey")||"")},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.error);setMessage("Cedriva certification saved independently.");setSelected(undefined)}catch(error){setMessage(error instanceof Error?error.message:"Certification failed")}finally{setBusy(false)}}
 return <><section className="placeSearch card"><div><div className="eyebrow">Live location discovery</div><h2>Find cigar culture near you.</h2><p>Search cigar lounges, cigar bars, and brick-and-mortar retailers. Google and Cedriva scores remain visibly separate.</p></div><form onSubmit={search}><label><span>U.S. ZIP code</span><input value={zip} onChange={event=>setZip(event.target.value)} inputMode="numeric" pattern="\d{5}(-\d{4})?" placeholder="90210" required/></label><button className="button" disabled={busy}>{busy?"Searching live sources…":"Find locations"}</button></form></section>
 {message&&<output className="placeMessage">{message}</output>}
 {meta&&<aside className="placeMethod"><strong>Transparent ranking</strong><span>{meta.methodology}</span><small>Google data retrieved {new Date(meta.retrievedAt).toLocaleString()} · Google ratings are not Cedriva ratings.</small></aside>}
 <section className="placeResults">{results.map((place,index)=><article key={place.googlePlaceId}><header><span>#{index+1} nearby result</span>{place.certification&&<b>{place.certification.level}</b>}</header><h2>{place.name}</h2><p>{place.address}</p><div className="dualScores"><div><span>Google rating</span><strong>{place.googleRating??"—"}</strong><small>{place.googleReviewCount??0} Google reviews</small></div><div><span>Cedriva Community</span><strong>{place.cedrivaScore??"Developing"}</strong><small>{place.cedrivaReviewCount} verified visit{place.cedrivaReviewCount===1?"":"s"}</small></div>{place.certification&&<div><span>Independent critic</span><strong>{place.certification.score}</strong><small>{place.certification.visitMonth}</small></div>}</div>{place.vibes.length>0&&<div className="placeVibes">{place.vibes.map(value=><span key={value.vibe}>{value.vibe} · {value.count}</span>)}</div>}{place.certification&&<blockquote>{place.certification.summary}</blockquote>}<footer><a href={place.googleMapsUri} target="_blank" rel="noreferrer">View on Google Maps ↗</a>{place.websiteUri&&<a href={place.websiteUri} target="_blank" rel="noreferrer">Official website ↗</a>}<button onClick={()=>setSelected(place)}>Review or certify</button></footer></article>)}</section>
 {selected&&<section className="placeContribution"><header><div><div className="eyebrow">Document a visit</div><h2>{selected.name}</h2><p>Community experience and independent Cedriva certification are separate records.</p></div><button onClick={()=>setSelected(undefined)}>Close</button></header><div><form className="card" onSubmit={review}><h3>Cedriva Community review</h3><label><span>Display name</span><input name="displayName" required/></label><label><span>Visit date</span><input name="visitDate" type="date" required/></label><label><span>Overall experience (1–100)</span><input name="score" type="number" min="1" max="100" required/></label><fieldset><legend>Atmosphere & vibe · choose up to three</legend>{placeVibes.map(vibe=><label key={vibe}><input type="checkbox" name="vibes" value={vibe}/>{vibe}</label>)}</fieldset><fieldset><legend>What is available?</legend>{placeCapabilities.map(value=><label key={value}><input type="checkbox" name="capabilities" value={value}/>{value}</label>)}</fieldset><label><span>Review</span><textarea name="review" minLength={20} rows={5} required/></label><label><span>Conflict or complimentary-item disclosure</span><input name="conflictDisclosure"/></label><button className="button" disabled={busy}>Submit community review</button></form><form className="card" onSubmit={certify}><h3>Founder-only independent assessment</h3><p>Certification cannot be purchased. Use an unannounced critic-style visit and disclose any relationship or complimentary item.</p><label><span>Designation</span><select name="level">{certificationLevels.map(value=><option key={value}>{value}</option>)}</select></label><label><span>Critic score</span><input name="score" type="number" min="1" max="100" required/></label><label><span>Visit month</span><input name="visitMonth" type="month" required/></label><label><span>Assessment</span><textarea name="summary" minLength={40} rows={5} required/></label><label><span>Strengths</span><textarea name="strengths" minLength={10} rows={3} required/></label><label><span>Opportunities</span><textarea name="opportunities" rows={3}/></label><label><span>Complimentary items / relationship</span><input name="complimentaryDisclosure"/></label><label><span>Next review</span><input name="nextReviewDate" type="date" required/></label><label><span>Founder write key</span><input name="writeKey" type="password" required/></label><button className="button" disabled={busy}>Save independent certification</button></form></div></section>}
 </>;
}
