"use client";
import { useState } from "react";
import type { InventoryItem, ProfessionalRating } from "@/lib/types";
import type { RatingResearch } from "@/lib/cigar-ratings";
type Draft=RatingResearch&{inventoryId:string};
export function RatingResearchPanel({items,initialRatings}:{items:InventoryItem[];initialRatings:ProfessionalRating[]}){const[ratings,setRatings]=useState(initialRatings);const[drafts,setDrafts]=useState<Record<string,Draft>>({});const[busy,setBusy]=useState("");const[message,setMessage]=useState("");
async function research(item:InventoryItem){setBusy(item.inventoryId);setMessage("");try{const response=await fetch("/api/rating-research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({inventoryId:item.inventoryId})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Research failed");setDrafts(current=>({...current,[item.inventoryId]:result.data}))}catch(error){setMessage(error instanceof Error?error.message:"Research failed")}finally{setBusy("")}}
async function save(inventoryId:string,index:number){const candidate=drafts[inventoryId]?.ratings[index];if(!candidate)return;setBusy(`${inventoryId}-${index}`);setMessage("");const payload={...candidate,ratingId:`RATE-${inventoryId}-${Date.now().toString(36).toUpperCase()}-${index}`,inventoryId,matchedVintage:candidate.matchedVintage??undefined,reviewDate:candidate.reviewDate||undefined,reviewer:candidate.reviewer||undefined,createdAt:new Date().toISOString()};try{const response=await fetch("/api/ratings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Save failed");setRatings(current=>[...current,result.data]);setDrafts(current=>({...current,[inventoryId]:{...current[inventoryId],ratings:current[inventoryId].ratings.filter((_,candidateIndex)=>candidateIndex!==index)}}));setMessage(`${candidate.publication} rating saved to ${inventoryId}.`)}catch(error){setMessage(error instanceof Error?error.message:"Save failed")}finally{setBusy("")}}
return <section className="ratingWorkspace"><div className="ratingList">{items.map(item=>{const existing=ratings.filter(rating=>rating.inventoryId===item.inventoryId);const draft=drafts[item.inventoryId];return <article key={item.inventoryId}><div className="ratingIdentity"><strong>{item.brand} {item.line}</strong><span>{item.vitola} · {item.vintage??"year unspecified"}</span><small>{existing.length?`${existing.length} saved professional rating${existing.length===1?"":"s"}`:"No professional ratings saved"}</small></div><div className="savedRatings">{existing.sort((a,b)=>b.score-a.score).slice(0,3).map(rating=><a href={rating.sourceUrl} target="_blank" rel="noreferrer" key={rating.ratingId}><strong>{rating.score}</strong><span>{rating.publication}</span><small>{rating.matchConfidence} match ↗</small></a>)}</div>{draft?<div className="ratingDrafts">{draft.ratings.length?draft.ratings.map((rating,index)=><div key={`${rating.sourceUrl}-${index}`}><strong>{rating.score}</strong><span>{rating.publication} · {rating.matchConfidence} match</span><p>{rating.summary}</p><a href={rating.sourceUrl} target="_blank" rel="noreferrer">Review source ↗</a><button className="button" disabled={Boolean(busy)} onClick={()=>save(item.inventoryId,index)}>Approve & save</button></div>):<p>No defensible exact professional rating was found. Nothing will be saved.</p>}<small>{draft.notes}</small></div>:<button className="button secondary" disabled={Boolean(busy)} onClick={()=>research(item)}>{busy===item.inventoryId?"Searching publications…":"Research ratings"}</button>}</article>})}</div>{message&&<output>{message}</output>}</section>}
