"use client";
import { FormEvent,useState } from "react";
import type { DataMode } from "@/lib/config";
import type { InventoryItem,SmokingLog,Valuation } from "@/lib/types";
const today=()=>new Date().toISOString().slice(0,10);
export function RecordsManager({inventory,initialSmokes,initialValuations,mode}:{inventory:InventoryItem[];initialSmokes:SmokingLog[];initialValuations:Valuation[];mode:DataMode}){const[smokes,setSmokes]=useState(initialSmokes);const[valuations,setValuations]=useState(initialValuations);const[message,setMessage]=useState("");
async function send(event:FormEvent<HTMLFormElement>,kind:"smoke"|"valuation"){event.preventDefault();const form=new FormData(event.currentTarget);const key=String(form.get("writeKey")||"");const numeric=new Set(["overall","replacementValue","marketValue"]);const boolean=new Set(["buyAgain"]);const payload=Object.fromEntries([...form.entries()].flatMap(([name,value])=>name==="writeKey"||value===""?[]:[[name,numeric.has(name)?Number(value):boolean.has(name)?value==="on":value]]));const response=await fetch(kind==="smoke"?"/api/smoking-log":"/api/valuations",{method:"POST",headers:{"Content-Type":"application/json","x-founder-key":key},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok){setMessage(result.error||"Save failed");return;}if(kind==="smoke")setSmokes(v=>[result.data,...v]);else setValuations(v=>[result.data,...v]);setMessage("Saved to Smartsheet.");event.currentTarget.reset();}
const picker=<select name="inventoryId" required><option value="">Select inventory lot</option>{inventory.map(i=><option key={i.inventoryId} value={i.inventoryId}>{i.inventoryId} · {i.brand} {i.line}</option>)}</select>;
return <div className="recordsGrid"><section className="card"><h2>Log a smoke</h2><form className="recordForm" onSubmit={e=>send(e,"smoke")}><label><span>Smoke ID</span><input name="smokeId" required placeholder="SMK-0001"/></label><label><span>Inventory lot</span>{picker}</label><label><span>Date</span><input name="dateSmoked" type="date" required defaultValue={today()}/></label><label><span>Score</span><input name="overall" type="number" min="0" max="100"/></label><label><span>Flavor</span><input name="flavor"/></label><label><span>Strength</span><input name="strength"/></label><label><span>Tasting notes</span><textarea name="tastingNotes" rows={4}/></label><label className="check"><input name="buyAgain" type="checkbox"/> Buy again</label>{mode==="smartsheet"&&<label><span>Founder write key</span><input name="writeKey" type="password" required/></label>}<button className="button" disabled={mode==="mock"}>Save smoke</button></form><div className="recordList"><h3>Recent smokes</h3>{smokes.slice(0,8).map(s=><div key={s.smokeId}><strong>{s.inventoryId}</strong><span>{s.dateSmoked} · {s.overall??"—"}</span></div>)}</div></section>
<section className="card"><h2>Add a valuation</h2><form className="recordForm" onSubmit={e=>send(e,"valuation")}><label><span>Valuation ID</span><input name="valuationId" required placeholder="VAL-0001"/></label><label><span>Inventory lot</span>{picker}</label><label><span>Date</span><input name="valuationDate" type="date" required defaultValue={today()}/></label><label><span>Replacement value</span><input name="replacementValue" type="number" min="0" step=".01"/></label><label><span>Market value</span><input name="marketValue" type="number" min="0" step=".01"/></label><label><span>Source</span><input name="source"/></label><label><span>Source URL</span><input name="sourceUrl" type="url"/></label><label><span>Confidence</span><select name="confidence"><option>High</option><option>Medium</option><option>Low</option></select></label>{mode==="smartsheet"&&<label><span>Founder write key</span><input name="writeKey" type="password" required/></label>}<button className="button" disabled={mode==="mock"}>Save valuation</button></form><div className="recordList"><h3>Recent valuations</h3>{valuations.slice(0,8).map(v=><div key={v.valuationId}><strong>{v.inventoryId}</strong><span>{v.valuationDate} · ${v.marketValue??v.replacementValue??0}</span></div>)}</div></section>{message&&<output className="wideMessage">{message}</output>}</div>}
