"use client";
import { useState } from "react";
import type { DataMode } from "@/lib/config";
import type { InventoryItem } from "@/lib/types";
import type { ValuationResearch } from "@/lib/valuation-research";
import { marketRangeText } from "@/lib/valuation-evidence";
type Draft=ValuationResearch&{inventoryId:string;currentQty?:number;lotMarketValue:number|null;lotReplacementValue:number|null;submissionId:string};
const money=(value:number|null|undefined)=>value===null||value===undefined?"—":value.toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2});
export function ValuationResearchPanel({items,mode}:{items:InventoryItem[];mode:DataMode}){const[drafts,setDrafts]=useState<Record<string,Draft>>({});const[busy,setBusy]=useState("");const[message,setMessage]=useState("");const[key,setKey]=useState("");
 async function research(item:InventoryItem){setBusy(item.inventoryId);setMessage("");try{const response=await fetch("/api/valuation-research",{method:"POST",headers:{"Content-Type":"application/json",...(key?{"x-founder-key":key}:{})},body:JSON.stringify({inventoryId:item.inventoryId})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Research failed");setDrafts(current=>({...current,[item.inventoryId]:{...result.data,submissionId:crypto.randomUUID()}}))}catch(error){setMessage(error instanceof Error?error.message:"Research failed")}finally{setBusy("")}}
 async function save(draft:Draft){setBusy(draft.inventoryId);setMessage("");try{const response=await fetch("/api/valuations",{method:"POST",headers:{"Content-Type":"application/json",...(key?{"x-founder-key":key}:{})},body:JSON.stringify({submissionId:draft.submissionId,inventoryId:draft.inventoryId,valuationDate:draft.evidenceDate,replacementValue:draft.replacementValue??undefined,marketValue:draft.marketValue??undefined,marketEvidenceType:draft.marketEvidenceType,marketRangeLow:draft.marketRangeLow??undefined,marketRangeHigh:draft.marketRangeHigh??undefined,askingPrice:draft.askingPrice??undefined,askingPriceSource:draft.askingPriceSource||undefined,askingPriceSourceUrl:draft.askingPriceSourceUrl||undefined,comparableCount:draft.comparables.length,lastSaleValue:draft.lastSaleValue??undefined,lastSaleDate:draft.lastSaleDate??undefined,lastSaleVenue:draft.lastSaleVenue??undefined,lastSaleSourceUrl:draft.lastSaleSourceUrl??undefined,source:draft.source,sourceUrl:draft.sourceUrl||undefined,confidence:draft.confidence,notes:draft.notes})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Save failed");setDrafts(current=>{const next={...current};delete next[draft.inventoryId];return next});setMessage(`${draft.inventoryId} valuation saved.`)}catch(error){setMessage(error instanceof Error?error.message:"Save failed")}finally{setBusy("")}}
 return <section className="section valueResearch"><div className="sectionHead"><div><div className="eyebrow">Source-backed research</div><h2>Build valuation drafts</h2><p className="small">Retail replacement, asking prices, estimated ranges, and verified completed sales remain distinct. A single New World listing is recorded as an asking price—not promoted into a market value. Nothing saves until you approve it.</p></div>{mode==="smartsheet"&&<label><span>Founder write key</span><input type="password" value={key} onChange={event=>setKey(event.target.value)}/></label>}</div><div className="valueResearchList">{items.slice(0,8).map(item=>{const draft=drafts[item.inventoryId];const range=draft?marketRangeText({valuationId:"draft",inventoryId:item.inventoryId,valuationDate:draft.evidenceDate,marketRangeLow:draft.marketRangeLow??undefined,marketRangeHigh:draft.marketRangeHigh??undefined}):undefined;return <article key={item.inventoryId}><div><strong>{item.brand} {item.line}</strong><small>{item.vitola} · {item.currentQty??"?"} cigars · {item.vintage??"year unknown"}</small></div>{draft?<><div className="researchValues"><b data-evidence={draft.marketEvidenceType}>{draft.marketEvidenceType}</b><span>Retail replacement {money(draft.replacementValue)} / cigar</span><span>Observed asking {money(draft.askingPrice)} / cigar</span><span>Estimated range {range??"—"} / cigar</span><span>Verified sale {money(draft.lastSaleValue)} / cigar</span><strong>Retail lot {money(draft.lotReplacementValue)}</strong></div><div className="researchEvidence">{draft.lastSaleSourceUrl?<a href={draft.lastSaleSourceUrl} target="_blank" rel="noreferrer">{draft.lastSaleVenue||"Completed sale"} · {draft.lastSaleDate||"date unavailable"} ↗</a>:<small>No verified completed sale found</small>}{draft.askingPriceSourceUrl&&<a href={draft.askingPriceSourceUrl} target="_blank" rel="noreferrer">{draft.askingPriceSource||"Observed asking price"} ↗</a>}{draft.sourceUrl&&<a href={draft.sourceUrl} target="_blank" rel="noreferrer">{draft.source||"View strongest evidence"} ↗</a>}<small>{draft.confidence} confidence · {draft.comparables.length} comparable{draft.comparables.length===1?"":"s"}</small><p>{draft.notes}</p></div><button className="button" disabled={busy===item.inventoryId} onClick={()=>save(draft)}>Approve & save</button></>:<button className="button secondary" disabled={Boolean(busy)||(mode==="smartsheet"&&!key)} onClick={()=>research(item)}>{busy===item.inventoryId?"Researching…":"Research value"}</button>}</article>})}</div>{message&&<output className="wideMessage">{message}</output>}</section>}
