import { NextResponse } from "next/server";
import { CollectorPassportInput, publicPassportShape } from "@/lib/collector-passport";
import { createClient, supabaseConfigured } from "@/lib/supabase/server";

const columns="handle,display_name,bio,years_collecting,interests,favorite_origins,favorite_makers,favorite_vitolas,featured_cigars,visibility,updated_at";
function unavailable(error:unknown){const value=error as{code?:string;message?:string}|null;return value?.code==="42P01"||/collector_passports.*does not exist/i.test(value?.message||"")}
async function context(){if(!supabaseConfigured())return undefined;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();return user?{supabase,user}:undefined}
export async function GET(){const value=await context();if(!value)return NextResponse.json({error:"Sign in to manage your Collector Passport"},{status:401});const{data,error}=await value.supabase.from("collector_passports").select(columns).eq("user_id",value.user.id).maybeSingle();if(error)return NextResponse.json({error:unavailable(error)?"Collector Passport storage is prepared but not provisioned yet.":error.message,code:unavailable(error)?"passport_pending":"passport_unavailable"},{status:503});return NextResponse.json({data:data?publicPassportShape(data as Record<string,unknown>):null},{headers:{"Cache-Control":"private, no-store"}})}
export async function POST(request:Request){const value=await context();if(!value)return NextResponse.json({error:"Sign in to save your Collector Passport"},{status:401});try{const input=CollectorPassportInput.parse(await request.json());const row={user_id:value.user.id,handle:input.handle,display_name:input.displayName,bio:input.bio,years_collecting:input.yearsCollecting??null,interests:input.interests,favorite_origins:input.favoriteOrigins,favorite_makers:input.favoriteMakers,favorite_vitolas:input.favoriteVitolas,featured_cigars:input.featuredCigars,visibility:input.visibility,updated_at:new Date().toISOString()};const{data,error}=await value.supabase.from("collector_passports").upsert(row,{onConflict:"user_id"}).select(columns).single();if(error){if(unavailable(error))return NextResponse.json({error:"Collector Passport storage is prepared but not provisioned yet.",code:"passport_pending"},{status:503});throw error}return NextResponse.json({data:publicPassportShape(data as Record<string,unknown>),message:input.visibility==="community"?"Your curated Passport is visible inside the collector community. Your Vault remains private.":"Your Passport is saved privately."},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Collector Passport could not be saved"},{status:422})}}
