import { climateHealth } from "./climate-alerts";
import { loadInventory } from "./inventory";
import { getAlertDeliveries,getHumidorReadings,getHumidors,getSensors,saveAlertDelivery } from "./smartsheet";
import type { AlertDelivery } from "./types";

export function notificationConfiguration(){return{email:Boolean(process.env.RESEND_API_KEY&&process.env.ALERT_EMAIL_TO&&process.env.ALERT_EMAIL_FROM),sms:Boolean(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_FROM_NUMBER&&process.env.ALERT_SMS_TO),history:Boolean(process.env.SMARTSHEET_ALERTS_SHEET_ID)}}
async function sendEmail(subject:string,text:string,idempotencyKey:string){if(!notificationConfiguration().email)return false;const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify({from:process.env.ALERT_EMAIL_FROM,to:[process.env.ALERT_EMAIL_TO],subject,text})});if(!response.ok)throw new Error(`Email delivery failed (${response.status})`);return true}
export async function sendAccountEmail(to:string,subject:string,text:string,idempotencyKey:string){if(!process.env.RESEND_API_KEY||!process.env.ALERT_EMAIL_FROM)return false;const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify({from:process.env.ALERT_EMAIL_FROM,to:[to],subject,text})});if(!response.ok)throw new Error(`Email delivery failed (${response.status})`);return true}
async function sendSms(text:string){if(!notificationConfiguration().sms)return false;const account=process.env.TWILIO_ACCOUNT_SID!;const body=new URLSearchParams({To:process.env.ALERT_SMS_TO!,From:process.env.TWILIO_FROM_NUMBER!,Body:text.slice(0,1500)});const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${account}/Messages.json`,{method:"POST",headers:{Authorization:`Basic ${btoa(`${account}:${process.env.TWILIO_AUTH_TOKEN}`)}`,"Content-Type":"application/x-www-form-urlencoded"},body});if(!response.ok)throw new Error(`Text delivery failed (${response.status})`);return true}
export async function sendTestNotifications(){const now=new Date().toISOString();const text=`Cedriva test alert — notification delivery is working. ${now}`;const[email,sms]=await Promise.all([sendEmail("Cedriva test alert",text,`cigar-vault-test-${Date.now()}`),sendSms(text)]);return{email,sms}}
export async function processClimateAlertNotifications(){const config=notificationConfiguration();if(!config.history||(!config.email&&!config.sms))return{enabled:false,sent:0,skipped:0};const[humidors,readings,sensors,inventory,existing]=await Promise.all([getHumidors(),getHumidorReadings(),getSensors(),loadInventory(),getAlertDeliveries()]);const known=new Set(existing.map(a=>a.alertId));let sent=0,skipped=0;for(const health of humidors.map(h=>climateHealth(h,readings,sensors,inventory))){for(const alert of health.alerts){const readingKey=health.latest?.externalReadingId||health.latest?.readingId||health.latest?.recordedAt||"no-reading";const alertId=`ALERT-${health.humidor.humidorId}-${alert.kind}-${readingKey}`.replace(/[^A-Za-z0-9_.:-]/g,"-").slice(0,190);if(known.has(alertId)){skipped++;continue}const subject=`${alert.severity}: ${health.humidor.name} ${alert.kind.toLowerCase()} alert`;const text=`Cedriva ${alert.severity} alert\n${health.humidor.name}\n${alert.message}\nStored value: $${health.storedValue.toLocaleString()}\nDetected: ${alert.recordedAt||new Date().toISOString()}`;let emailSent=false,smsSent=false;const errors:string[]=[];try{emailSent=await sendEmail(subject,text,alertId)}catch(e){errors.push(e instanceof Error?e.message:"Email failed")}try{smsSent=await sendSms(text)}catch(e){errors.push(e instanceof Error?e.message:"SMS failed")}const channels=[config.email,config.sms].filter(Boolean).length;const delivered=[emailSent,smsSent].filter(Boolean).length;const record:AlertDelivery={alertId,humidorId:health.humidor.humidorId,sensorId:health.sensor?.sensorId,severity:alert.severity,alertType:alert.kind,message:alert.message,readingId:health.latest?.readingId,detectedAt:new Date().toISOString(),emailSentAt:emailSent?new Date().toISOString():undefined,smsSentAt:smsSent?new Date().toISOString():undefined,status:delivered===channels?"Sent":delivered?"Partial":"Failed",notes:errors.join("; ")||undefined};await saveAlertDelivery(record);known.add(alertId);sent+=delivered?1:0;}}return{enabled:true,sent,skipped}}
