export type BetaActivityCollector={id:string;name:string;email:string;stage:string};
export type BetaActivityAccount={id:string;email?:string;created_at?:string;last_sign_in_at?:string};
export type BetaActivityRecord={user_id:string;kind:string;updated_at?:string;payload?:Record<string,unknown>};
export type BetaActivityEvent={user_id:string;event_type:string;created_at:string;properties?:Record<string,unknown>};
export type BetaActivityFeedback={user_id:string;status:string;severity:string;summary:string;created_at:string;page_url?:string};
export type RecoveryItem={action:string;label:string;state:"Unresolved"|"Recovered";failureCount:number;lastFailureAt:string;lastSuccessAt?:string;category?:string;statusCode?:string;path?:string;version?:string;recommendedFollowUp:string};
export type TesterActivityRow={id:string;name:string;email:string;stage:string;userId?:string;accountCreatedAt?:string;lastLoginAt?:string;installationConfirmedAt?:string;lastActivityAt?:string;inventoryLots:number;smokesLogged:number;inventoryActivities:number;openFeedback:number;urgentFeedback:number;recordedFailures:number;unresolvedFailures:number;recoveredFailures:number;state:"Ready"|"Needs attention";reasons:string[];recent:Array<{at:string;label:string}>;recoveryQueue:RecoveryItem[]};

const latest=(values:Array<string|undefined>)=>values.filter((value):value is string=>Boolean(value)).sort((a,b)=>b.localeCompare(a))[0];
const failedRun=(record:BetaActivityRecord)=>record.kind==="system-runs"&&String(record.payload?.status||"").toLowerCase()==="failed";
const actionLabels:Record<string,string>={"inventory-save":"Inventory save","smoke-save":"Smoke-log save","photo-upload":"Photo upload","feedback-submit":"Feedback submission","auth-sign-in":"Sign in","auth-recovery":"Account recovery"};
const failureLabels:Record<string,string>={"inventory-save":"Could not save inventory","smoke-save":"Could not save smoke log","photo-upload":"Could not upload photo","feedback-submit":"Could not submit feedback","auth-sign-in":"Could not sign in","auth-recovery":"Could not recover account"};
const followUps:Record<string,string>={"inventory-save":"Ask the tester to retry the same inventory save.","smoke-save":"Ask the tester to reopen Log a Smoke and retry once.","photo-upload":"Ask the tester to retry the photo from a stable connection.","feedback-submit":"Ask the tester to reopen Feedback and submit again.","auth-sign-in":"Resend confirmation or password-recovery instructions.","auth-recovery":"Confirm the tester uses only the newest recovery email."};

function buildRecoveryQueue(events:BetaActivityEvent[]){
  const outcomes=events.filter(event=>event.event_type==="app-operation-failed"||event.event_type==="app-operation-succeeded");
  const actions=[...new Set(outcomes.filter(event=>event.event_type==="app-operation-failed").map(event=>String(event.properties?.action||"")).filter(Boolean))];
  return actions.map(action=>{
    const failures=outcomes.filter(event=>event.event_type==="app-operation-failed"&&event.properties?.action===action).sort((a,b)=>b.created_at.localeCompare(a.created_at));
    const successes=outcomes.filter(event=>event.event_type==="app-operation-succeeded"&&event.properties?.action===action).sort((a,b)=>b.created_at.localeCompare(a.created_at));
    const failure=failures[0],success=successes[0],recovered=Boolean(success&&success.created_at>failure.created_at),properties=failure.properties||{};
    return{action,label:actionLabels[action]||"App operation",state:recovered?"Recovered"as const:"Unresolved"as const,failureCount:failures.length,lastFailureAt:failure.created_at,lastSuccessAt:recovered?success.created_at:undefined,category:typeof properties.category==="string"?properties.category:undefined,statusCode:typeof properties.statusCode==="string"?properties.statusCode:undefined,path:typeof properties.path==="string"?properties.path:undefined,version:typeof properties.version==="string"?properties.version:undefined,recommendedFollowUp:recovered?"No follow-up needed. A later attempt succeeded.":followUps[action]||"Ask the tester to retry the action once."};
  }).sort((a,b)=>a.state===b.state?b.lastFailureAt.localeCompare(a.lastFailureAt):a.state==="Unresolved"?-1:1);
}

export function buildBetaActivityDashboard(collectors:BetaActivityCollector[],accounts:BetaActivityAccount[],records:BetaActivityRecord[],events:BetaActivityEvent[],feedback:BetaActivityFeedback[]){
  const accountsByEmail=new Map(accounts.filter(account=>account.email).map(account=>[account.email!.trim().toLowerCase(),account]));
  const testers:TesterActivityRow[]=collectors.map(collector=>{
    const account=accountsByEmail.get(collector.email.trim().toLowerCase()),userId=account?.id,owned=userId?records.filter(record=>record.user_id===userId):[],userEvents=userId?events.filter(event=>event.user_id===userId):[],userFeedback=userId?feedback.filter(item=>item.user_id===userId):[];
    const open=userFeedback.filter(item=>item.status==="Open"||item.status==="Reviewing"),urgent=open.filter(item=>item.severity==="High"||item.severity==="Blocking"),failedRuns=owned.filter(failedRun),recoveryQueue=buildRecoveryQueue(userEvents),installs=userEvents.filter(event=>event.event_type==="app-install-confirmed");
    const failedEvents=userEvents.filter(event=>event.event_type==="app-operation-failed"),unresolvedFailures=failedRuns.length+recoveryQueue.filter(item=>item.state==="Unresolved").reduce((sum,item)=>sum+item.failureCount,0),recoveredFailures=recoveryQueue.filter(item=>item.state==="Recovered").reduce((sum,item)=>sum+item.failureCount,0),recordedFailures=failedRuns.length+failedEvents.length;
    const recent=[...owned.filter(record=>record.kind==="inventory"&&record.updated_at).map(record=>({at:record.updated_at!,label:"Added or updated inventory"})),...owned.filter(record=>record.kind==="smokes"&&record.updated_at).map(record=>({at:record.updated_at!,label:"Logged a smoke"})),...owned.filter(record=>record.kind==="activities"&&record.updated_at).map(record=>({at:record.updated_at!,label:"Recorded inventory activity"})),...userFeedback.map(item=>({at:item.created_at,label:`Submitted ${item.severity.toLowerCase()} feedback`})),...installs.map(event=>({at:event.created_at,label:"Confirmed phone app"})),...failedEvents.map(event=>({at:event.created_at,label:failureLabels[String(event.properties?.action||"")]||"App operation failed"}))].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,3);
    const reasons:string[]=[];if(!account)reasons.push("Account not created");else if(!account.last_sign_in_at)reasons.push("Login not confirmed");if(account&&!installs.length)reasons.push("Phone app not confirmed");if(urgent.length)reasons.push(`${urgent.length} urgent feedback item${urgent.length===1?"":"s"}`);if(unresolvedFailures)reasons.push(`${unresolvedFailures} unresolved operation failure${unresolvedFailures===1?"":"s"}`);
    const state:TesterActivityRow["state"]=reasons.length?"Needs attention":"Ready";
    return{id:collector.id,name:collector.name,email:collector.email,stage:collector.stage,userId,accountCreatedAt:account?.created_at,lastLoginAt:account?.last_sign_in_at,installationConfirmedAt:latest(installs.map(event=>event.created_at)),lastActivityAt:latest([account?.last_sign_in_at,...owned.map(record=>record.updated_at),...userEvents.map(event=>event.created_at),...userFeedback.map(item=>item.created_at)]),inventoryLots:owned.filter(record=>record.kind==="inventory").length,smokesLogged:owned.filter(record=>record.kind==="smokes").length,inventoryActivities:owned.filter(record=>record.kind==="activities").length,openFeedback:open.length,urgentFeedback:urgent.length,recordedFailures,unresolvedFailures,recoveredFailures,state,reasons,recent,recoveryQueue};
  }).sort((a,b)=>a.state===b.state?(b.lastActivityAt||"").localeCompare(a.lastActivityAt||""):a.state==="Needs attention"?-1:1);
  return{generatedAt:new Date().toISOString(),summary:{testers:testers.length,active:testers.filter(item=>item.lastActivityAt).length,needsAttention:testers.filter(item=>item.state==="Needs attention").length,inventoryLots:testers.reduce((sum,item)=>sum+item.inventoryLots,0),smokes:testers.reduce((sum,item)=>sum+item.smokesLogged,0),openFeedback:testers.reduce((sum,item)=>sum+item.openFeedback,0),recordedFailures:testers.reduce((sum,item)=>sum+item.recordedFailures,0),unresolvedFailures:testers.reduce((sum,item)=>sum+item.unresolvedFailures,0),recoveredFailures:testers.reduce((sum,item)=>sum+item.recoveredFailures,0)},testers};
}
