import { z } from "zod";
import type { InventoryItem, SmokingLog } from "./types";
import { responseOutputText } from "./cigar-vision";

export const CigarSommQuestionSchema=z.object({question:z.string().trim().min(3).max(1000),inventoryId:z.string().trim().max(100).optional(),occasion:z.string().trim().max(120).optional(),includeAlcohol:z.boolean().default(true)}).strict();
const Pairing=z.object({name:z.string(),style:z.string(),why:z.string(),service:z.string()});
const ResearchSource=z.object({title:z.string(),url:z.string().url(),publisher:z.string(),supports:z.string()});
export const CigarSommAnswerSchema=z.object({answer:z.string(),cigarContext:z.string(),confidence:z.enum(["High","Medium","Developing"]),basis:z.array(z.string()).max(6),coffee:z.array(Pairing).max(3),spirits:z.array(Pairing).max(3),cocktails:z.array(Pairing).max(3),nonAlcoholic:z.array(Pairing).max(3),sources:z.array(ResearchSource).max(8),cautions:z.array(z.string()).max(4)});
export type CigarSommAnswer=z.infer<typeof CigarSommAnswerSchema>;
const pairingJson={type:"array",maxItems:3,items:{type:"object",additionalProperties:false,properties:{name:{type:"string"},style:{type:"string"},why:{type:"string"},service:{type:"string"}},required:["name","style","why","service"]}} as const;
export const cigarSommJsonSchema={type:"object",additionalProperties:false,properties:{answer:{type:"string"},cigarContext:{type:"string"},confidence:{type:"string",enum:["High","Medium","Developing"]},basis:{type:"array",maxItems:6,items:{type:"string"}},coffee:pairingJson,spirits:pairingJson,cocktails:pairingJson,nonAlcoholic:pairingJson,sources:{type:"array",maxItems:8,items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},url:{type:"string"},publisher:{type:"string"},supports:{type:"string"}},required:["title","url","publisher","supports"]}},cautions:{type:"array",maxItems:4,items:{type:"string"}}},required:["answer","cigarContext","confidence","basis","coffee","spirits","cocktails","nonAlcoholic","sources","cautions"]} as const;

export async function askCigarSomm(input:z.infer<typeof CigarSommQuestionSchema>,inventory:InventoryItem[],smokes:SmokingLog[]){const apiKey=process.env.OPENAI_API_KEY?.trim();if(!apiKey)throw new Error("Cigar Somm is not configured");const item=input.inventoryId?inventory.find(value=>value.inventoryId===input.inventoryId):undefined;const tastings=item?smokes.filter(value=>value.inventoryId===item.inventoryId).slice(-5):[];const context=item?{inventoryId:item.inventoryId,brand:item.brand,line:item.line,vitola:item.vitola,vintage:item.vintage,quantity:item.currentQty,status:item.status,personalScore:item.score,notes:item.notes,tastings:tastings.map(value=>({overall:value.overall,strength:value.strength,sweetness:value.sweetness,flavor:value.flavor,notes:value.tastingNotes,buyAgain:value.buyAgain}))}:undefined;const prompt=`You are Cigar Somm, Cigar Vault's premium cigar advisor. Answer the collector's question using their supplied inventory and tasting context when available. Be refined, concise, useful, and candid about uncertainty.

PAIRING KNOWLEDGE STANDARD:
- Use web research for the exact cigar, brand, blend, vitola, beverage category, spirit style, or cocktail when it would materially improve the answer. Do not present model memory as researched fact.
- Source priority for cigars: official manufacturer and importer pages; then established cigar-industry publications and documented professional reviews. Source priority for beverages: official producer and appellation or regulatory references; then recognized beverage education, distilling, coffee, tea, and cocktail references.
- Separate product facts from pairing judgment. Never copy marketing language as objective tasting fact.
- Cite only direct pages actually used and state what each supports. If reliable exact-product evidence is unavailable, lower confidence and say so.
- Match beverage intensity to cigar body first; then use flavor bridges or deliberate contrast.
- Coffee: consider roast level, origin/process, acidity, milk, extraction, temperature, and sweetness. Avoid claiming one origin is universally correct.
- Spirits: consider proof, oak, sweetness, smoke, fruit, oxidation, and serving dilution. Bourbon/rye, aged rum, Scotch, Irish whiskey, Cognac/Armagnac, brandy, tequila/mezcal, and fortified-wine styles may fit, but recommend only what serves the cigar.
- Cocktails are separate from neat spirits. Consider base spirit, modifiers, sugar, bitterness, acidity, dilution, ice, garnish, and aromatic intensity. Prefer established cocktail styles and prevent an overly sweet, sour, smoky, or high-proof drink from overwhelming the cigar.
- Nonalcoholic: treat this as a first-class category. Consider espresso or decaf, tea, cacao, sparkling mineral water, tonic, ginger, verjus, shrubs, and zero-proof drinks. Protect the palate from excessive sugar or acidity.
- Give specific styles, not invented product endorsements. Explain temperature, dilution, glassware, or sweetness when useful.
- Never make health claims. Alcohol is only for adults of legal drinking age; recommend moderation and omit both spirits and cocktails entirely when includeAlcohol is false.
- Cigar age and readiness claims must be conservative. Ownership alone does not prove flavor. Distinguish known tasting evidence from general pairing principles.

Collector question: ${JSON.stringify(input.question)}
Occasion: ${JSON.stringify(input.occasion||"not specified")}
Include alcoholic pairings: ${input.includeAlcohol}
Selected cigar context: ${JSON.stringify(context||"none selected")}`;const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_SOMM_MODEL?.trim()||"gpt-5-mini",reasoning:{effort:"low"},store:false,max_output_tokens:3000,tools:[{type:"web_search"}],include:["web_search_call.action.sources"],input:prompt,text:{format:{type:"json_schema",name:"cigar_somm_answer",strict:true,schema:cigarSommJsonSchema}}}),signal:AbortSignal.timeout(90_000)});const payload=await response.json();if(!response.ok)throw new Error((payload as{error?:{message?:string}}).error?.message||`OpenAI request failed (${response.status})`);const text=responseOutputText(payload);if(!text)throw new Error("Cigar Somm returned no answer");return CigarSommAnswerSchema.parse(JSON.parse(text))}
