import { z } from "zod";
import type { InventoryItem, ProfessionalRating } from "./types";
import { responseOutputText } from "./cigar-vision";

export const ProfessionalRatingSchema = z.object({ ratingId:z.string().trim().min(1), inventoryId:z.string().trim().min(1), publication:z.string().trim().min(1), score:z.coerce.number().min(50).max(100), reviewDate:z.string().trim().optional(), reviewer:z.string().trim().optional(), sourceUrl:z.string().url(), matchConfidence:z.enum(["High","Medium","Low"]), matchedVintage:z.union([z.string(),z.number()]).optional(), summary:z.string().trim().max(1000).optional(), createdAt:z.string().datetime() });
export const RatingResearchSchema = z.object({ ratings:z.array(z.object({ publication:z.string(), score:z.number().min(50).max(100), reviewDate:z.string(), reviewer:z.string(), sourceUrl:z.string().url(), matchConfidence:z.enum(["High","Medium","Low"]), matchedVintage:z.union([z.string(),z.number()]).nullable(), summary:z.string() })).max(8), notes:z.string() });
export type RatingResearch = z.infer<typeof RatingResearchSchema>;
const researchSchema={type:"object",additionalProperties:false,properties:{ratings:{type:"array",maxItems:8,items:{type:"object",additionalProperties:false,properties:{publication:{type:"string"},score:{type:"number",minimum:50,maximum:100},reviewDate:{type:"string"},reviewer:{type:"string"},sourceUrl:{type:"string"},matchConfidence:{type:"string",enum:["High","Medium","Low"]},matchedVintage:{type:["string","number","null"]},summary:{type:"string"}},required:["publication","score","reviewDate","reviewer","sourceUrl","matchConfidence","matchedVintage","summary"]}},notes:{type:"string"}},required:["ratings","notes"]} as const;
export function ratingsForInventory(ratings:ProfessionalRating[],inventoryId:string){return ratings.filter(rating=>rating.inventoryId===inventoryId).sort((a,b)=>b.score-a.score)}
export function ratingSummary(ratings:ProfessionalRating[],inventoryId:string){const matches=ratingsForInventory(ratings,inventoryId);return{count:matches.length,highest:matches[0]?.score,average:matches.length?Math.round(matches.reduce((sum,rating)=>sum+rating.score,0)/matches.length*10)/10:undefined,publications:new Set(matches.map(rating=>rating.publication)).size}}
export async function researchCigarRatings(item:InventoryItem){const apiKey=process.env.OPENAI_API_KEY?.trim();if(!apiKey)throw new Error("Professional rating research is not configured");const prompt=`Find published professional review scores for this exact premium cigar: brand ${item.brand}; line ${item.line}; vitola ${item.vitola}; release or vintage ${item.vintage??"unknown"}. Search rating publishers and established cigar publications such as Cigar Aficionado, Cigar Journal, halfwheel, Blind Man's Puff, and comparable editorial sources. Include a result only when the source page directly supports a numeric score and the brand, line, and vitola match. Mark High confidence only when all identity fields and any stated vintage match; Medium when the exact cigar matches but vintage is unspecified; Low when the source may describe a nearby size or release. Do not treat retailer customer ratings, star ratings, forum posts, search snippets without a source page, or collection-level ratings as professional scores. Summarize each review in original words without copying review text. Use the canonical direct source URL. Return an empty ratings array when no defensible exact rating is found.`;const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_VISION_MODEL?.trim()||"gpt-5.6-terra",reasoning:{effort:"medium"},store:false,max_output_tokens:3200,tools:[{type:"web_search"}],include:["web_search_call.action.sources"],input:prompt,text:{format:{type:"json_schema",name:"professional_rating_research",strict:true,schema:researchSchema}}}),signal:AbortSignal.timeout(100_000)});const payload=await response.json();if(!response.ok)throw new Error((payload as {error?:{message?:string}}).error?.message||`OpenAI request failed (${response.status})`);const text=responseOutputText(payload);if(!text)throw new Error("Research returned no rating results");return RatingResearchSchema.parse(JSON.parse(text))}
