import { z } from "zod";
import { cigarIdentityKey } from "./cigar-identity";

export const CommunityPostInput=z.object({displayName:z.string().trim().min(2).max(40),category:z.enum(["General","Cigar discussion","Collection care","Humidors","Events"]),title:z.string().trim().min(4).max(120),body:z.string().trim().min(10).max(4000)}).strict();
export const CommunityRatingInput=z.object({displayName:z.string().trim().min(2).max(40),brand:z.string().trim().min(2).max(100),line:z.string().trim().min(1).max(150),vitola:z.string().trim().min(1).max(120),vintage:z.union([z.string().trim().max(20),z.number()]).optional(),score:z.coerce.number().int().min(1).max(100),review:z.string().trim().max(1200).optional()}).strict();
export type CommunityPost=z.infer<typeof CommunityPostInput>&{id:string;createdAt:string;status:"active"|"review"|"hidden";moderationReason?:string};
export type CommunityRating=z.infer<typeof CommunityRatingInput>&{id:string;createdAt:string;status:"active"|"review"|"hidden";cigarKey:string;userId?:string};
export type CommunityRanking={rank:number;cigarKey:string;brand:string;line:string;vitola:string;vintage?:string|number;averageScore:number;ratingCount:number};

export function communityCigarKey(value:Pick<CommunityRating,"brand"|"line"|"vitola"|"vintage">){return cigarIdentityKey(value)}
export function communityTop25(ratings:CommunityRating[]):CommunityRanking[]{const groups=new Map<string,CommunityRating[]>();for(const rating of ratings.filter(value=>value.status==="active")){const key=communityCigarKey(rating);groups.set(key,[...(groups.get(key)||[]),rating])}return[...groups.entries()].map(([cigarKey,values])=>{const first=values[0];return{rank:0,cigarKey,brand:first.brand,line:first.line,vitola:first.vitola,vintage:first.vintage,averageScore:Math.round(values.reduce((sum,value)=>sum+value.score,0)/values.length*10)/10,ratingCount:values.length}}).sort((a,b)=>b.averageScore-a.averageScore||b.ratingCount-a.ratingCount||a.brand.localeCompare(b.brand)).slice(0,25).map((value,index)=>({...value,rank:index+1}))}

export type ModerationDecision={decision:"allow"|"review"|"block";reason:string};
export function baselineCommunityModeration(text:string):ModerationDecision{const normalized=text.toLowerCase();if(/\b(buy|sell|venmo|cashapp|paypal|ship(?:ping)? to|price shipped|dm me)\b/.test(normalized))return{decision:"block",reason:"Buying, selling, and transaction arrangements are not allowed in the community."};if(/\b(kill yourself|racial slur|doxx|home address)\b/.test(normalized))return{decision:"block",reason:"Threatening, hateful, or personally identifying content is not allowed."};if(/https?:\/\/|\b(?:email|phone|text me)\b/.test(normalized))return{decision:"review",reason:"External links or contact details require administrator review."};return{decision:"allow",reason:"Passed community safety rules."}}
