import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import { responseOutputText } from "./cigar-vision";

export const knowledgeCategories=["cigar","spirit","cocktail","coffee","tea","nonalcoholic","pairing"] as const;
export const SommelierKnowledgeSchema=z.object({knowledgeId:z.string(),category:z.enum(knowledgeCategories),subject:z.string(),factType:z.string(),statement:z.string(),pairingImplications:z.string(),sourceTitle:z.string(),sourceUrl:z.string().url(),publisher:z.string(),evidenceDate:z.string(),confidence:z.enum(["High","Medium","Developing"]),status:z.enum(["review","approved","rejected"]),researchedAt:z.string(),reviewedAt:z.string().optional(),reviewNote:z.string().optional()});
export type SommelierKnowledge=z.infer<typeof SommelierKnowledgeSchema>;
const Candidate=z.object({category:z.enum(knowledgeCategories),subject:z.string(),factType:z.string(),statement:z.string(),pairingImplications:z.string(),sourceTitle:z.string(),sourceUrl:z.string().url(),publisher:z.string(),evidenceDate:z.string(),confidence:z.enum(["High","Medium","Developing"])});
const Research=z.object({records:z.array(Candidate).max(12)});
const researchJson={type:"object",additionalProperties:false,properties:{records:{type:"array",maxItems:12,items:{type:"object",additionalProperties:false,properties:{category:{type:"string",enum:knowledgeCategories},subject:{type:"string"},factType:{type:"string"},statement:{type:"string"},pairingImplications:{type:"string"},sourceTitle:{type:"string"},sourceUrl:{type:"string"},publisher:{type:"string"},evidenceDate:{type:"string"},confidence:{type:"string",enum:["High","Medium","Developing"]}},required:["category","subject","factType","statement","pairingImplications","sourceTitle","sourceUrl","publisher","evidenceDate","confidence"]}}},required:["records"]} as const;

function admin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim(),key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)return undefined;return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function idFor(value:Pick<z.infer<typeof Candidate>,"category"|"subject"|"statement">){let hash=2166136261;for(const char of `${value.category}|${value.subject}|${value.statement}`.toLowerCase()){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}return `SOMM-${(hash>>>0).toString(16).toUpperCase().padStart(8,"0")}`}
const fromRow=(row:Record<string,unknown>)=>SommelierKnowledgeSchema.parse({knowledgeId:row.knowledge_id,category:row.category,subject:row.subject,factType:row.fact_type,statement:row.statement,pairingImplications:row.pairing_implications,sourceTitle:row.source_title,sourceUrl:row.source_url,publisher:row.publisher,evidenceDate:row.evidence_date,confidence:row.confidence,status:row.status,researchedAt:row.researched_at,reviewedAt:row.reviewed_at||undefined,reviewNote:row.review_note||undefined});
export async function loadKnowledge(status:"review"|"approved"|"rejected"="approved"){const client=admin();if(!client)return[];const{data,error}=await client.from("sommelier_knowledge").select("*").eq("status",status).order("researched_at",{ascending:false}).limit(500);if(error){if(error.code==="42P01")return[];throw error}return(data||[]).map(row=>fromRow(row))}
export function relevantKnowledge(query:string,records:SommelierKnowledge[],limit=16){const words=[...new Set(query.toLowerCase().split(/[^a-z0-9]+/).filter(word=>word.length>2))];return records.map(record=>({record,score:words.reduce((sum,word)=>sum+(`${record.subject} ${record.factType} ${record.statement} ${record.pairingImplications}`.toLowerCase().includes(word)?1:0),0)})).filter(row=>row.score>0).sort((a,b)=>b.score-a.score||b.record.confidence.localeCompare(a.record.confidence)).slice(0,limit).map(row=>row.record)}
export async function researchSommelierKnowledge(category:typeof knowledgeCategories[number]){const apiKey=process.env.OPENAI_API_KEY?.trim();if(!apiKey)throw new Error("Sommelier research is not configured");const today=new Date().toISOString().slice(0,10);const prompt=`Today is ${today}. Research durable, decision-useful ${category} knowledge for a premium cigar master sommelier library. Find up to 12 discrete facts from direct authoritative pages. For cigars prioritize official manufacturers/importers and established cigar publications. For spirits prioritize official producers, appellations and regulators. For cocktails prioritize recognized historical or professional references. For coffee, tea, and nonalcoholic drinks prioritize producers, trade bodies, and respected education sources. Each record must state one verifiable fact, distinguish fact from pairing judgment, provide the direct source URL and evidence date, and explain pairing implications conservatively. Exclude retailer marketing claims, copied listicles, unsupported tasting certainty, health claims, and generic facts without a useful named subject. Return only category ${category}.`;
 const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_SOMM_RESEARCH_MODEL?.trim()||"gpt-5.6-terra",reasoning:{effort:"medium"},store:false,max_output_tokens:5000,tools:[{type:"web_search"}],include:["web_search_call.action.sources"],input:prompt,text:{format:{type:"json_schema",name:"sommelier_knowledge",strict:true,schema:researchJson}}}),signal:AbortSignal.timeout(110_000)});const payload=await response.json();if(!response.ok)throw new Error((payload as{error?:{message?:string}}).error?.message||`Research failed (${response.status})`);const output=responseOutputText(payload);if(!output)throw new Error("Sommelier research returned no records");const records=Research.parse(JSON.parse(output)).records;const client=admin();if(!client)throw new Error("Sommelier library database is not configured");const rows=records.map(record=>({knowledge_id:idFor(record),category:record.category,subject:record.subject,fact_type:record.factType,statement:record.statement,pairing_implications:record.pairingImplications,source_title:record.sourceTitle,source_url:record.sourceUrl,publisher:record.publisher,evidence_date:record.evidenceDate,confidence:record.confidence,status:"review",researched_at:new Date().toISOString()}));const{error}=await client.from("sommelier_knowledge").upsert(rows,{onConflict:"knowledge_id",ignoreDuplicates:true});if(error)throw error;return{category,found:records.length,queued:rows.length}}
export async function reviewKnowledge(knowledgeId:string,status:"approved"|"rejected",note?:string){const client=admin();if(!client)throw new Error("Sommelier library database is not configured");const{data,error}=await client.from("sommelier_knowledge").update({status,reviewed_at:new Date().toISOString(),review_note:note||null}).eq("knowledge_id",knowledgeId).select("*").single();if(error)throw error;return fromRow(data)}
