import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import { authorizeWrite } from "@/lib/config";

function admin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim(),key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();if(!url||!key)throw new Error("AI Administrator requires Supabase service credentials");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
const Update=z.object({kind:z.enum(["post","rating"]),id:z.uuid(),status:z.enum(["active","hidden"])}).strict();
export async function GET(request:Request){if(!authorizeWrite(request))return NextResponse.json({error:"Founder authorization required"},{status:401});try{const client=admin();const[posts,ratings,profiles,events]=await Promise.all([client.from("community_posts").select("*").order("created_at",{ascending:false}).limit(100),client.from("community_ratings").select("*").order("created_at",{ascending:false}).limit(100),client.from("profiles").select("user_id"),client.from("product_events").select("event_type,created_at").gte("created_at",new Date(Date.now()-30*86_400_000).toISOString()).limit(5000)]);if(posts.error||ratings.error||profiles.error)throw posts.error||ratings.error||profiles.error;const queue=[...(posts.data||[]).filter(row=>row.status==="review").map(row=>({kind:"post",id:row.id,label:row.title,detail:row.body,displayName:row.display_name,reason:row.moderation_reason,createdAt:row.created_at})),...(ratings.data||[]).filter(row=>row.status==="review").map(row=>({kind:"rating",id:row.id,label:`${row.brand} ${row.line} ${row.vitola} — ${row.score}`,detail:row.review||"No written review",displayName:row.display_name,reason:row.moderation_reason,createdAt:row.created_at}))].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return NextResponse.json({data:{summary:{collectors:(profiles.data||[]).length,activePosts:(posts.data||[]).filter(row=>row.status==="active").length,activeRatings:(ratings.data||[]).filter(row=>row.status==="active").length,pendingReview:queue.length,events30Days:(events.error?[]:events.data||[]).length},queue}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Administrator dashboard unavailable"},{status:502})}}
export async function PATCH(request:Request){if(!authorizeWrite(request))return NextResponse.json({error:"Founder authorization required"},{status:401});try{const input=Update.parse(await request.json());const table=input.kind==="post"?"community_posts":"community_ratings";const{error}=await admin().from(table).update({status:input.status,moderation_reason:`Founder marked ${input.status}`,updated_at:new Date().toISOString()}).eq("id",input.id);if(error)throw error;return NextResponse.json({data:{...input}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Moderation update failed"},{status:422})}}
