import type { Metadata } from "next";
import { cedrivaPrinciples } from "@/lib/cedriva-constitution";
export const metadata:Metadata={title:"The Cedriva Constitution",description:"Cedriva’s purpose, commitments, and promise to premium cigar culture."};
const commitments=[
  ["New collectors","Every expert was once a beginner. Questions are welcomed, learning is celebrated, and every collector deserves to belong from day one."],
  ["Experienced collectors","Experience deserves respect. Cedriva amplifies expertise with advanced tools worthy of the world’s finest collections."],
  ["The industry","Manufacturers, retailers, lounges, media, factories, and collectors are partners. Cedriva succeeds only when the ecosystem succeeds."],
  ["Truth","History, information, and authenticity matter. We state uncertainty, correct mistakes, and earn trust through honesty—not perfection."],
  ["Innovation","Technology should remove barriers without replacing the rituals and traditions that make premium cigars meaningful."],
] as const;
export default function ConstitutionPage(){return <main className="shell constitutionPage"><section className="constitutionHero"><div className="eyebrow">The Cedriva Constitution · Version 1.0</div><h1>A tradition worth preserving. A culture worth growing.</h1><p className="lede">Cedriva exists to preserve, honor, and grow the culture of premium cigars—and to help every collection preserve the people, memories, milestones, and craftsmanship within it.</p><span>Brian Bowers · Founder</span></section><section className="constitutionPurpose"><div><div className="eyebrow">Our purpose</div><h2>We are not simply building software.</h2></div><p>Every cigar reflects generations of farmers, blenders, rollers, factory teams, distributors, retailers, and collectors. Our responsibility is to strengthen that tradition for the generations that follow.</p></section><section className="section"><div className="sectionHead"><div><div className="eyebrow">Our responsibility</div><h2>Four questions govern every decision.</h2></div></div><div className="constitutionQuestions">{cedrivaPrinciples.map((item,index)=><article key={item.question}><span>0{index+1}</span><h3>{item.question}</h3><p>{item.commitment}</p></article>)}</div></section><section className="section"><div className="sectionHead"><div><div className="eyebrow">Our commitments</div><h2>Build for the whole culture.</h2></div></div><div className="constitutionCommitments">{commitments.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section><section className="constitutionLegacy"><div className="eyebrow">Our legacy</div><h2>Success is larger than downloads, revenue, or valuations.</h2><p>We succeed when collectors know more, manufacturers are better represented, retailers are stronger, cigar history is better preserved, and future generations fall in love with the culture.</p><blockquote>We will never stop learning. We will never stop improving. We will never stop listening.</blockquote><a className="button" href="/">Enter Cedriva</a></section></main>}
