import assert from"node:assert/strict";import test from"node:test";import{advancedBetaStage,betaAppUrl,betaInvitationEmail,betaInvitationMailto,betaInvitationWebmailLinks,betaReinstallEmail,betaReinstallWebmailLinks,betaSignupUrl,betaSummary,type BetaCollector}from"../lib/beta-onboarding";
const item=(stage:BetaCollector["stage"],id:string):BetaCollector=>({id,name:id,email:`${id}@example.com`,stage,createdAt:"2026-07-21",updatedAt:"2026-07-21"});
test("summarizes the founder beta pipeline and remaining seats",()=>{const result=betaSummary([item("Prospect","a"),item("Invited","b"),item("Imported","c"),item("Activated","d")]);assert.equal(result.total,4);assert.equal(result.activated,1);assert.equal(result.founderSeatsRemaining,22)});
test("founder seats never become negative",()=>{assert.equal(betaSummary(Array.from({length:30},(_,i)=>item("Activated",String(i)))).founderSeatsRemaining,0)});
test("account signals advance but never regress onboarding",()=>{assert.equal(advancedBetaStage("Invited",{signedUp:true,inventoryLots:0,activated:false}),"Signed up");assert.equal(advancedBetaStage("Signed up",{signedUp:true,inventoryLots:4,activated:false}),"Imported");assert.equal(advancedBetaStage("Activated",{signedUp:true,inventoryLots:1,activated:false}),"Activated")});
test("beta invitation email includes the canonical signup link and exact invited address",()=>{const link=betaInvitationMailto({name:"Cristian Verme",email:"cristianverme@yahoo.com"});const params=new URL(link).searchParams;const body=params.get("body")||"";assert.equal(betaSignupUrl,"https://hojavia.com/login?mode=signup");assert.match(params.get("subject")||"",/Hojavía private beta invitation/);assert.match(body,/Hi Cristian Verme,/);assert.match(body,/https:\/\/hojavia\.com\/login\?mode=signup/);assert.match(body,/Use this exact invited email address: cristianverme@yahoo\.com/);assert.match(body,/https:\/\/hojavia\.com\/beta-agreement/);});
test("beta invitation content can be previewed and copied without a mail app",()=>{const email=betaInvitationEmail({name:"Cristian Verme",email:"cristianverme@yahoo.com"});assert.equal(email.recipient,"cristianverme@yahoo.com");assert.match(email.subject,/private beta invitation/);assert.match(email.body,/Create your account: https:\/\/hojavia\.com\/login\?mode=signup/);assert.match(email.body,/open the confirmation email and follow its link before signing in/);});
test("beta invitation opens in supported webmail composers",()=>{const links=betaInvitationWebmailLinks({name:"Cristian Verme",email:"cristianverme@yahoo.com"});for(const link of Object.values(links)){const url=new URL(link);assert.match(url.searchParams.get("to")||"",/cristianverme@yahoo\.com/);assert.match(url.searchParams.get("body")||"",/https:\/\/hojavia\.com\/login\?mode=signup/)}assert.equal(new URL(links.gmail).searchParams.get("su"),"Your Hojavía private beta invitation");assert.equal(new URL(links.outlook).searchParams.get("subject"),"Your Hojavía private beta invitation");});
test("beta reinstall email always uses the permanent public app address",()=>{const collector={name:"Cristian Verme",email:"cristianverme@yahoo.com"};const email=betaReinstallEmail(collector,"http://192.168.1.104:3102");assert.equal(email.recipient,"cristianverme@yahoo.com");assert.equal(email.replacementUrl,betaAppUrl);assert.match(email.subject,/Hojavía phone-app reinstall/);assert.match(email.body,/Hi Cristian Verme,/);assert.match(email.body,/192\.168\.1\.104:3102/);assert.match(email.body,/https:\/\/hojavia\.com\/\?source=hojavia-app/);assert.match(email.body,/No special Wi-Fi connection is required/);assert.doesNotMatch(email.body,/different local address/);assert.match(email.body,/will not delete collection records/);for(const link of Object.values(betaReinstallWebmailLinks(collector,"http://192.168.1.104:3102")))assert.match(new URL(link).searchParams.get("body")||"",/https:\/\/hojavia\.com/)});
