import assert from "node:assert/strict";
import test from "node:test";
import { buildCigarLineage, cigarTradition } from "../lib/cigar-lineage";
import { CollectorPassportInput, collectorPassportSuggestions } from "../lib/collector-passport";
import { buildLeafFeed } from "../lib/leaf-feed";
import { exactMarketMovement } from "../lib/market-movement";
import { communityExperienceProfiles, type CommunityRating } from "../lib/community";
import type { CatalogCigar, InventoryItem } from "../lib/types";

const lot={inventoryId:"I1",brand:"Cohiba",line:"Siglo VI",vitola:"Cañonazo",vintage:"2020",currentQty:5,retailValue:70} satisfies InventoryItem;
test("market movement requires dated exact observations and preserves source count",()=>{const movement=exactMarketMovement([{valuationId:"V1",inventoryId:"I1",valuationDate:"2025-01-01",marketValue:100,sourceUrl:"https://one.example"},{valuationId:"V2",inventoryId:"I1",valuationDate:"2026-01-01",marketValue:120,sourceUrl:"https://two.example"}]);assert.equal(movement.direction,"Up");assert.equal(movement.changePercent,20);assert.equal(movement.sourceCount,2);assert.equal(movement.confidence,"Documented")});
test("experience profiles keep optional dimensions unknown",()=>{const ratings=[{id:"R1",userId:"U1",displayName:"A",cigarKey:"x",brand:"Cohiba",line:"Siglo VI",vitola:"Cañonazo",tradition:"Habanos",score:94,constructionScore:91,buyAgain:true,status:"active",createdAt:"2026-01-01"},{id:"R2",userId:"U2",displayName:"B",cigarKey:"x",brand:"Cohiba",line:"Siglo VI",vitola:"Cañonazo",tradition:"Habanos",score:92,constructionScore:89,buyAgain:false,status:"active",createdAt:"2026-01-02"}] as CommunityRating[];const profile=communityExperienceProfiles(ratings)[0];assert.equal(profile.overall,93);assert.equal(profile.dimensions.construction,90);assert.equal(profile.dimensions.flavor,undefined);assert.equal(profile.buyAgainRate,50)});
test("lineage applies separate Habanos and New World identity rules",()=>{const selected={catalogId:"C1",brand:"Cohiba",line:"Siglo VI",vitola:"Cañonazo",releaseYear:2020} satisfies CatalogCigar;const habanos=buildCigarLineage(selected,[selected,{catalogId:"C2",brand:"Cohiba",line:"Siglo VI Reserva",vitola:"Cañonazo",releaseYear:2016,edition:"Reserva"}]);assert.equal(habanos.tradition,"Habanos");assert.match(habanos.identityRule,/box or cosecha/);assert.equal(cigarTradition("Padrón"),"New World")});
test("collector passport accepts curated fields but no inventory surface",()=>{const parsed=CollectorPassportInput.parse({handle:"leaf-student",displayName:"Leaf Student",bio:"Learning through people and place.",interests:["History"],favoriteOrigins:["Habanos"],favoriteMakers:["Cohiba"],favoriteVitolas:["Cañonazo"],featuredCigars:["Cohiba Siglo VI"],visibility:"community"});assert.equal("inventory" in parsed,false);assert.equal("value" in parsed,false);const suggestions=collectorPassportSuggestions([lot],[]);assert.deepEqual(suggestions.favoriteMakers,["Cohiba"])});
test("Leaf Feed connects private signals without exposing quantity in copy",()=>{const feed=buildLeafFeed({inventory:[lot],smokes:[{smokeId:"S1",inventoryId:"I1",dateSmoked:"2026-08-01",overall:94}],valuations:[],collections:[],communityPosts:[{id:"P1",title:"Aging Cohiba",category:"Cigar discussion"}]});assert.ok(feed.some(value=>value.kind==="Journal"));assert.ok(feed.some(value=>value.kind==="Culture"));assert.doesNotMatch(feed.map(value=>value.detail).join(" "),/5 cigars|quantity/i)});
