import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
import test from"node:test";

test("Vault presents separate workspaces and preserves the global-search return journey",()=>{
 const page=readFileSync(new URL("../app/inventory/page.tsx",import.meta.url),"utf8");
 const manager=readFileSync(new URL("../components/inventory-manager.tsx",import.meta.url),"utf8");
 const audit=readFileSync(new URL("../app/collection-health/page.tsx",import.meta.url),"utf8");
 const detail=readFileSync(new URL("../app/inventory/[inventoryId]/page.tsx",import.meta.url),"utf8");
 const globalSearch=readFileSync(new URL("../components/global-search.tsx",import.meta.url),"utf8");
 const story=readFileSync(new URL("../app/cigars/[identityId]/page.tsx",import.meta.url),"utf8");
 assert.match(page,/Browse Vault/);
 assert.match(page,/initialItems=\{cigarItems\}/);
 assert.match(page,/presentationAssetCount/);
 assert.match(page,/tracked separately/);
 assert.match(page,/Open Valuable Collections/);
 assert.match(manager,/setItems\(cigarInventoryRecords\(result\.data,collections\)\)/);
 assert.match(page,/href="#inventory-records"/);
 assert.match(page,/Audit My Inventory/);
 assert.match(page,/href="\/collection-health"/);
 assert.match(page,/href="\/collections"/);
 assert.match(page,/Valuable Collections/);
 assert.match(manager,/id="inventory-records"/);
 assert.match(manager,/aria-label="Inventory records and filters"/);
 assert.match(audit,/Audit my inventory/);
 assert.match(audit,/Physical quantity/);
 assert.match(audit,/Production year/);
 assert.match(audit,/Replacement value/);
 assert.match(audit,/Storage location/);
 assert.match(audit,/Provenance/);
 assert.match(audit,/Membership truth/);
 assert.match(audit,/missing=\$\{check\.key\}&active=1#inventory-records/);
 assert.match(audit,/missing=\$\{gap\.key\}&active=1&inventoryId=\$\{encodeURIComponent\(item\.inventoryId\)\}#inventory-records/);
 assert.match(audit,/Active inventory audit complete/);
 assert.match(page,/initialActiveOnly=\{filters\.active === "1"\}/);
 assert.match(page,/initialQuery=\{filters\.vaultSearch\}/);
 assert.match(page,/initialEditId=\{filters\.edit\}/);
 assert.match(manager,/!initialActiveOnly \|\| \(item\.currentQty \?\? 0\) > 0/);
 assert.match(manager,/missing==="storage".*Add storage location/);
 assert.match(manager,/missing==="provenance".*Add provenance/);
 assert.match(manager,/textarea name="provenanceNotes"/);
 assert.match(manager,/select name="packaging"/);
 assert.match(manager,/Choose the packaging type/);
 assert.match(manager,/Presentation humidor \/ case/);
 assert.match(page,/"packaging"/);
 assert.match(story,/focus=packaging#inventory-editor/);
 assert.match(story,/"Add packaging"/);
 assert.doesNotMatch(page,/Confirm my collection/);
 assert.match(detail,/className="button secondary detailReturnLink"/);
 assert.match(detail,/Back to search results/);
 assert.match(detail,/Back to Vault/);
 assert.match(detail,/>Edit story<\/Link>/);
 assert.match(detail,/>Edit all details<\/Link>/);
 assert.match(detail,/focus=provenance#inventory-editor/);
 assert.match(detail,/vaultSearch=\$\{encodeURIComponent\(inventoryId\)\}/);
 assert.match(manager,/id="inventory-editor"/);
 assert.match(manager,/initialQuery\|\|requestedItem\?\.inventoryId/);
 assert.match(globalSearch,/buildSearchResultHref/);
 assert.match(globalSearch,/aria-label="Recent searches"/);
 assert.match(globalSearch,/Saved only in this browser profile—not to your account/);
});
