import { requestPasswordReset, signIn, signUp } from "./actions";
import "./login.css";

export const dynamic = "force-dynamic";
export default async function LoginPage({ searchParams }: { searchParams: Promise<{ mode?: string; error?: string; notice?: string; next?: string }> }) {
  const params = await searchParams;
  const signup = params.mode === "signup";
  const forgot = params.mode === "forgot";
  return <main className="loginShell"><section className="loginStory"><a className="appBrand" href="/"><span className="appBrandMark">CV</span><span><strong>Cigar Vault</strong><small>Collector intelligence</small></span></a><div><div className="eyebrow">Your collection. Privately protected.</div><h1>Every cigar, value, and humidor in one secure vault.</h1><p className="lede">Build an accurate collection record, preserve provenance, monitor storage, and understand replacement value.</p></div><small>Private accounts · Owner-controlled records · Climate intelligence</small></section><section className="loginPanel"><div><div className="eyebrow">{forgot ? "Account recovery" : signup ? "Create your vault" : "Welcome back"}</div><h2>{forgot ? "Reset your password" : signup ? "Start your collection" : "Sign in to Cigar Vault"}</h2><p>{forgot ? "Enter your email and we’ll send you a secure reset link." : signup ? "Your collection will be private to your account." : "Access your inventory, values, and storage records."}</p></div>{params.error&&<div className="loginMessage error">{params.error}</div>}{params.notice&&<div className="loginMessage">{params.notice}</div>}<form action={forgot ? requestPasswordReset : signup ? signUp : signIn}>{signup&&<label><span>Name</span><input name="fullName" autoComplete="name" required/></label>}<label><span>Email</span><input name="email" type="email" autoComplete="email" required/></label>{!forgot&&<label><span>Password</span><input name="password" type="password" autoComplete={signup?"new-password":"current-password"} minLength={8} required/></label>}{!forgot&&<input type="hidden" name="next" value={params.next||"/"}/>}<button className="button">{forgot ? "Send reset link" : signup ? "Create account" : "Sign in"}</button></form>{!signup&&!forgot&&<p className="forgotLink"><a href="/login?mode=forgot">Forgot password?</a></p>}<p className="loginSwitch">{forgot ? "Remember your password?" : signup ? "Already have an account?" : "New to Cigar Vault?"} <a href={forgot||signup?"/login":"/login?mode=signup"}>{forgot||signup ? "Sign in" : "Create account"}</a></p></section></main>;
}
