import { signIn, signUp } from "./actions";
import "./login.css";

export const dynamic = "force-dynamic";
export default async function LoginPage({ searchParams }: { searchParams: Promise<{ mode?: string; error?: string; notice?: string; next?: string }> }) {
  const params = await searchParams;
  const signup = params.mode === "signup";
  return <main className="loginShell"><section className="loginStory"><a className="appBrand" href="/"><span className="appBrandMark">CV</span><span><strong>Cigar Vault</strong><small>Collector intelligence</small></span></a><div><div className="eyebrow">Your collection. Privately protected.</div><h1>Every cigar, value, and humidor in one secure vault.</h1><p className="lede">Build an accurate collection record, preserve provenance, monitor storage, and understand replacement value.</p></div><small>Private accounts · Owner-controlled records · Climate intelligence</small></section><section className="loginPanel"><div><div className="eyebrow">{signup ? "Create your vault" : "Welcome back"}</div><h2>{signup ? "Start your collection" : "Sign in to Cigar Vault"}</h2><p>{signup ? "Your collection will be private to your account." : "Access your inventory, values, and storage records."}</p></div>{params.error&&<div className="loginMessage error">{params.error}</div>}{params.notice&&<div className="loginMessage">{params.notice}</div>}<form action={signup ? signUp : signIn}>{signup&&<label><span>Name</span><input name="fullName" autoComplete="name" required/></label>}<label><span>Email</span><input name="email" type="email" autoComplete="email" required/></label><label><span>Password</span><input name="password" type="password" autoComplete={signup?"new-password":"current-password"} minLength={8} required/></label><input type="hidden" name="next" value={params.next||"/"}/><button className="button">{signup ? "Create account" : "Sign in"}</button></form><p className="loginSwitch">{signup ? "Already have an account?" : "New to Cigar Vault?"} <a href={signup?"/login":"/login?mode=signup"}>{signup ? "Sign in" : "Create account"}</a></p></section></main>;
}
