import { signIn, signUp } from "./actions";
import { PasswordRecoveryForm } from "@/components/password-recovery-form";
import { CedrivaMark } from "@/components/cedriva-mark";
import "./login.css";

export const dynamic = "force-dynamic";
export default async function LoginPage({ searchParams }: { searchParams: Promise<{ mode?: string; error?: string; notice?: string; next?: string }> }) {
  const params = await searchParams;
  const signup = params.mode === "signup";
  const forgot = params.mode === "forgot";
  return <main className="loginShell"><section className="loginStory"><a className="appBrand" href="/"><CedrivaMark/><span><strong>Cedriva</strong><small>Premium cigar culture</small></span></a><div><div className="eyebrow">A trusted home for every collector</div><h1>Your collection tells a story. Preserve it well.</h1><p className="lede">Learn with confidence, document every chapter, care for what you own, and stay connected to the culture behind every cigar.</p></div><small>Private by default · Owner-controlled records · Trustworthy intelligence</small></section><section className="loginPanel"><div><div className="eyebrow">{forgot ? "Account recovery" : signup ? "Private beta invitation" : "Welcome back"}</div><h2>{forgot ? "Reset your password" : signup ? "Create your Cedriva home" : "Sign in to Cedriva"}</h2><p>{forgot ? "Enter your email and we’ll send you a secure reset link." : signup ? "Use the email address Brian invited. Every expert was once a beginner, and your collection remains private to your account." : "Return to your collection, learning, and personal guidance."}</p></div>{params.error&&<div className="loginMessage error">{params.error}</div>}{params.notice&&<div className="loginMessage">{params.notice}</div>}{forgot?<PasswordRecoveryForm/>:<form action={signup ? signUp : signIn}>{signup&&<label><span>Name</span><input name="fullName" autoComplete="name" required/></label>}<label><span>Email</span><input name="email" type="email" autoComplete="email" required/></label><label><span>Password</span><input name="password" type="password" autoComplete={signup?"new-password":"current-password"} minLength={8} required/></label>{signup&&<fieldset className="signupConsent"><legend>Private beta agreement</legend><label><input name="ageConfirmation" type="checkbox" required/><span>I confirm I am of legal age where I live and at least 21 years old.</span></label><label><input name="termsAcceptance" type="checkbox" required/><span>I accept the <a href="/terms" target="_blank">Terms of Use</a> and <a href="/beta-agreement" target="_blank">Beta Agreement</a>.</span></label><label><input name="privacyAcceptance" type="checkbox" required/><span>I have read the <a href="/privacy" target="_blank">Privacy Notice</a>.</span></label></fieldset>}<input type="hidden" name="next" value={params.next||"/"}/><button className="button">{signup ? "Create private beta account" : "Sign in"}</button></form>}{!signup&&!forgot&&<p className="forgotLink"><a href="/recover">Forgot password?</a></p>}<p className="loginSwitch">{forgot ? "Remember your password?" : signup ? "Already have an account?" : "Invited to the beta?"} <a href={forgot||signup?"/login":"/login?mode=signup"}>{forgot||signup ? "Sign in" : "Create account"}</a></p></section></main>;
}
