"use client";
import{useMemo,useState,type FormEvent}from"react";
import type{InventoryItem}from"@/lib/types";
import type{CigarSommAnswer}from"@/lib/cigar-somm";

const prompts=["How will this cigar develop while I smoke it?","What should I pair with this cigar after dinner?","Choose a coffee and a zero-proof pairing.","Should I smoke this now or continue aging it?"];
const identity=(item:InventoryItem)=>`${item.brand} · ${item.line} · ${item.vitola}${item.vintage?` · ${item.vintage}`:""}`;

export function CigarSomm({inventory,initialInventoryId="",initialQuestion="",initialManualName=""}:{inventory:InventoryItem[];initialInventoryId?:string;initialQuestion?:string;initialManualName?:string}){
 const[source,setSource]=useState<"inventory"|"manual">(initialManualName?"manual":"inventory"),[selectedId,setSelectedId]=useState(initialInventoryId),[manualName,setManualName]=useState(initialManualName),[search,setSearch]=useState(""),[result,setResult]=useState<CigarSommAnswer>(),[question,setQuestion]=useState(initialQuestion),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const available=useMemo(()=>inventory.filter(item=>(item.currentQty??0)>0).sort((a,b)=>identity(a).localeCompare(identity(b))),[inventory]);
 const matches=useMemo(()=>{const words=search.toLowerCase().trim().split(/\s+/).filter(Boolean);return available.filter(item=>words.every(word=>identity(item).toLowerCase().includes(word))).slice(0,30)},[available,search]);
 const selected=available.find(item=>item.inventoryId===selectedId),ready=source==="inventory"?Boolean(selected):manualName.trim().length>=3;
 function chooseSource(value:"inventory"|"manual"){setSource(value);setError("");setResult(undefined)}
 async function analyze(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!ready){setError(source==="inventory"?"Choose a cigar from your vault first.":"Enter the brand, line, and cigar name.");return}const form=new FormData(event.currentTarget),request=question.trim()||"Analyze this exact cigar. Give me a conservative tasting profile, expected progression while smoking, and well-matched coffee, spirit, cocktail, and nonalcoholic pairings.";setBusy(true);setError("");setResult(undefined);try{const response=await fetch("/api/cigar-somm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:request,inventoryId:source==="inventory"?selected?.inventoryId:undefined,cigarName:source==="manual"?manualName.trim():undefined,occasion:String(form.get("occasion")||"")||undefined,includeAlcohol:form.get("includeAlcohol")==="on"})}),value=await response.json();if(!response.ok)throw new Error(value.error||"Unable to analyze this cigar");setResult(value.data)}catch(value){setError(value instanceof Error?value.message:"Unable to analyze this cigar")}finally{setBusy(false)}}
 return <>
  <section className="sommConsole"><div className="sommIdentity"><span>C</span><div><div className="eyebrow">Private collection guidance</div><h2>Choose a cigar. Get its complete profile.</h2><p>Select an owned lot or enter any cigar manually. Manual analysis does not add it to inventory.</p></div></div><div className="sommSourceTabs" role="tablist" aria-label="Cigar source"><button type="button" role="tab" aria-selected={source==="inventory"} onClick={()=>chooseSource("inventory")}>From my inventory</button><button type="button" role="tab" aria-selected={source==="manual"} onClick={()=>chooseSource("manual")}>Enter another cigar</button></div><form onSubmit={analyze}>{source==="inventory"?<><label className="sommCigarSearch"><span>Find a cigar in your vault</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search brand, line, vitola, or year"/></label><label className="sommCigarSelect"><span>Choose the exact cigar *</span><select value={selectedId} onChange={event=>setSelectedId(event.target.value)} required><option value="">Select from {available.length} owned lots</option>{matches.map(item=><option value={item.inventoryId} key={item.inventoryId}>{identity(item)}</option>)}</select></label>{selected&&<article className="selectedCigar"><div><span>Selected inventory cigar</span><strong>{selected.brand} {selected.line}</strong><small>{selected.vitola}{selected.vintage?` · ${selected.vintage}`:""} · {selected.currentQty} owned</small></div><b>Ready to analyze</b></article>}</>:<label className="manualCigar"><span>Enter the cigar *</span><input value={manualName} onChange={event=>setManualName(event.target.value)} required minLength={3} maxLength={300} placeholder="Brand, line, vitola and year if known"/><small>Example: Arturo Fuente OpusX Lost City Double Robusto 2024</small></label>}<label><span>Occasion (optional)</span><input name="occasion" placeholder="After dinner, morning coffee, celebration…"/></label><label className="sommQuestion"><span>Anything specific you want to know? (optional)</span><textarea value={question} onChange={event=>setQuestion(event.target.value)} maxLength={1000} rows={3} placeholder="Leave blank for a complete tasting and pairing analysis."/></label><label className="alcoholChoice"><input name="includeAlcohol" type="checkbox" defaultChecked/><span>Include spirits and cocktails</span></label><button className="button" disabled={busy||!ready}>{busy?"Researching this cigar…":"Analyze cigar & pairings"}</button></form><div className="sommPrompts">{prompts.map(prompt=><button type="button" onClick={()=>setQuestion(prompt)} key={prompt}>{prompt}</button>)}</div>{error&&<output className="sommError">{error}</output>}</section>
  {result&&<section className="sommAnswer"><header><div><div className="eyebrow">Cedriva AI · {result.confidence} confidence</div><h2>{result.cigarContext}</h2></div><span>AI-assisted · Source-aware</span></header><p className="sommLead">{result.answer}</p><aside className="sommPersonalization"><div><strong>{result.personalization.used?"Personalized for your collection":"General guidance"}</strong><p>{result.personalization.explanation}</p></div>{result.personalization.signals.length>0&&<div className="sommSignals">{result.personalization.signals.map(signal=><span key={signal}>{signal}</span>)}</div>}<small>Private account context is summarized for this answer and is never presented as a public source.</small></aside><section className="tastingProfile"><div><span>Body</span><strong>{result.tastingProfile.body}</strong></div><div><span>Strength</span><strong>{result.tastingProfile.strength}</strong></div><article><span>Likely tasting notes</span><p>{result.tastingProfile.coreNotes.join(" · ")}</p></article><article><span>Expected progression</span>{result.tastingProfile.development.map(note=><p key={note}>{note}</p>)}</article><small>{result.tastingProfile.evidence}</small></section><div className="pairingGrid"><Pairings title="Coffee" symbol="☕" items={result.coffee}/><Pairings title="Spirits" symbol="◒" items={result.spirits}/><Pairings title="Cocktails" symbol="◈" items={result.cocktails}/><Pairings title="Nonalcoholic" symbol="◇" items={result.nonAlcoholic}/></div><div className="sommBasis"><div><strong>Recommendation basis</strong>{result.basis.map(value=><span key={value}>{value}</span>)}</div><div><strong>Boundaries</strong>{result.cautions.map(value=><span key={value}>{value}</span>)}</div></div><div className="sommSources"><div className="eyebrow">Research sources</div>{result.sources.length?result.sources.map(source=><a href={source.url} target="_blank" rel="noreferrer" key={source.url}><strong>{source.title}</strong><span>{source.publisher} · {source.supports}</span></a>):<p>No external source was needed for this answer; recommendations use disclosed general pairing principles.</p>}</div></section>}
 </>;
}
function Pairings({title,symbol,items}:{title:string;symbol:string;items:CigarSommAnswer["coffee"]}){return <article><header><span>{symbol}</span><h3>{title}</h3></header>{items.map(item=><div key={`${item.name}-${item.style}`}><strong>{item.name}</strong><small>{item.style}</small><p>{item.why}</p><em>{item.service}</em></div>)}{!items.length&&<p className="small">Not included for this recommendation.</p>}</article>}
