"use client";
import { FormEvent,useMemo,useState } from "react";
import type { CollectionTemplate } from "@/lib/collection-templates";
import { collectionTemplates } from "@/lib/collection-templates";
import type { WebCollectionResult } from "@/lib/collection-research";
import type { CigarVisionResult } from "@/lib/cigar-vision";
import { cigarBrands } from "@/lib/brand-directory";
import { recentYearOptions } from "@/lib/year-options";
import { brand } from "@/lib/brand";

export function CollectionResearchIntake({onTemplate,onDraft}:{onTemplate:(template:CollectionTemplate)=>void;onDraft:(draft:{name:string;maker?:string;releaseYear?:string;result:WebCollectionResult})=>void}){
 const[researchBrand,setResearchBrand]=useState("");const[researchYear,setResearchYear]=useState("");const[researchQuery,setResearchQuery]=useState("");const[researching,setResearching]=useState(false);const[researchMessage,setResearchMessage]=useState("");const[webResults,setWebResults]=useState<WebCollectionResult[]>([]);const[photos,setPhotos]=useState<File[]>([]);const[identifying,setIdentifying]=useState(false);
 const catalogMatches=useMemo(()=>{const words=researchQuery.toLowerCase().trim().split(/\s+/).filter(Boolean);if(!words.length)return[];return collectionTemplates.filter(item=>(!researchYear||String(item.releaseYear||"")===researchYear)&&words.every(word=>`${item.name} ${item.maker} ${item.edition||""}`.toLowerCase().includes(word)))},[researchQuery,researchYear]);
 async function runResearch(query=researchQuery,maker=researchBrand,year=researchYear){if(query.trim().length<3)return;setResearching(true);setResearchMessage("");setWebResults([]);try{const response=await fetch(`/api/collection-research?q=${encodeURIComponent([maker,query,year].filter(Boolean).join(" "))}`);const result=await response.json();if(!response.ok)throw new Error(result.error||"Search failed");setWebResults(result.data||[]);if(!result.data?.length)setResearchMessage("No additional source was found. Review any researched match below, or add more detail.")}catch(error){setResearchMessage(error instanceof Error?error.message:"Search failed")}finally{setResearching(false)}}
 async function research(event:FormEvent<HTMLFormElement>){event.preventDefault();await runResearch()}
 async function identifyCollection(){if(!photos.length||identifying)return;setIdentifying(true);setResearchMessage("");try{const data=new FormData();photos.forEach(file=>data.append("photos",file));const response=await fetch("/api/photo-identification",{method:"POST",body:data});const result=await response.json();if(!response.ok)throw new Error(result.error||"Photo identification failed");const identified=result.data as CigarVisionResult;const query=[identified.line,identified.vitola].filter(Boolean).join(" ").trim();setResearchBrand(identified.brand||"");setResearchQuery(query);setResearchYear(identified.vintage||"");setResearchMessage(`Photo draft: ${[identified.brand,query,identified.vintage].filter(Boolean).join(" · ")}. Review the edition and exact contents before saving.`);await runResearch(query,identified.brand||"",identified.vintage||"")}catch(error){setResearchMessage(error instanceof Error?error.message:"Photo identification failed")}finally{setIdentifying(false)}}
 return <><section className="collectionPhotoIntake card" id="add-collection"><div><div className="eyebrow">Add a collection</div><h2>Photograph the box and contents card</h2><p>Include the front, color or edition markings, release card, and the card listing the cigars. {brand.name} creates a review draft and checks researched editions. Nothing is added until you review and save it.</p></div><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event=>setPhotos(Array.from(event.target.files||[]).slice(0,8))}/><div className="formActions"><button type="button" className="button" disabled={!photos.length||identifying} onClick={identifyCollection}>{identifying?"Identifying collection…":"Identify and research collection"}</button>{photos.length>0&&<small>{photos.length} photo{photos.length===1?"":"s"} selected</small>}</div></section>
 <section className="heritageBrandSearch"><label><span>Heritage brand (optional)</span><select value={researchBrand} onChange={event=>setResearchBrand(event.target.value)}><option value="">Search every heritage brand</option>{cigarBrands.filter(item=>item.segment!=="Boutique").map(item=><option key={`${item.region}-${item.name}`} value={item.name}>{item.name} · {item.region}</option>)}</select></label><label><span>Release year</span><select value={researchYear} onChange={event=>setResearchYear(event.target.value)}><option value="">Choose the documented year</option>{recentYearOptions(researchYear).map(year=><option key={year} value={year}>{year}</option>)}</select></label><p>Add the year when known so {brand.name} searches the correct edition. Confirm it before saving.</p></section>
 <section className="collectionResearch"><div><div className="eyebrow">Name-first collection research</div><h2>What collection do you own?</h2><p>Enter its name, then choose Search. Typing no longer rerenders your full Vault.</p></div><form onSubmit={research}><input type="search" value={researchQuery} onChange={event=>setResearchQuery(event.target.value)} placeholder="Try La Gran Fumada from Fuente" aria-label="Collection name"/><button className="button" disabled={researching||researchQuery.trim().length<3}>{researching?"Searching…":"Search collections"}</button></form>{researchMessage&&<output aria-live="polite">{researchMessage}</output>}{(catalogMatches.length>0||webResults.length>0)&&<div className="researchResults">{catalogMatches.map(item=><article key={item.templateId}><span className="collectionStatus complete">Researched match</span><div><strong>{item.name}</strong><small>{item.maker} · {item.releaseYear||"Year unknown"} · {item.edition}</small><p>{item.packaging} · {item.expectedCigars??item.expectedComponents} cigars</p><details><summary>Show documented contents</summary><ul>{item.requirements.map(requirement=><li key={requirement}>{requirement}</li>)}</ul></details></div><button className="button secondary" onClick={()=>onTemplate(item)}>Use this edition</button></article>)}{webResults.map(result=><article key={result.url}><span className="collectionStatus incomplete">Source to review</span><div><strong>{result.title}</strong><p>{result.summary||"Open the source to review collection details."}</p><a href={result.url} target="_blank" rel="noreferrer">Review source ↗</a></div><button className="button secondary" onClick={()=>onDraft({name:researchQuery.trim(),maker:researchBrand||result.inferred.maker,releaseYear:researchYear||(result.inferred.releaseYear?String(result.inferred.releaseYear):undefined),result})}>Use as review draft</button></article>)}</div>}</section></>;
}
