"use client";

import { FormEvent, useEffect, useState } from "react";
import { forgetFounderSessionKey, readFounderSessionKey, rememberFounderSessionKey } from "@/lib/founder-session";

type TesterStatus={id:string;name:string;email:string;stage:string;accountCreatedAt?:string;loginConfirmedAt?:string;installationConfirmedAt?:string;host?:string;version?:string;standalone?:string};

export function FounderInstallStatus(){
  const[key,setKey]=useState(""),[items,setItems]=useState<TesterStatus[]>(),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function load(next=key){setBusy(true);setMessage("");try{const response=await fetch("/api/founder-onboarding/install-status",{cache:"no-store",headers:{"x-founder-key":next}});const result=await response.json();if(!response.ok){if(response.status===401)forgetFounderSessionKey();throw new Error(result.error)}setKey(next);rememberFounderSessionKey(next);setItems(result.data)}catch(error){setMessage(error instanceof Error?error.message:"Unable to load installation status")}finally{setBusy(false)}}
  async function unlock(event:FormEvent<HTMLFormElement>){event.preventDefault();const next=String(new FormData(event.currentTarget).get("writeKey")||"");setKey(next);await load(next)}
  useEffect(()=>{const saved=readFounderSessionKey();if(saved)void load(saved)},[]);
  if(!items)return <section className="card installStatusGate"><div><div className="eyebrow">Founder access</div><h2>Open installation status</h2><p>Uses the protected Founder key and shows operational milestones only.</p></div><form onSubmit={unlock}><label><span>Founder write key</span><input type="password" name="writeKey" required/></label><button className="button" disabled={busy}>{busy?"Opening…":"Open status"}</button></form>{message&&<output>{message}</output>}</section>;
  return <><section className="installStatusHead"><div><div className="eyebrow">Founder beta operations</div><h2>{items.length} active tester{items.length===1?"":"s"}</h2><p>Account, login, and phone installation are verified independently so a signup never looks like a completed setup.</p></div><button className="button secondary" disabled={busy} onClick={()=>load()}>{busy?"Refreshing…":"Refresh"}</button></section>{message&&<output className="betaMessage">{message}</output>}<section className="testerInstallGrid">{items.map(item=><article className="card" key={item.id}><header><div><small>{item.email}</small><h3>{item.name}</h3></div><span>{item.stage}</span></header><div className="testerMilestones"><div className={item.accountCreatedAt?"ready":"attention"}><b>{item.accountCreatedAt?"✓":"!"}</b><span>Account</span><small>{item.accountCreatedAt?new Date(item.accountCreatedAt).toLocaleString():"Not created"}</small></div><div className={item.loginConfirmedAt?"ready":"attention"}><b>{item.loginConfirmedAt?"✓":"!"}</b><span>Login</span><small>{item.loginConfirmedAt?new Date(item.loginConfirmedAt).toLocaleString():"Not confirmed"}</small></div><div className={item.installationConfirmedAt?"ready":"attention"}><b>{item.installationConfirmedAt?"✓":"!"}</b><span>Phone app</span><small>{item.installationConfirmedAt?new Date(item.installationConfirmedAt).toLocaleString():"Not confirmed"}</small></div></div><p>{item.installationConfirmedAt?`${item.host||"Host unknown"} · build ${item.version||"unknown"} · ${item.standalone==="true"?"home-screen app":"browser confirmation"}`:"Send the permanent install link, then ask the tester to tap Confirm this phone."}</p></article>)}</section></>;
}
