"use client";
import{FormEvent,useMemo,useState}from"react";import{betaSummary,type BetaCollector,type BetaStage}from"@/lib/beta-onboarding";
const stages:BetaStage[]=["Prospect","Invited","Signed up","Imported","Activated"];
export function FounderOnboarding(){
 const[key,setKey]=useState("");const[items,setItems]=useState<BetaCollector[]>();const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const summary=useMemo(()=>betaSummary(items||[]),[items]);
 async function fetchItems(next=key){const response=await fetch("/api/founder-onboarding",{headers:{"x-founder-key":next}});const result=await response.json();if(!response.ok)throw new Error(result.error);setItems(result.data)}
 async function unlock(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const next=String(new FormData(e.currentTarget).get("writeKey")||"");try{await fetchItems(next);setKey(next);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Unable to open queue")}setBusy(false)}
 async function sync(){setBusy(true);setMessage("");const response=await fetch("/api/founder-onboarding/sync",{method:"POST",headers:{"x-founder-key":key}});const result=await response.json();if(!response.ok){setMessage(result.error);setBusy(false);return}await fetchItems();setMessage(`${result.data.matched} accounts matched · ${result.data.advanced} stages advanced.`);setBusy(false)}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const response=await fetch("/api/founder-onboarding",{method:"POST",headers:{"Content-Type":"application/json","x-founder-key":key},body:JSON.stringify({name:form.get("name"),email:form.get("email"),stage:form.get("stage"),notes:form.get("notes")})});const result=await response.json();if(!response.ok){setMessage(result.error);return}setItems(current=>[result.data,...(current||[])]);e.currentTarget.reset();setMessage("Collector added to the onboarding queue.")}
 async function update(item:BetaCollector,stage:BetaStage){const response=await fetch("/api/founder-onboarding",{method:"PATCH",headers:{"Content-Type":"application/json","x-founder-key":key},body:JSON.stringify({...item,stage})});const result=await response.json();if(!response.ok){setMessage(result.error);return}setItems(current=>(current||[]).map(value=>value.id===item.id?result.data:value))}
 if(!items)return <section className="card betaGate"><div><div className="eyebrow">Founder access</div><h2>Open the beta onboarding queue</h2><p>Protected by the same Founder key used for private operations.</p></div><form onSubmit={unlock}><label><span>Founder write key</span><input name="writeKey" type="password" required/></label><button className="button" disabled={busy}>{busy?"Opening…":"Open queue"}</button></form>{message&&<output>{message}</output>}</section>;
 return <><div className="betaSync"><div><strong>Account-aware pipeline</strong><span>Match email addresses to private account milestones without reading collection details.</span></div><button className="button secondary" onClick={sync} disabled={busy}>{busy?"Synchronizing…":"Sync account progress"}</button></div><section className="betaMetrics"><article><span>Pipeline</span><strong>{summary.total}</strong><small>tracked collectors</small></article><article><span>Invited</span><strong>{summary.invited}</strong><small>awaiting signup</small></article><article><span>Imported</span><strong>{summary.imported}</strong><small>vault data loaded</small></article><article><span>Activated</span><strong>{summary.activated}</strong><small>reached launch value</small></article><article><span>Founder seats</span><strong>{summary.founderSeatsRemaining}</strong><small>remaining of 25</small></article></section>{message&&<output className="betaMessage">{message}</output>}<section className="betaLayout"><div className="betaList">{items.map(item=><article key={item.id}><div><small>{item.email}</small><h3>{item.name}</h3><p>{item.notes||"No follow-up notes yet."}</p></div><label><span>Stage</span><select value={item.stage} onChange={event=>update(item,event.target.value as BetaStage)}>{stages.map(stage=><option key={stage}>{stage}</option>)}</select></label><a className="button secondary" href={`mailto:${encodeURIComponent(item.email)}?subject=${encodeURIComponent("Your Cedriva invitation")}`}>Email</a></article>)}{!items.length&&<div className="emptyState">No beta collectors tracked yet.</div>}</div><aside className="card"><div className="eyebrow">White-glove onboarding</div><h2>Add a collector</h2><form className="betaForm" onSubmit={create}><label><span>Name</span><input name="name" required/></label><label><span>Email</span><input name="email" type="email" required/></label><label><span>Stage</span><select name="stage">{stages.map(stage=><option key={stage}>{stage}</option>)}</select></label><label><span>Notes</span><textarea name="notes" rows={4}/></label><button className="button">Add to queue</button></form></aside></section></>;
}
