"use client";
import{FormEvent,useMemo,useState}from"react";import type{TesterActivityRow}from"@/lib/beta-activity";
type Dashboard={generatedAt:string;summary:{testers:number;active:number;needsAttention:number;inventoryLots:number;smokes:number;openFeedback:number;recordedFailures:number;unresolvedFailures:number;recoveredFailures:number};testers:TesterActivityRow[]};type View="all"|"attention"|"recovered";
const when=(value?:string)=>value?new Date(value).toLocaleString():"Not recorded";
export function FounderBetaActivity(){
 const[key,setKey]=useState(""),[data,setData]=useState<Dashboard>(),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[view,setView]=useState<View>("all");
 const shown=useMemo(()=>data?.testers.filter(item=>view==="all"||(view==="attention"?item.state==="Needs attention":item.recoveryQueue.some(issue=>issue.state==="Recovered")))||[],[data,view]);
 async function load(next=key){setBusy(true);setMessage("");try{const response=await fetch("/api/founder-onboarding/activity-status",{cache:"no-store",headers:{"x-founder-key":next}});const result=await response.json();if(!response.ok)throw new Error(result.error||"Activity dashboard unavailable");setData(result.data)}catch(error){setMessage(error instanceof Error?error.message:"Activity dashboard unavailable")}finally{setBusy(false)}}
 async function unlock(event:FormEvent<HTMLFormElement>){event.preventDefault();const next=String(new FormData(event.currentTarget).get("writeKey")||"");setKey(next);await load(next)}
 if(!data)return <section className="card activityGate"><div><div className="eyebrow">Founder access</div><h2>Open tester activity</h2><p>Protected operational information. Cigar names, values, and provenance are not displayed.</p></div><form onSubmit={unlock}><label><span>Founder write key</span><input type="password" name="writeKey" required/></label><button className="button" disabled={busy}>{busy?"Opening…":"Open dashboard"}</button></form>{message&&<output>{message}</output>}</section>;
 return <><section className="activityToolbar"><div><div className="eyebrow">Current beta cohort</div><h2>{shown.length} tester{shown.length===1?"":"s"} shown</h2><p>Updated {when(data.generatedAt)}</p></div><div><button className={`button secondary ${view==="attention"?"selected":""}`} onClick={()=>setView(view==="attention"?"all":"attention")}>{view==="attention"?"Show everyone":"Unresolved only"}</button><button className={`button secondary ${view==="recovered"?"selected":""}`} onClick={()=>setView(view==="recovered"?"all":"recovered")}>{view==="recovered"?"Show everyone":"Recovered issues"}</button><button className="button secondary" disabled={busy} onClick={()=>load()}>{busy?"Refreshing…":"Refresh"}</button></div></section>{message&&<output className="activityMessage">{message}</output>}
 <section className="activityMetrics"><article><span>Testers</span><strong>{data.summary.testers}</strong><small>{data.summary.active} with recorded activity</small></article><article><span>Needs attention</span><strong>{data.summary.needsAttention}</strong><small>setup, feedback, or failure</small></article><article><span>Inventory</span><strong>{data.summary.inventoryLots}</strong><small>lots added or updated</small></article><article><span>Smokes</span><strong>{data.summary.smokes}</strong><small>journal entries</small></article><article><span>Unresolved</span><strong>{data.summary.unresolvedFailures}</strong><small>failed attempts still open</small></article><article><span>Recovered</span><strong>{data.summary.recoveredFailures}</strong><small>later attempts succeeded</small></article></section>
 <section className="testerActivityList">{shown.map(item=><article className={`card testerActivity ${item.state==="Needs attention"?"attention":"ready"}`} key={item.id}><header><div><small>{item.email}</small><h3>{item.name}</h3><span>{item.stage}</span></div><strong>{item.state}</strong></header><div className="testerActivityFacts"><div><span>Last login</span><b>{when(item.lastLoginAt)}</b></div><div><span>Last activity</span><b>{when(item.lastActivityAt)}</b></div><div><span>Phone app</span><b>{item.installationConfirmedAt?"Confirmed":"Not confirmed"}</b></div><div><span>Inventory</span><b>{item.inventoryLots} lot{item.inventoryLots===1?"":"s"}</b></div><div><span>Smoke log</span><b>{item.smokesLogged} entr{item.smokesLogged===1?"y":"ies"}</b></div><div><span>Feedback</span><b>{item.openFeedback} open</b></div></div>{item.reasons.length>0&&<section className="attentionReasons"><b>Needs follow-up</b><ul>{item.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></section>}{item.recoveryQueue.length>0&&<section className="recoveryQueue"><header><b>Automatic recovery queue</b><small>Repeated failures are grouped by action.</small></header>{item.recoveryQueue.map(issue=><article className={issue.state.toLowerCase()} key={issue.action}><div><strong>{issue.label}</strong><span>{issue.state} · {issue.failureCount} failed attempt{issue.failureCount===1?"":"s"}</span></div><dl><dt>Last failure</dt><dd>{when(issue.lastFailureAt)}</dd>{issue.lastSuccessAt&&<><dt>Later success</dt><dd>{when(issue.lastSuccessAt)}</dd></>}<dt>Build</dt><dd>{issue.version||"Unknown"}</dd><dt>Follow-up</dt><dd>{issue.recommendedFollowUp}</dd></dl></article>)}</section>}<section className="recentTesterActivity"><b>Recent activity</b>{item.recent.length?<ul>{item.recent.map(entry=><li key={`${entry.at}-${entry.label}`}><span>{entry.label}</span><small>{when(entry.at)}</small></li>)}</ul>:<p>No in-app activity recorded yet.</p>}</section></article>)}{!shown.length&&<div className="emptyState">No testers match this view.</div>}</section></>;
}
