"use client";

import { useEffect, useMemo, useState } from "react";
import "./industry-research-ledger.css";

type Proposal={proposal_id:string;profile_id:string;status:string;candidate_payload:{dossierId?:string;organization?:string;productLine?:string;vitola?:string;stage?:string;sourceUrl?:string;unresolved?:string[]}};
type Fact={fact_id:string;proposal_id:string;field_name:string;proposed_value:string;source_url:string;source_title:string;confidence:string;status:string;review_note?:string};
type Ledger={status:string;proposals:Proposal[];facts:Fact[]};

export function IndustryResearchLedger({writeKey}:{writeKey:string}){
  const[data,setData]=useState<Ledger>();const[busy,setBusy]=useState("");const[message,setMessage]=useState("");
  async function request(body?:unknown){const response=await fetch("/api/industry-research-ledger",{method:body?"POST":"GET",headers:{"x-founder-key":writeKey,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Research ledger unavailable");return result.data as Ledger}
  useEffect(()=>{request().then(setData).catch(error=>setMessage(error instanceof Error?error.message:"Unable to load research ledger"))},[writeKey]);
  const summary=useMemo(()=>{const facts=data?.facts||[];const accepted=facts.filter(item=>item.status==="approved").length,rejected=facts.filter(item=>item.status==="rejected").length,deeper=facts.filter(item=>item.status==="pending"&&item.review_note?.startsWith("Deeper research requested")).length;return{accepted,rejected,deeper,pending:facts.length-accepted-rejected-deeper}},[data]);
  async function act(body:unknown,label:string){setBusy(label);setMessage("");try{setData(await request(body));setMessage(label==="ingest"?"Dossier added once. Duplicate source/profile combinations were skipped.":"Field decision saved to the private knowledge history.")}catch(error){setMessage(error instanceof Error?error.message:"Update failed")}finally{setBusy("")}}
  if(!data)return <section className="card researchLedger"><div className="eyebrow">Step 2 · Your decisions</div><h2>Choose which facts Hojavía should keep</h2><p>{message?"The private review list could not open. Return to the founder access screen and open this review again.":"Opening the facts for review…"}</p></section>;
  return <section className="card researchLedger"><header><div><div className="eyebrow">Step 2 · Your decisions</div><h2>Choose which facts Hojavía should keep</h2><p>Each choice affects private background knowledge only. It does not publish anything.</p></div><span className="ledgerStage">First source review</span></header>
    <div className="ledgerMetrics"><article><strong>{data.proposals.length}</strong><span>cigars in this review</span></article><article><strong>{data.facts.length}</strong><span>facts to consider</span></article><article><strong>{summary.accepted}</strong><span>facts kept</span></article><article><strong>{summary.deeper}</strong><span>need more research</span></article></div>
    {!data.proposals.length?<div className="ledgerEmpty"><p>The OpusX one-source pilot is ready to become the first ledger dossier. Importing creates private review records only.</p><button className="button" disabled={Boolean(busy)} onClick={()=>act({action:"ingest-opusx-pilot"},"ingest")}>{busy?"Adding once…":"Add pilot to intake ledger"}</button></div>:<details><summary>Review {data.facts.length} field-level facts</summary><div className="ledgerFacts">{data.proposals.map(proposal=><article key={proposal.proposal_id}><header><span><strong>{proposal.candidate_payload.vitola}</strong><small>{proposal.candidate_payload.organization} · {proposal.candidate_payload.productLine}</small></span><a href={proposal.candidate_payload.sourceUrl} target="_blank" rel="noreferrer">Source ↗</a></header>{data.facts.filter(fact=>fact.proposal_id===proposal.proposal_id).map(fact=><div className="ledgerFact" key={fact.fact_id}><span><small>{fact.field_name}</small><strong>{String(fact.proposed_value)}</strong><em>{fact.confidence} confidence · {fact.status}{fact.review_note?` · ${fact.review_note}`:""}</em></span><div><button disabled={Boolean(busy)} onClick={()=>act({action:"review-fact",factId:fact.fact_id,decision:"accepted"},fact.fact_id)}>Accept</button><button disabled={Boolean(busy)} onClick={()=>act({action:"review-fact",factId:fact.fact_id,decision:"rejected"},fact.fact_id)}>Reject</button><button disabled={Boolean(busy)} onClick={()=>act({action:"review-fact",factId:fact.fact_id,decision:"deeper-research"},fact.fact_id)}>Research deeper</button></div></div>)}</article>)}</div></details>}
    {message&&<output aria-live="polite">{message}</output>}<div className="ledgerGuard"><strong>Efficient by design</strong><span>This review reuses one source, avoids a second AI search, prevents duplicate entries, and cannot publish publicly.</span></div>
  </section>
}
