"use client";

import { FormEvent, useState } from "react";

type RegistryRecord={id:string;record_type:"product"|"release"|"packaging";status:string;draft_payload:Record<string,unknown>;review_note?:string};

async function registryRequest(body:unknown){
  const response=await fetch("/api/partner-workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
  const result=await response.json();
  if(!response.ok)throw new Error(result.error||"Registry operation failed");
  return result.data;
}

export function IndustryRegistryWorkspace({partnerId,records,canEdit,onRefresh}:{partnerId:string;records:RegistryRecord[];canEdit:boolean;onRefresh:()=>Promise<void>}){
  const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[editing,setEditing]=useState<RegistryRecord>();
  async function save(event:FormEvent<HTMLFormElement>,kind:"Product"|"Release"|"Packaging"){
    event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);
    try{await registryRequest({action:`saveIndustry${kind}`,data:{...Object.fromEntries(form),partnerId,recordId:editing?.id}});event.currentTarget.reset();setEditing(undefined);await onRefresh();setMessage(`${kind} draft saved privately. It is not public until independent verification, approval, and publication are complete.`)}catch(error){setMessage(error instanceof Error?error.message:"Unable to save registry draft")}finally{setBusy(false)}
  }
  async function submit(item:RegistryRecord){setBusy(true);try{await registryRequest({action:"submitIndustryRegistry",partnerId,recordId:item.id});await onRefresh();setMessage("Official registry record submitted for independent verification. It remains private.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to submit registry record")}finally{setBusy(false)}}
  const draft=editing?.draft_payload||{};
  return <section className="card industryRegistryWorkspace"><div className="sectionHead"><div><div className="eyebrow">Official product, release & artifact registry</div><h2>Preserve facts beyond the announcement.</h2><p>Products, dated releases, and packaging revisions remain separate, versioned records. “Official” always identifies your organization as the source.</p></div><a className="button secondary" href="/industry/registry">Open public registry</a></div>{message&&<output className="workspaceMessage">{message}</output>}
    <div className="registryDraftList">{records.map(item=><article key={item.id}><span><small>{item.record_type} · {item.status}</small><strong>{String(item.draft_payload.brand||item.draft_payload.releaseName||item.draft_payload.revisionName||"Untitled record")}</strong><p>{String(item.draft_payload.line||item.draft_payload.productName||"")}</p>{item.review_note&&<em>Independent review: {item.review_note}</em>}</span><div>{canEdit&&["draft","changes_requested","published"].includes(item.status)&&<button className="textButton" onClick={()=>setEditing(item)}>Edit</button>}{canEdit&&["draft","changes_requested","published"].includes(item.status)&&<button className="button secondary" disabled={busy} onClick={()=>submit(item)}>Submit</button>}</div></article>)}</div>
    {canEdit&&<div className="registryForms">
      <details open={editing?.record_type==="product"}><summary>Official product record</summary><form key={`product-${editing?.id||"new"}`} onSubmit={event=>save(event,"Product")}><div className="formPair"><label><span>Brand</span><input name="brand" defaultValue={String(draft.brand||"")} required/></label><label><span>Line</span><input name="line" defaultValue={String(draft.line||"")} required/></label></div><label><span>Official product description</span><textarea name="description" rows={4} minLength={40} defaultValue={String(draft.description||"")} required/></label><div className="formPair"><label><span>Production status</span><select name="productionStatus" defaultValue={String(draft.productionStatus||"current")}><option value="current">Current</option><option value="limited">Limited</option><option value="seasonal">Seasonal</option><option value="discontinued">Discontinued</option><option value="historical">Historical</option></select></label><label><span>Country</span><input name="country" defaultValue={String(draft.country||"")}/></label></div><div className="formPair"><label><span>Factory</span><input name="factory" defaultValue={String(draft.factory||"")}/></label><label><span>Blender</span><input name="blender" defaultValue={String(draft.blender||"")}/></label></div><div className="formTriplet"><label><span>Wrapper</span><input name="wrapper" defaultValue={String(draft.wrapper||"")}/></label><label><span>Binder</span><input name="binder" defaultValue={String(draft.binder||"")}/></label><label><span>Strength</span><input name="strength" defaultValue={String(draft.strength||"")}/></label></div><label><span>Filler</span><input name="filler" defaultValue={String(draft.filler||"")}/></label><label><span>Official product URL</span><input name="officialProductUrl" type="url" defaultValue={String(draft.officialProductUrl||"")}/></label><button className="button" disabled={busy}>Save private product draft</button></form></details>
      <details open={editing?.record_type==="release"}><summary>Dated release record</summary><form key={`release-${editing?.id||"new"}`} onSubmit={event=>save(event,"Release")}><div className="formPair"><label><span>Product name</span><input name="productName" defaultValue={String(draft.productName||"")} required/></label><label><span>Release name</span><input name="releaseName" defaultValue={String(draft.releaseName||"")} required/></label></div><div className="formTriplet"><label><span>Release date</span><input name="releaseDate" type="date" defaultValue={String(draft.releaseDate||"")} required/></label><label><span>Release type</span><select name="releaseType" defaultValue={String(draft.releaseType||"regular_production")}><option value="regular_production">Regular production</option><option value="limited_edition">Limited edition</option><option value="annual">Annual</option><option value="regional">Regional</option><option value="retailer_exclusive">Retailer exclusive</option><option value="event_exclusive">Event exclusive</option><option value="historical">Historical</option></select></label><label><span>Availability</span><select name="availabilityStatus" defaultValue={String(draft.availabilityStatus||"announced")}><option value="announced">Announced</option><option value="shipping">Shipping</option><option value="available">Available</option><option value="sold_out">Sold out</option><option value="retired">Retired</option><option value="historical">Historical</option></select></label></div><label><span>Vitolas and dimensions</span><textarea name="vitolas" rows={3} defaultValue={String(draft.vitolas||"")} required/></label><div className="formPair"><label><span>MSRP with market/date</span><input name="msrp" defaultValue={String(draft.msrp||"")}/></label><label><span>Production quantity</span><input name="productionQuantity" defaultValue={String(draft.productionQuantity||"")}/></label></div><label><span>Markets</span><input name="markets" defaultValue={String(draft.markets||"")}/></label><label><span>Official release URL</span><input name="officialReleaseUrl" type="url" defaultValue={String(draft.officialReleaseUrl||"")}/></label><label><span>Official notes</span><textarea name="notes" rows={3} defaultValue={String(draft.notes||"")}/></label><button className="button" disabled={busy}>Save private release draft</button></form></details>
      <details open={editing?.record_type==="packaging"}><summary>Packaging & authentication revision</summary><form key={`packaging-${editing?.id||"new"}`} onSubmit={event=>save(event,"Packaging")}><div className="formPair"><label><span>Product name</span><input name="productName" defaultValue={String(draft.productName||"")} required/></label><label><span>Revision name</span><input name="revisionName" defaultValue={String(draft.revisionName||"")} required/></label></div><div className="formTriplet"><label><span>Artifact</span><select name="artifactType" defaultValue={String(draft.artifactType||"band")}><option value="band">Band</option><option value="box">Box</option><option value="bundle">Bundle</option><option value="seal">Seal</option><option value="cellophane">Cellophane</option><option value="tube">Tube</option><option value="humidor">Humidor</option><option value="other">Other</option></select></label><label><span>Effective from</span><input name="effectiveFrom" type="date" defaultValue={String(draft.effectiveFrom||"")} required/></label><label><span>Effective to</span><input name="effectiveTo" type="date" defaultValue={String(draft.effectiveTo||"")}/></label></div><label><span>Visible change</span><textarea name="description" rows={4} minLength={40} defaultValue={String(draft.description||"")} required/></label><div className="formPair"><label><span>Box count</span><input name="boxCount" defaultValue={String(draft.boxCount||"")}/></label><label><span>Box-code guidance</span><textarea name="boxCodeGuidance" rows={3} defaultValue={String(draft.boxCodeGuidance||"")}/></label></div><label><span>Authentication guidance</span><textarea name="authenticationGuidance" rows={4} defaultValue={String(draft.authenticationGuidance||"")}/></label><label><span>Counterfeit warning</span><textarea name="counterfeitWarning" rows={4} defaultValue={String(draft.counterfeitWarning||"")}/></label><div className="formPair"><label><span>Official source URL</span><input name="officialSourceUrl" type="url" defaultValue={String(draft.officialSourceUrl||"")}/></label><label><span>Official image URL</span><input name="imageUrl" type="url" defaultValue={String(draft.imageUrl||"")}/></label></div><button className="button" disabled={busy}>Save private artifact draft</button></form></details>
    </div>}
    {editing&&<button className="textButton" onClick={()=>setEditing(undefined)}>Cancel editing</button>}
  </section>;
}
