"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { IndustryWorkspace } from "@/components/industry-workspace";
import { IndustryRegistryWorkspace } from "@/components/industry-registry-workspace";

type Member={id:string;displayName:string;email:string;role:"owner"|"administrator"|"editor"|"analyst"|"viewer";status:"invited"|"active"|"revoked";invitationExpiresAt?:string;acceptedAt?:string;lastAccessedAt?:string};
type Campaign={id:string;name:string;code:string;channel:string;status:"draft"|"review"|"approved"|"active"|"paused"|"ended";starts_at?:string;ends_at?:string;commission_type:string;commission_rate:number;attribution_window_days:number;hold_days:number};
type ReadinessItem={id:string;item_key:string;category:string;title:string;description:string;required:boolean;status:"pending"|"submitted"|"approved"|"changes_requested"|"waived";partner_note?:string;evidence_url?:string;founder_note?:string;updated_at:string};
type Workspace={partner:{id:string;name:string;slug:string;partnerType:string;status:string};role:Member["role"];permissions:{createCampaign:boolean;editCampaign:boolean;submitForReview:boolean;manageTeam:boolean;viewPayouts:boolean;submitReadiness:boolean;approve:false;launch:false;pause:false};campaigns:Campaign[];members:Member[];readiness:{items:ReadinessItem[];summary:{approved:number;required:number;complete:boolean}};industry:{profile:{id:string;status:string;draft_payload?:Record<string,unknown>;published_payload?:Record<string,unknown>;review_note?:string}|null;publications:{id:string;publication_type:string;status:string;draft_payload:Record<string,unknown>;published_payload?:Record<string,unknown>;review_note?:string;published_at?:string}[];registryRecords:{id:string;record_type:"product"|"release"|"packaging";status:string;draft_payload:Record<string,unknown>;review_note?:string}[]};metrics:{clicks:number;attributedCollectors:number;paidConversions:number;netRevenueCents:number;commissionCents:number}};

const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);

export function PartnerWorkspace(){
  const[workspaces,setWorkspaces]=useState<Workspace[]>();const[selectedId,setSelectedId]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[lastInvitation,setLastInvitation]=useState("");
  const selected=useMemo(()=>workspaces?.find(item=>item.partner.id===selectedId)||workspaces?.[0],[workspaces,selectedId]);
  async function request(body?:unknown){const response=await fetch("/api/partner-workspace",{method:body?"POST":"GET",headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Workspace operation failed");return result.data}
  async function load(){try{const data=await request();setWorkspaces(data.workspaces);if(!selectedId&&data.workspaces[0])setSelectedId(data.workspaces[0].partner.id)}catch(error){setMessage(error instanceof Error?error.message:"Unable to open workspace")}}
  useEffect(()=>{void load()},[]);
  async function createCampaign(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const values=Object.fromEntries(form);values.partnerId=selected.partner.id;values.destinationPath="/partners/join";values.startsAt=new Date(String(values.startsAt)).toISOString();values.endsAt=new Date(String(values.endsAt)).toISOString();try{await request({action:"createCampaign",data:values});event.currentTarget.reset();await load();setMessage("Draft saved for your organization. It is not approved, testable, or live.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to save draft")}finally{setBusy(false)}}
  async function submit(campaign:Campaign){if(!selected)return;setBusy(true);try{await request({action:"submitCampaign",partnerId:selected.partner.id,campaignId:campaign.id});await load();setMessage("Submitted for Cedriva founder review. This does not approve or launch the campaign.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to submit campaign")}finally{setBusy(false)}}
  async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);const form=new FormData(event.currentTarget);try{const data=await request({action:"inviteMember",data:{...Object.fromEntries(form),partnerId:selected.partner.id}});const link=`${window.location.origin}${data.invitationPath}`;setLastInvitation(link);await navigator.clipboard.writeText(link);event.currentTarget.reset();await load();setMessage("Secure invitation created and copied. Send it only to the named recipient.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to create invitation")}finally{setBusy(false)}}
  async function changeRole(member:Member,role:Member["role"]){if(!selected)return;setBusy(true);try{await request({action:"changeMemberRole",partnerId:selected.partner.id,membershipId:member.id,role});await load();setMessage("Role updated and recorded in the audit history.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to change role")}finally{setBusy(false)}}
  async function revoke(member:Member){if(!selected||!window.confirm(`Revoke ${member.displayName}'s workspace access immediately?`))return;setBusy(true);try{await request({action:"revokeMember",partnerId:selected.partner.id,membershipId:member.id});await load();setMessage("Workspace access revoked.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to revoke access")}finally{setBusy(false)}}
  async function submitReadiness(event:FormEvent<HTMLFormElement>,item:ReadinessItem){event.preventDefault();if(!selected)return;setBusy(true);const form=new FormData(event.currentTarget);try{await request({action:"submitReadiness",data:{partnerId:selected.partner.id,itemId:item.id,note:form.get("note"),evidenceUrl:form.get("evidenceUrl")}});await load();setMessage(`${item.title} submitted for founder review. Submission does not approve the item or activate the partnership.`)}catch(error){setMessage(error instanceof Error?error.message:"Unable to submit readiness evidence")}finally{setBusy(false)}}
  if(workspaces===undefined)return <section className="card workspaceLoading"><div className="eyebrow">Secure organization access</div><h2>Opening your workspace…</h2></section>;
  if(!workspaces.length)return <section className="card workspaceEmpty"><div className="eyebrow">Partner workspaces</div><h2>No active organization access</h2><p>A Cedriva founder or organization owner must invite your verified account before a workspace appears here.</p><a className="button secondary" href="/">Return to Cedriva</a></section>;
  if(!selected)return null;
  return <>{message&&<output className="workspaceMessage">{message}</output>}<section className="workspaceBar"><label><span>Organization</span><select value={selected.partner.id} onChange={event=>setSelectedId(event.target.value)}>{workspaces.map(item=><option value={item.partner.id} key={item.partner.id}>{item.partner.name}</option>)}</select></label><div><span>Your role</span><strong>{selected.role}</strong></div><div className="founderBoundary"><span>Founder boundary</span><strong>Partners cannot approve, launch, or pause</strong></div></section>
    <section className="workspaceMetrics"><article><span>Tracked visits</span><strong>{selected.metrics.clicks}</strong></article><article><span>Attributed collectors</span><strong>{selected.metrics.attributedCollectors}</strong></article><article><span>Paid conversions</span><strong>{selected.metrics.paidConversions}</strong></article><article><span>Net attributed revenue</span><strong>{money(selected.metrics.netRevenueCents)}</strong></article><article><span>Recorded commission</span><strong>{selected.permissions.viewPayouts?money(selected.metrics.commissionCents):"Restricted"}</strong></article></section>
    <section className="card readinessCenter"><div className="sectionHead"><div><div className="eyebrow">Partner readiness</div><h2>Earn activation through evidence.</h2><p>{selected.readiness.summary.approved} of {selected.readiness.summary.required} required controls approved. Partners submit facts; Cedriva’s founder reviews each control independently.</p></div><strong className={selected.readiness.summary.complete?"readyComplete":"readyProgress"}>{selected.readiness.summary.complete?"Ready for founder activation":"Not active"}</strong></div><div className="readinessGrid">{selected.readiness.items.map(item=><article className={`readinessItem ${item.status}`} key={item.id}><header><span>{item.category}</span><em>{item.status.replace("_"," ")}</em></header><h3>{item.title}</h3><p>{item.description}</p>{item.partner_note&&<small><strong>Submitted:</strong> {item.partner_note}</small>}{item.founder_note&&<small><strong>Founder response:</strong> {item.founder_note}</small>}{item.evidence_url&&<a className="textLink" href={item.evidence_url} target="_blank" rel="noreferrer">Open submitted evidence ↗</a>}{selected.permissions.submitReadiness&&!["approved","waived"].includes(item.status)&&<form onSubmit={event=>submitReadiness(event,item)}><label><span>Evidence note</span><textarea name="note" rows={3} minLength={10} defaultValue={item.status==="changes_requested"?item.partner_note:""} required/></label><label><span>Optional evidence URL</span><input name="evidenceUrl" type="url" defaultValue={item.status==="changes_requested"?item.evidence_url:""} placeholder="https://"/></label><button className="button secondary" disabled={busy}>{item.status==="submitted"?"Update submission":"Submit for review"}</button></form>}</article>)}</div>{!selected.readiness.items.length&&<div className="emptyState">The founder has not initialized this organization’s readiness record.</div>}<p className="readinessSafety"><strong>Do not upload or paste banking credentials, tax identifiers, passwords, or collector information.</strong> Readiness records document approvals—not secrets.</p></section>
    <IndustryWorkspace partnerId={selected.partner.id} profile={selected.industry.profile} publications={selected.industry.publications} canEdit={selected.permissions.submitReadiness} onRefresh={load}/>
    <IndustryRegistryWorkspace partnerId={selected.partner.id} records={selected.industry.registryRecords} canEdit={selected.permissions.submitReadiness} onRefresh={load}/>
    <section className="workspaceLayout"><div className="workspaceCampaigns"><div className="sectionHead"><div><div className="eyebrow">Campaign preparation</div><h2>Draft and review queue</h2><p>Partners prepare factual campaign records. Cedriva’s founder separately reviews, approves, and launches.</p></div></div>{selected.campaigns.map(campaign=><article key={campaign.id}><div><small>{campaign.channel} · {campaign.status}</small><h3>{campaign.name}</h3><p>{campaign.attribution_window_days}-day attribution · {campaign.commission_type==="percentage"?`${campaign.commission_rate}%`:`${money(campaign.commission_rate)}`} · {campaign.hold_days}-day hold</p><span>{campaign.starts_at?new Date(campaign.starts_at).toLocaleString():"No start"} → {campaign.ends_at?new Date(campaign.ends_at).toLocaleString():"No end"}</span></div><code>{campaign.status==="active"?`/r/${campaign.code}`:"Link withheld"}</code>{selected.permissions.submitForReview&&["draft","paused"].includes(campaign.status)&&<button className="button secondary" disabled={busy} onClick={()=>submit(campaign)}>Submit for founder review</button>}</article>)}{!selected.campaigns.length&&<div className="emptyState">No campaigns have been prepared for this organization.</div>}</div>
      {selected.permissions.createCampaign&&<aside className="card"><div className="eyebrow">Partner-authored record</div><h2>Prepare a draft</h2><form onSubmit={createCampaign}><label><span>Campaign name</span><input name="name" required/></label><label><span>Referral code</span><input name="code" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></label><label><span>Channel</span><select name="channel"><option value="email">Email</option><option value="website">Website</option><option value="social">Social</option><option value="event">Event</option><option value="qr">QR code</option><option value="creator">Creator</option><option value="other">Other</option></select></label><div className="formPair"><label><span>Starts</span><input name="startsAt" type="datetime-local" required/></label><label><span>Ends</span><input name="endsAt" type="datetime-local" required/></label></div><div className="formPair"><label><span>Attribution days</span><input name="attributionWindowDays" type="number" min="1" max="365" defaultValue="30"/></label><label><span>Hold days</span><input name="holdDays" type="number" min="0" max="180" defaultValue="30"/></label></div><div className="formPair"><label><span>Commission</span><select name="commissionType"><option value="percentage">Percentage</option><option value="fixed">Fixed cents</option></select></label><label><span>Rate</span><input name="commissionRate" type="number" min="0" step=".01" required/></label></div><div className="workspaceChecks"><label><input type="checkbox" name="termsConfirmed" value="true" required/>Terms confirmed</label><label><input type="checkbox" name="disclosureApproved" value="true" required/>Disclosure approved</label><label><input type="checkbox" name="audienceConsentConfirmed" value="true" required/>Audience consent confirmed</label><label><input type="checkbox" name="privacyReviewed" value="true" required/>Privacy reviewed</label></div><button className="button" disabled={busy}>Save inactive draft</button></form></aside>}</section>
    <section className="workspaceTeam card"><div className="sectionHead"><div><div className="eyebrow">Organization-scoped access</div><h2>Team and roles</h2><p>Access can be changed or revoked without affecting collector accounts or records.</p></div></div><div className="teamRows">{selected.members.map(member=><article key={member.id}><span><strong>{member.displayName}</strong><small>{member.email||"Organization team member"} · {member.status}</small></span>{selected.permissions.manageTeam?<select value={member.role} disabled={busy} onChange={event=>changeRole(member,event.target.value as Member["role"])}><option>owner</option><option>administrator</option><option>editor</option><option>analyst</option><option>viewer</option></select>:<em>{member.role}</em>}{selected.permissions.manageTeam&&<button className="button secondary" disabled={busy} onClick={()=>revoke(member)}>Revoke</button>}</article>)}</div>{selected.permissions.manageTeam&&<form className="teamInvite" onSubmit={invite}><label><span>Name</span><input name="displayName" required/></label><label><span>Email</span><input name="email" type="email" required/></label><label><span>Role</span><select name="role"><option value="administrator">Administrator</option><option value="editor">Editor</option><option value="analyst">Analyst</option><option value="viewer">Viewer</option><option value="owner">Owner</option></select></label><label><span>Expires in</span><select name="expiresInDays"><option value="7">7 days</option><option value="3">3 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><button className="button" disabled={busy}>Create secure invitation</button></form>}{lastInvitation&&<div className="invitationLink"><strong>Most recent invitation</strong><code>{lastInvitation}</code><button className="button secondary" onClick={()=>navigator.clipboard.writeText(lastInvitation)}>Copy</button></div>}</section>
  </>;
}
