"use client";
import { FormEvent,useMemo,useState } from "react";
import type { CatalogCigar,AvailabilityListing } from "@/lib/types";
import type { CigarResearch } from "@/lib/cigar-research";
import { createClientUuid } from "@/lib/client-uuid";

const fields:[[keyof CatalogCigar,string],...[keyof CatalogCigar,string][]]=[["dimensions","Size"],["country","Country"],["factory","Factory"],["blender","Blender"],["wrapper","Wrapper"],["binder","Binder"],["filler","Filler"],["strength","Stated strength"],["packaging","Packaging"],["releaseYear","Release year"],["edition","Edition"]];
const clean=(value:string)=>value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
function money(value:number|undefined){return value===undefined?"Price not stated":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value)}

export function ResearchAnyCigar({catalog}:{catalog:CatalogCigar[]}){
  const[query,setQuery]=useState("");const[known,setKnown]=useState<CatalogCigar>();const[live,setLive]=useState<CigarResearch>();const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[saved,setSaved]=useState(false);
  const identity=live?.profile?`${live.profile.brand} ${live.profile.line} ${live.profile.vitola}`:known?`${known.brand} ${known.line} ${known.vitola}`:query;
  const knownFields=useMemo(()=>known?fields.filter(([key])=>Boolean(known[key])):[],[known]);
  function searchKnown(event:FormEvent){event.preventDefault();setLive(undefined);setSaved(false);const terms=clean(query).split(" ").filter(Boolean);const matches=catalog.filter(item=>terms.every(term=>clean(`${item.brand} ${item.line} ${item.vitola} ${item.releaseYear||""}`).includes(term)));setKnown(matches.length===1?matches[0]:undefined);setMessage(matches.length===1?"Found in Hojavía’s cigar reference. No live research credits were used.":matches.length>1?"Several cigars match. Add the exact line, size, or year, or run live research.":"This cigar is not complete in Hojavía’s reference yet. Live research can investigate it.")}
  async function researchLive(){setBusy(true);setMessage("Researching the exact cigar and current retailer pages…");setLive(undefined);setSaved(false);try{const response=await fetch("/api/cigar-research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Research failed");setLive(result.data);setKnown(undefined);setMessage("Research complete. Review the exact cigar and sources below.")}catch(error){setMessage(error instanceof Error?error.message:"Research failed")}finally{setBusy(false)}}
  async function saveWishlist(){if(!live)return;setMessage("Saving to your wishlist…");try{const p=live.profile,response=await fetch("/api/wishlist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brand:p.brand,line:p.line,vitola:p.vitola,priority:"Standard",sourceUrl:live.sources[0]?.url,status:"Watching",notes:`Research confidence: ${live.confidence}. ${p.summary}`,createdAt:new Date().toISOString(),submissionId:createClientUuid()})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not save wishlist item");setSaved(true);setMessage("Saved to your wishlist.")}catch(error){setMessage(error instanceof Error?error.message:"Could not save wishlist item")}}
  const listings=(live?.availability.listings||[]) as AvailabilityListing[];
  return <section className="researchAnyCigar card" id="research-any-cigar"><div><div className="eyebrow">Research any cigar</div><h2>Type the cigar. Hojavía builds the record.</h2><p>Start with our existing reference at no research cost. If details are missing, run one live search for the exact cigar, trusted sources, and current retailer observations.</p></div><form onSubmit={searchKnown}><label><span>Which cigar?</span><input value={query} onChange={event=>setQuery(event.target.value)} minLength={3} maxLength={300} required placeholder="Brand, line, exact vitola, and year if known"/></label><button className="button" disabled={busy}>Search Hojavía first</button></form>{message&&<output aria-live="polite">{message}</output>}{(known||(!busy&&query.length>=3&&!live))&&<button type="button" className="button secondary" disabled={busy} onClick={researchLive}>{busy?"Researching…":"Research live sources and retailer evidence · uses credits"}</button>}{known&&<Result title={`${known.brand} ${known.line}`} vitola={known.vitola} summary={known.masterNotes||"Hojavía already has a record for this exact cigar."} confidence={known.confidence||"Unrated"} facts={knownFields.map(([key,label])=>[label,String(known[key])])} sources={known.sourceUrl?[{name:known.sourceName||"Documented source",url:known.sourceUrl,supports:"Existing cigar record"}]:[]} listings={[]}/>} {live&&<><Result title={`${live.profile.brand} ${live.profile.line}`} vitola={live.profile.vitola} summary={live.profile.summary} confidence={live.confidence} facts={fields.filter(([key])=>Boolean(live.profile[key as keyof typeof live.profile])).map(([key,label])=>[label,String(live.profile[key as keyof typeof live.profile])])} sources={live.sources} listings={listings}/><div className="researchCigarActions"><a className="button" href={`/cigar-somm?cigarName=${encodeURIComponent(identity)}`}>Ask Cigar Somm</a><a className="button secondary" href={`/records?cigarName=${encodeURIComponent(identity)}#log-smoke`}>Log a smoke</a><a className="button secondary" href={`/inventory?cigarName=${encodeURIComponent(identity)}#mobile-intake`}>Add to Vault</a><button className="button secondary" type="button" disabled={saved} onClick={saveWishlist}>{saved?"Saved to wishlist":"Save to wishlist"}</button></div></>}</section>
}
function Result({title,vitola,summary,confidence,facts,sources,listings}:{title:string;vitola:string;summary:string;confidence:string;facts:string[][];sources:{name:string;url:string;supports:string}[];listings:AvailabilityListing[]}){return <div className="cigarResearchResult"><header><div><small>{confidence} confidence</small><h3>{title}</h3><strong>{vitola}</strong></div></header><p>{summary}</p><dl>{facts.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{sources.length>0&&<div className="researchSources"><h4>Sources</h4>{sources.map(source=><a href={source.url} target="_blank" rel="noreferrer" key={source.url}><strong>{source.name}</strong><small>{source.supports}</small></a>)}</div>}<div className="researchRetailers"><h4>Retailer observations</h4>{listings.length?listings.map(listing=><article key={listing.url}><span><strong>{listing.seller}</strong><small>{listing.availability} · observed during research; verify independently</small></span><b>{money(listing.unitPrice??listing.askingPrice)}</b></article>):<p>No exact current retailer listing was confirmed. Hojavía will not substitute a nearby cigar.</p>}<p className="small">Research only. The mobile app does not open tobacco purchase pages or use affiliate tracking.</p></div></div>}
