"use client";
import { useEffect, useState } from "react";
import type { AvailabilityListing, InventoryItem } from "@/lib/types";

type RetailerRating={score?:number;count:number;confidence:"Not yet rated"|"Early evidence"|"Developing"|"Established"};
type Research={checkedAt:string;summary:string;legalCaution:string;listings:AvailabilityListing[];ratings:Record<string,RetailerRating>};
type PurchaseSession={id:string;retailer_key:string;retailer_name:string;status:"clicked"|"evidence_pending"|"verified"|"rejected"|"expired";purchase_date?:string;receipt_verified_at?:string};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
function key(value:string){return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)}

export function RetailerMarket({item}:{item:InventoryItem}){
  const[data,setData]=useState<Research>();
  const[busy,setBusy]=useState("");
  const[message,setMessage]=useState("");
  const[sessions,setSessions]=useState<Record<string,string>>({});
  const[purchases,setPurchases]=useState<PurchaseSession[]>([]);
  useEffect(()=>{fetch(`/api/retailer-market/purchases?inventoryId=${encodeURIComponent(item.inventoryId)}`).then(response=>response.json()).then(result=>setPurchases(result.data||[])).catch(()=>{})},[item.inventoryId]);

  async function search(){setBusy("search");setMessage("");try{const response=await fetch("/api/retailer-market/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({inventoryId:item.inventoryId})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Search failed");setData(result.data);setMessage(`Checked ${result.data.listings.length} exact-match retailer lead${result.data.listings.length===1?"":"s"}. Confirm price and availability with the seller.`)}catch(error){setMessage(error instanceof Error?error.message:"Retailer search failed")}finally{setBusy("")}}
  async function openListing(listing:AvailabilityListing){setBusy(listing.url);setMessage("");try{const response=await fetch("/api/retailer-market/click",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({inventoryId:item.inventoryId,listing})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Retailer link is unavailable");setSessions(current=>({...current,[listing.url]:result.data.purchaseSessionId}));window.open(result.data.outboundUrl,"_blank","noopener,noreferrer");setMessage("Retailer opened. If you purchase, return here to submit private transaction evidence before rating.")}catch(error){setMessage(error instanceof Error?error.message:"Retailer link is unavailable")}finally{setBusy("")}}
  async function evidence(event:React.FormEvent<HTMLFormElement>,listing:AvailabilityListing){event.preventDefault();setBusy(`evidence:${listing.url}`);setMessage("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/retailer-market/purchases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({purchaseSessionId:sessions[listing.url],orderReference:form.get("orderReference"),receiptUrl:form.get("receiptUrl"),purchaseDate:form.get("purchaseDate")})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Evidence could not be saved");setMessage(result.message);setPurchases(current=>[{id:sessions[listing.url],retailer_key:key(listing.seller),retailer_name:listing.seller,status:"evidence_pending"},...current])}catch(error){setMessage(error instanceof Error?error.message:"Evidence could not be saved")}finally{setBusy("")}}
  async function rate(event:React.FormEvent<HTMLFormElement>,purchaseSessionId:string){event.preventDefault();setBusy(`rate:${purchaseSessionId}`);setMessage("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/retailer-market/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({purchaseSessionId,overall:Number(form.get("overall")),fulfillment:Number(form.get("fulfillment")),packaging:Number(form.get("packaging")),authenticityConfidence:form.get("authenticityConfidence"),review:form.get("review")})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Rating could not be published");setMessage(result.message)}catch(error){setMessage(error instanceof Error?error.message:"Rating could not be published")}finally{setBusy("")}}

  const verified=purchases.filter(purchase=>purchase.status==="verified");
  return <>
    <section className="section card retailerMarketIntro"><div><div className="eyebrow">Exact-cigar retailer comparison</div><h1>Find this cigar</h1><p>Hojavía searches for the exact brand, line, vitola, and compatible release—not a nearby substitute. Prices shown are market asking prices, never proof of a completed sale.</p></div><button className="button" disabled={Boolean(busy)} onClick={search}>{busy==="search"?"Checking trusted sellers…":"Find current sellers"}</button></section>
    {message&&<output className="wideMessage" aria-live="polite">{message}</output>}
    {data&&<section className="section"><div className="sectionHead"><div><div className="eyebrow">Availability checked {new Date(data.checkedAt).toLocaleString()}</div><h2>{data.summary}</h2></div></div><div className="retailerListingGrid">{data.listings.map(listing=>{const rating=data.ratings[key(listing.seller)];return <article className="card" key={listing.url}><header><div><span>{listing.sellerType}</span><h3>{listing.seller}</h3></div><b>{listing.availability}</b></header><p>{listing.title}</p><div className="retailerPrices"><span><small>Listing</small><strong>{listing.askingPrice===undefined?"Confirm with seller":money.format(listing.askingPrice)}</strong></span><span><small>Per cigar</small><strong>{listing.unitPrice===undefined?"Not normalized":money.format(listing.unitPrice)}</strong></span><span><small>Quantity</small><strong>{listing.quantity??"Unclear"}</strong></span></div><div className="retailerTrust"><strong>{rating?.score===undefined?"Hojavía rating: not yet established":`Hojavía ${rating.score} / 5`}</strong><small>{rating?.count?`${rating.count} verified transaction${rating.count===1?"":"s"} · ${rating.confidence}`:"Only verified transactions can affect this score."} Seller payment never changes ranking.</small></div><p className="small">{listing.notes}</p><button className="button secondary" disabled={Boolean(busy)} onClick={()=>openListing(listing)}>{busy===listing.url?"Opening safely…":"View seller ↗"}</button>{sessions[listing.url]&&<details className="purchaseEvidence"><summary>I purchased from this listing</summary><form onSubmit={event=>evidence(event,listing)}><p>Order information stays private and does not create a rating until the transaction is verified.</p><label><span>Purchase date</span><input name="purchaseDate" type="date" required/></label><label><span>Order reference</span><input name="orderReference" required minLength={4}/><small>Stored as a one-way hash, not displayed publicly.</small></label><label><span>Private receipt or provenance link</span><input name="receiptUrl" type="url" placeholder="https://…" required/></label><button className="button" disabled={Boolean(busy)}>{busy===`evidence:${listing.url}`?"Submitting evidence…":"Submit for verification"}</button></form></details>}</article>})}</div>{!data.listings.length&&<div className="emptyState"><strong>No defensible exact match was found.</strong><p>Hojavía will not substitute another vitola or release merely to show a seller.</p></div>}<p className="marketDisclosure">{data.legalCaution} You must be 21 or older and follow all applicable shipping and tobacco laws.</p></section>}
    {purchases.some(purchase=>purchase.status==="evidence_pending")&&<section className="section card"><div className="eyebrow">Transaction verification</div><h2>Evidence pending</h2><p>Your submitted purchase evidence has no effect on any retailer score until it is verified. Order details remain private.</p></section>}
    {verified.length>0&&<section className="section"><div className="sectionHead"><div><div className="eyebrow">Verified purchases</div><h2>Rate an experience you can prove.</h2></div></div><div className="retailerListingGrid">{verified.map(purchase=><form className="card purchaseEvidence" key={purchase.id} onSubmit={event=>rate(event,purchase.id)}><h3>{purchase.retailer_name}</h3><p>Verified purchase{purchase.purchase_date?` · ${purchase.purchase_date}`:""}</p><label><span>Overall</span><select name="overall" required>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} / 5</option>)}</select></label><label><span>Fulfillment</span><select name="fulfillment" required>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} / 5</option>)}</select></label><label><span>Packaging</span><select name="packaging" required>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} / 5</option>)}</select></label><label><span>Authenticity confidence</span><select name="authenticityConfidence"><option>High</option><option>Medium</option><option>Concern</option></select></label><label><span>Private-to-public review text</span><textarea name="review" rows={3} maxLength={1000}/></label><button className="button" disabled={Boolean(busy)}>{busy===`rate:${purchase.id}`?"Publishing verified rating…":"Publish verified rating"}</button></form>)}</div></section>}
    <section className="section card retailerRatingPolicy"><div><div className="eyebrow">Hojavía verified-retailer standard</div><h2>Reputation must be earned through real transactions.</h2></div><div className="trustGrid"><article><strong>One order, one review</strong><p>A unique verified purchase session can publish only one rating.</p></article><article><strong>Evidence before influence</strong><p>Clicked links and self-submitted claims have zero effect until receipt evidence is verified.</p></article><article><strong>Manipulation resistance</strong><p>Scores use weighted evidence, reviewer diversity, and volume—not a simple average that one person can swing.</p></article><article><strong>Commercial independence</strong><p>Affiliate compensation is disclosed and never changes retailer scores or search ranking.</p></article></div></section>
  </>;
}
